### ISSUE TITLE
There is no option to search for mp4 files in advanced search

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1001]
**What is the URL that originated the issue?**

**What happened?**
There is no option for .mp4 files in advanced search, type:mp4

**What should have happened?**
MP4 should be in the list (it would be usefull)

**Screenshots**
<img width="960" alt="2020_07_28_15_21_00_" src="https://user-images.githubusercontent.com/44206545/88678279-3183d400-d0e6-11ea-9af6-fea83eef1f47.png">
<img width="617" alt="2020_07_28_15_11_03_Pesquisa_avançada_Arquivo pt" src="https://user-images.githubusercontent.com/44206545/88678314-39dc0f00-d0e6-11ea-9985-c572641af4e6.png">

**Comment by dcgomes** [comment]
MP4 is not a textual format (page search) neither image format (image search).
Address in the future when we develop video search.
