### ISSUE TITLE
Information about image with no labels

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1002]
**What is the URL that originated the issue?**
https://arquivo.pt/image/search?hitsPerPage=10&query=praia&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-07-28&dateStart=01%2F01%2F1996&dateEnd=28%2F07%2F2020#card

**What happened?**
Information about the image, when displayed as thumbnail, is there but is not so explicit

**What should have happened?**
Each information about the image should have a label: 
- Título, Image URL, Dimensions, Date of the capture; 
- Título, Page URL, Date of the capture

**Screenshots**
<img width="959" alt="2020_07_28_15_35_12_" src="https://user-images.githubusercontent.com/44206545/88683395-a574ab00-d0eb-11ea-8847-c82cc5cfc492.png">

**Comment by amourao** [comment]
@hmendes we should check the best way to make this information visible to the user 
This is part of the images2.js file, which adds the image results to the interface from the API call dynamically.

**Comment by hmendes** [comment]
> @hmendes we should check the best way to make this information visible to the user
> This is part of the images2.js file, which adds the image results to the interface from the API call dynamically.

A quick fix adding to CSS *element*:before { content="label"; } would work but I think we'll find a better solution through the markup/html to be SEO friendly.

**Comment by amourao** [comment]
### This is how it looks now:
![image](https://user-images.githubusercontent.com/2866295/108704985-9ed4d780-7504-11eb-9ace-929ac4e9173c.png)
![image](https://user-images.githubusercontent.com/2866295/108705044-b3b16b00-7504-11eb-9fe5-9d040e02dd1b.png)
