### ISSUE TITLE
Prepare and test SolrCloud configuration for page indexes

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1005]
**What happened?**
We need to check how to configure SolrCloud to support both the image and page search indexes.

Some examples of what we need to discuss and set:

- How many images to index per GB of memory in the server
- How many pages to index per GB of memory in the server
- How many replicas of each document to create

**Comment by VascoRatoFCCN** [comment]
Working on this. Does not need to be an issue.
