### ISSUE TITLE
Change the CSS to better fit the page "Suggestion" with the wordpress (sobre.arquivo.pt)

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1007]
**What is the URL that originated the issue?**
https://preprod.sobre.arquivo.pt/pt/colabore/sugerir/

**What should have happened?**

It is necessary to adapt the CSS of the new form of preprod.sobre.arquivo.pt (i.e., https://preprod.sobre.arquivo.pt/pt/colabore/sugerir/) to be more similar to what is on sobre.arquivo.pt (https://sobre.arquivo.pt/pt/colabore/sugerir/).

The goal is to try to remove all the elements that refer to "Google form" so that it looks like a normal page on sobre.arquivo.pt

**Screenshots**

***PREPROD***

![dsdsd](https://user-images.githubusercontent.com/25795364/88928568-e5b16600-d270-11ea-9770-f39ad1fa3553.JPG)

***SOBRE***

![safasfd](https://user-images.githubusercontent.com/25795364/88928612-eea23780-d270-11ea-9bad-5710c0953f6e.JPG)

**Comment by igobranco** [comment]
Isn't this enough https://support.google.com/docs/answer/145737?hl=en ?

**Comment by PedroG1515** [comment]
There is no white, only grey.

![saff](https://user-images.githubusercontent.com/25795364/88932427-f7493c80-d275-11ea-95ab-fab046151bed.JPG)

Second:

Wloud be nice removing the following text/elements:

"Nunca envie palavras-passe através dos Google Forms."
"Este conteúdo não foi criado nem aprovado pela Google. Denunciar abuso - Termos de Utilização - Política de privacidade"
"Google Formulários"

**Comment by dcgomes** [comment]
It is good enough
