### ISSUE TITLE
Insecure examples pages on sobre.arquivo.pt

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#1009]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/pt/exemplos/

**What happened?**
The browsers are starting to warn that the page isn't secure.
The image https://sobre.arquivo.pt/wp-content/uploads/diarioDigital.gif is being loaded using http instead of https and the browsers are starting to complain.

**What should have happened?**
All resources need to be downloaded using secure connections (https).

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/67018/89325755-2817e000-d681-11ea-914d-d04d6dc7ad75.png)

Chrome:
![image](https://user-images.githubusercontent.com/67018/89325816-3ebe3700-d681-11ea-89ff-c28e1e986358.png)

**Comment by dcgomes** [comment]
Fixed. 

Replaced all:
- http://arquivo.pt -> https://arquivo.pt
- http://sobre.arquivo.pt -> https://sobre.arquivo.pt

@igobranco please confirm.

**Comment by dcgomes** [comment]
I confirmed.
