### ISSUE TITLE
The page search result logging service is removing query string parameters from the Wayback redirect

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1011]
**What is the URL that originated the issue?**
https://arquivo.pt/page/view/98b000e13090571ad60c_cef26d80d5a120bca55c_2/20100102135137/http://blogs.sapo.pt/userinfo.bml?user=naocaso

**What happened?**
The logging service redirected the wayback request to 
https://arquivo.pt/wayback/20100102135137/http://blogs.sapo.pt/userinfo.bml
(notice that the query string parameters **?user=naocaso** are missing)

**What should have happened?**
The logging service should redirect the wayback request to 
https://arquivo.pt/wayback/20100102135137/http://blogs.sapo.pt/userinfo.bml?user=naocaso

This example should also be added as a test to check for regressions.

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/89663650-c39d9080-d8cd-11ea-9534-c51882c04f6a.png)
![image](https://user-images.githubusercontent.com/2866295/89663713-e29c2280-d8cd-11ea-8f1a-2ba9d1e0bc24.png)

**Comment by igobranco** [comment]
Fixed, this is a very important fix.

**Comment by VascoRatoFCCN** [comment]
https://github.com/arquivo/arquivo-webapp-eros/commit/882cf1cf35f62b4089e55f361f45a0331a90e876 fixes this issue
