### ISSUE TITLE
Link in page search SERP cards is linking directly to /wayback, instead of /page/view/

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1012]
**What is the URL that originated the issue?**
https://arquivo.pt/page/search?hitsPerPage=10&query=bicho&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-08-07&dateStart=01%2F01%2F1996&dateEnd=07%2F08%2F2020

or any other page SERP

**What happened?**
Clicking on the link directly goes to the /page/view/
Clicking on the card goes to the /wayback/ direcltly

**What should have happened?**
Clicking on the link should also go to the /page/view/

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/89665044-f5175b80-d8cf-11ea-88ff-485578951ea3.png)
Clicking outside the area in red redirects to the wrong service (/wayback) instead of the correct /page/view/

**Comment by igobranco** [comment]
Fixed
