### ISSUE TITLE
Add SVG support

### ISSUE THREAD

**Issue by hmendes** [arquivo/pwa-technologies#1018]
[This plugin must be installed](https://wordpress.org/plugins/svg-support/) for adding SVG support in Wordpress.

**Comment by ricardobasiliopt** [comment]
Upload didn't work: "O pós-processamento da imagem falhou provavelmente porque o servidor está ocupado o não tem recursos suficientes. Poderá ajudar carregar uma imagem mais pequena. O tamanho máximo sugerido é de 250 píxeis."

**Comment by pcabritafccn** [comment]
I had a look into the plugins, installed three plugins and tested them and all are returning the same error when trying to upload SVG files.

![image](https://user-images.githubusercontent.com/51712013/121908522-0073b880-cd25-11eb-917d-ca6b0a23bf20.png)

I will continue further investigation to check what is causing this issue.

**Comment by pcabritafccn** [comment]
This issue was opened as we wanted at some stage to upload SVG image files in order to provide a better resolution of imagery. Because of security reasons related with Wordpress, there was decided only to upload .jpg, .gif and .png image files. For that reason we are closing this issue #1018.
