### ISSUE TITLE
Add regression/integration tests to page search full text API

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#1019]
We need regression tests that verify if each API parameter is working correctly.

**Comment by dcgomes** [comment]
Document on https://docs.google.com/spreadsheets/d/14bKaTeo64G2bgDYyXxB6jvocttQZ4s9svJuHhPGKl74/edit#gid=1250096550

**Comment by VascoRatoFCCN** [comment]
All API tests have been documented on a new sheet called API (on the same google sheet document)
