### ISSUE TITLE
Page is blinking and doesn't replay

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1032]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20200714190313/https://www.portugal.gov.pt/pt/gc22

**What happened?**
Page is blinking

**What should have happened?**
Should replay normally

**Comment by PedroG1515** [comment]
issue #726
https://github.com/arquivo/pwa-technologies/issues/726
