### ISSUE TITLE
Develop a new homepage interface structure: HTML+CSS.

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#1040]
**What is the URL that originated the issue?**

Arquivo.pt have an old HTML and CSS structure.

**What happened?**

This is an old structure which is not contributing to the implementation and spreading of this service as it should.

**What should have happened?**

We should design/develop a new structure to work as a strong foundation, allowing us to optimise/update content easily and to engage with the user in a better way. Accessibility is also a key point that we will take into account in order to create great user experiences to everyone that visit our website. 

This new structure will allow Arquivo.pt, to play a key role as an important and great research tool, not only for academic students but for the public in general, leveraging and positioning Arquivo.pt even more, recognising it as a world web archive reference.
 
**Screenshots**

**Comment by dcgomes** [comment]
@pcabritafccn split this Issue in 7 separated Issues. One per each main UI:

- Home Page
- Page Search
- Page Advanced Search
- Image Search
- Advanced Search Images
- URL search
- Replay
See links in:
http://wiki.priv.fccn.pt/Objectivos_Arquivo.pt_2020#Contribui.C3.A7.C3.A3o_de_Arquivo.pt_para_objetivo_ASA

**Comment by pcabritafccn** [comment]
This is done.

**Comment by dcgomes** [comment]
Not in production

**Comment by dcgomes** [comment]
Broken link in footer "Open-source and API"
http://p54.arquivo.pt/?l=en 
Link should target: https://github.com/arquivo/pwa-technologies/wiki

**Comment by dcgomes** [comment]
Looks OK with preliminary testing. Proceed with integration and then create initial regression tests.

**Comment by dcgomes** [comment]
New Home page UI developed
