### ISSUE TITLE
Generate new Google Analytic codes for the different environments

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1041]
**What is the URL that originated the issue?**
https://analytics.google.com/analytics/web/?authuser=2#/report/content-event-overview/a21825027w43114507p43102353/_u.dateOption=last30days&overview-dimensionSummary.selectedGroup=visitors&overview-dimensionSummary.selectedDimension=analytics.eventCategory/

**What happened?**
Events for all environments (dev, preprod and prod) are going to the same event count

**What should have happened?**
Different environments should have their own Google Analytics code, to enable us to filter by environment and better test the events in dev and preprod.

**Screenshots**

**Comment by igobranco** [comment]
I suggest to replace the default one with a new tracking code. And on prod deployment replace (configure) it with a new one.

**Comment by vitgou** [comment]
A tracking code is available for development and part of the deploy process.
