### ISSUE TITLE
Check and revise the Google Analytics event codes

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1042]
**What is the URL that originated the issue?**
User facing URLs that generate events (page search, image search, wayback, ....)

**What happened?**
Some of the GA codes and label meanings are not clear.
The SERP results positions in https://analytics.google.com/analytics/web/?authuser=2#/report/content-event-overview/a21825027w43114507p43102353/_u.dateOption=last30days&overview-dimensionSummary.selectedGroup=visitors&overview-dimensionSummary.selectedDimension=analytics.eventCategory/ do not match the expected values.

**What should have happened?**
Events should have clear labels, and label meanings should be documented.

**Screenshots**

**Comment by dcgomes** [comment]
Install basic GAnalytics 4 without events for milestone Godhelpus.

**Comment by VascoRatoFCCN** [comment]
Won't fix, we're abandoning GA
