### ISSUE TITLE
Missing apache packages and certificates when deploying arquivo-webapp to "clean" server

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1043]
**What is the URL that originated the issue?**
After deploying webapp to dev machine (p51), apache does not start.

**What happened?**
Apache complains about missing SSL; after installing the missing package (mod_ssl), it complains about the missing certificate files

**What should have happened?**
These steps (install package and copy certs) should be added to the Ansible deploy config.

**Screenshots**

**Comment by igobranco** [comment]
The ansible has support to deploy the HTTPd of Arquivo.pt using SSL / HTTPS, but each environment needs to be configured correctly.
Any dev environment machine is configured to have the SSL on Apache HTTPd, because it would require emit a valid certificate for each dev virtual host.

**Comment by vitgou** [comment]
Development environments work without SSL. Currently, p51.arquivo.pt is working as a development broker.
