### ISSUE TITLE
Page information is not present on mobile

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1044]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/19961013145650/http://www.fccn.pt/

**What happened?**
Page description/Page information is not present on mobile. For instance, "fccn.pt 13 Outubro às 14:56, 1996"

**Screenshots Mobile**
![1](https://user-images.githubusercontent.com/25795364/98359819-b0ab7100-2020-11eb-830c-46394e0fa80e.JPG)

**Screenshots Desktop**
![2](https://user-images.githubusercontent.com/25795364/98359928-da649800-2020-11eb-8a57-7c70a40899dc.JPG)

**Comment by pcabritafccn** [comment]
This issue does not apply to the new HTML code. Going to close it.
