### ISSUE TITLE
Review tomcat broker logging behavior

### ISSUE THREAD

**Issue by ghost** [arquivo/pwa-technologies#105]
Originally reported on Google Code with ID 106

```
Essential information about the broker activity is not being logged to catalina.date.log
files that are schedule to backup.

The missing information on logs are search requests to brokers, that are being logged
in catalina.out (all stdout and stderr), generating some confusion about logging information.

The logging needs a review, and the catalina.out should be daily rotated to be more
suitable to backup.
```

Reported by `daniel.bicho` on 2015-03-10 10:07:23

**Comment by danielbicho** [comment]
Update Nutchwax webapp to log to its own log file:

log4j.rootLogger=DEBUG, R
log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=${catalina.home}/logs/nutchwaxwebapp.log
log4j.appender.R.MaxFileSize=100MB
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{ISO8601} %-5p %c{1} - %m%n
log4j.threshhold=DEBUG 

Change the threshhold at production
