### ISSUE TITLE
change title on Arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1060]
**What is the URL that originated the issue?**
https://arquivo.pt/

<Title> of the home page should be our official slogan: 
- PT: "Arquivo.pt: pesquise páginas do passado!"

**Comment by pcabritafccn** [comment]
Issues #1060 is now solved and closed.

**Comment by dcgomes** [comment]
Change title in English version to:
"Arquivo.pt - search pages from the past!"

**Comment by pcabritafccn** [comment]
Issue #1060 is solved and closed.
