### ISSUE TITLE
Revise how to process quoted queries in page and image search

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1062]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/advanced/search?hitsPerPage=10&query=portugal+"""moção de censura

**What happened?**
When creating a query with quotes, if there is an opening quote without a closing quote, everything after the opening quote will be treated as the phrase query when searching the APIs

This process is a part of the [simple-params-processing.jsp](https://github.com/arquivo/arquivo-webapp/blob/master/src/main/webapp/include/simple-params-processing.jsp) class and also happens for all other search interfaces (regular, advanced and images) "invisibly" 

Related to arquivo/pwa-technologies#1034

In addition, multiple consecutive quotes are ignored/treated as one.

**What should have happened?**
Research how other search engines deal with this situation  
Discuss if we should ignore single quotes or keep behaviour as is

**Comment by dcgomes** [comment]
Won't fix.
We assume that the users inserted the open quotes (it was not a typo) but forgot to insert the ending quotes.
