### ISSUE TITLE
Revise Image Search API log format

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1065]
**What is the URL that originated the issue?**
All image search API requests

**What happened?**
Some important information is not being logged or it is being logged in the wrong format

**What should have happened?**
Revise the format to facilitate parsing

**Screenshots**

**Comment by PedroG1515** [comment]
Log Formart:

**IP_Address**  \t  **User_Agent**  \t  **Request**  \t  **Duration**  \t  **Search_Parameters**  \t  **Search_Results**.

- **IP_Address** is a unique address that identifies a device on the internet or a local network.
- **User_Agent** is any software that retrieves and presents Web content for end-users.
- **Request** is the request made to Image Search API.
- **Duration** is the response time of the request.
- **Search_Parameters** are the parameters used in the request.
- **Search_Results** are the results that were returned to the user.

**Example**

1.1.1.1	Mozilla/5.0	http://arquivo.pt/imagesearch?q=example	160ms	search_parameters:{"q":["example"]]}	search_results:["1784b0bc37551b4f52fbf3f738e11e8c8903742192f379706f1a3b4f9761d7e3","699cf552fcf76b3d5021018a3dae46bdd4fc4fed7a143d57d4a3e58acd5c842d", ...]
