### ISSUE TITLE
Revise Page Search API log format

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1066]
**What is the URL that originated the issue?**
All page search API requests

**What happened?**
Some important information is not being logged or it is being logged in the wrong format

**What should have happened?**
Revise the format to facilitate parsing

**Screenshots**

**Comment by PedroG1515** [comment]
Log Formart:

**IP_Address**  \t  **User_Agent**  \t  **Request**  \t  **Duration**  \t  **Search_Parameters**  \t  **Search_Results**.

- **IP_Address** is a unique address that identifies a device on the internet or a local network.
- **User_Agent** is any software that retrieves and presents Web content for end-users.
- **Request** is the request made to Page Search API.
- **Duration** is the response time of the request.
- **Search_Parameters** are the parameters used in the request.
- **Search_Results** are the results that were returned to the user.
