### ISSUE TITLE
White Page when user clicks on the browser back button (Image Search)

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1068]
**What is the URL that originated the issue?**
https://arquivo.pt/image/search?hitsPerPage=10&query=amadora&l=pt&ion-dt-1=1996-01-01&ion-dt-0=2021-01-29&dateStart=01%2F01%2F1996&dateEnd=29%2F01%2F2021

**What happened?**
1. https://arquivo.pt/image/search?hitsPerPage=10&query=amadora&l=pt&ion-dt-1=1996-01-01&ion-dt-0=2021-01-29&dateStart=01%2F01%2F1996&dateEnd=29%2F01%2F2021
2. Click on the first image.
3. Click on the browser back button.

**What should have happened?**
It should appear the page:
https://arquivo.pt/image/search?hitsPerPage=10&query=amadora&l=pt&ion-dt-1=1996-01-01&ion-dt-0=2021-01-29&dateStart=01%2F01%2F1996&dateEnd=29%2F01%2F2021

**Screenshot**
![1](https://user-images.githubusercontent.com/25795364/106262190-90074780-621a-11eb-815e-ee0ad0257b62.JPG)

**Comment by amourao** [comment]
This problem will be resolved in the new version of the web UI.
