### ISSUE TITLE
Deploys 2019 collections

### ISSUE THREAD

**Issue by vitgou** [arquivo/pwa-technologies#1070]
Before the Dionisius milestone we need to have all 2019 collections. This issue just collects the task.

**DoD**

All 2019 collections are available in Arquivo.pt

**Comment by amourao** [comment]
Image collections are fully deployed

**Comment by vitgou** [comment]
All 2019 collections are available in Arquivo.pt. https://sobre.arquivo.pt/en/2019-websites-available-and-arquivo-pt-surpasses-10-billion-files/
