### ISSUE TITLE
White images with transparent background show up as white rectangles in image search results

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1077]
**What is the URL that originated the issue?**
http://p51.arquivo.pt/image/search?query=fccn&dateStart=01/01/1996&dateEnd=01/03/2021&pag=prev&start=72&l=pt#

**What happened?**
White images with transparent background show up as white rectangles in image search results.

**What should have happened?**
Not sure what is the best way to make this images "pop" in the Search results.
In the screenshots below, I show what happens if you add a gray background, but I don't think this is a good solution.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/2866295/109524361-568b5b80-7aa8-11eb-9605-7d0ee142d182.png)

Changed the card background to gray to show what the image looks like:
![image](https://user-images.githubusercontent.com/2866295/109524450-728efd00-7aa8-11eb-8897-173fc4aaa3b3.png)

**Comment by pcabritafccn** [comment]
Issue #1077; this will be solved on the Eros version.
