### ISSUE TITLE
Image that generate 404/500 errors should be hidden from the results

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1088]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/image/search?hitsPerPage=10&query=fccn&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2021-03-11&dateStart=01%2F01%2F1996&dateEnd=11%2F03%2F2021#

**What happened?**
Missing images appear with the broken icon card

**What should have happened?**
Error results should be hidden from the end user

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/110832131-df697a80-8292-11eb-9e58-fd8ebde9f18f.png)

**Comment by VascoRatoFCCN** [comment]
Needs to be implemented in new interface.

Example of search with broken images:
https://preprod.arquivo.pt/image/search?hitsPerPage=10&query=dali&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2021-03-11&dateStart=01%2F01%2F1996&dateEnd=11%2F03%2F2021

**Comment by arquivo-awp** [comment]
Cannot reproduce error from provided examples.
