### ISSUE TITLE
Exclude ".open" WARCs from Image and Page Indexing

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1095]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20191127031533im_/https://osbichos.news/wp-content/uploads/2018/12/Blat-435x290.jpg

**What happened?**
Pywb was unable to replay the image, since it was not possible to generate cdxj. Although the file looks like a well-formed WARC (i.e., ".warc.gz") within the file the WARC is a "warc.open".  The WARCs with an extension ".open" is created when the crawler was stopped abruptly.  

Collection: RAQ2019
WARC: raq-osbichos-20191127024404758-00081-6f2po793.warc.gz
Offset: 29475666

**What should have happened?**
This WARCs should not be considered when indexing Images and Pages.

**Comment by amourao** [comment]
@PedroG1515 
Not sure if it is worth working on this as malformed warcs will fail processing anyway.
How often does this problem occur? The indexer does not process "warc.open" files, only "arc.gz" and "warc.gz" How easy is it detect "warc.open" files if there is no open in the filename? Do all "warc.open" files fail CDX indexing?

**Comment by PedroG1515** [comment]
Closed.
#1124
