### ISSUE TITLE
Maintain consistency in home page design

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1099]
**What is the URL that originated the issue?**
http://p54.arquivo.pt/

**What happened?**
When comparing the design of home page with previous design the following graphical inconsistencies were found (see screenshot below):

**What should have happened?**

![image](https://user-images.githubusercontent.com/13120352/112145059-cdac9f00-8bd1-11eb-8083-adbfc531d8b4.png)
On the left side is the Dionisius version (new), on the right the Caronte version (in production)
- Cursor should be on search box.
- There should be a shadow on search box to emphasize it.
- Datepickers icons should be larger, they are what distinguish Arquivo.pt from other search engine, and to provide space to the dates values inside the calendar icons to improve readability.
- The vertical space between buttons "Pages", "Images" and "Advanced search" and the first card "Arquivo.pt Award" should be larger to separate the search transactional block from the cards informational block.
- Personal note: the rounder edges on the previous versions look more elegant than the sharper ones on the new version. Why were they changed?
- Datepickers must NOT have a close button cross because when SOME users click on "close" they interpret that the input values must be set, while SOME other users interpret that their input must be canceled. In the current situation, the close button has the same redundant behavior as the OK button which is confusing to the users. 
![image](https://user-images.githubusercontent.com/13120352/112166715-c85a4f00-8be7-11eb-99b9-c6332c6abd19.png)

- The full names of months must be displayed on the datepickers, there is no space need to abbreviate them and add the cognitive burden of expanding them to the users.

**Comment by pcabritafccn** [comment]
Olá Daniel,

Podes verificar se o datepicker já está melhor. Faz refresh no browser
antes de verificares:

Estou a trabalhar no restante do issue #1099 e assim que estiver pronto
aviso-te para certificares se está tudo bem para poder fechá-lo.

Obrigado.

Um abraço,
Paulo

**Comment by pcabritafccn** [comment]
This is now solved.
