### ISSUE TITLE
Lack of documentation in the API about the parameter linkToOriginalFile

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1100]
https://github.com/arquivo/pwa-technologies/wiki/Arquivo.pt-API

The parameter "linkToOriginalPage" is on the technical details at Arquivo.pt, but is not yet documented on GitHub

Add a row the table about API parameters, add a description and put new examples about responses

<img width="694" alt="print" src="https://user-images.githubusercontent.com/44206545/112171794-14a78e00-8bec-11eb-8947-90113164555b.png">

<img width="956" alt="2021_03_23_14_57_47_linktooriginalfile" src="https://user-images.githubusercontent.com/44206545/112172079-4e789480-8bec-11eb-9daf-26bf90fce927.png">

**Comment by amourao** [comment]
Added "linkToOriginalPage" description
