### ISSUE TITLE
Submit query button only works if you click the "Pesquisar" text

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1101]
**What is the URL that originated the issue?**
Pages with the search header
https://arquivo.pt/image/search
https://arquivo.pt/page/search
https://arquivo.pt/

**What happened?**
When you click the search button, it only works if you click the "Pesquisar" text, clicking the remainder of the button does not do anything 

**What should have happened?**
The full button should be clickable

**Screenshots**
![Screenshot from 2021-03-24 15-11-01](https://user-images.githubusercontent.com/2866295/112334998-c3fb6800-8cb3-11eb-95ea-4920f20f4ec3.png)
Only the area between the blue dashed lines are clickable, not the full button

**Comment by pcabritafccn** [comment]
This issue is now solved and it needs to be tested at preprod.arquivo.pt before it goes live.
