### ISSUE TITLE
Search layout breaks on mobile for some keywords

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1103]
**What is the URL that originated the issue?**
sobre.arquivo.pt
Search for: "Manique"

**What happened?**
The layout brook on a mobile device (Hawei P10 lite, Chrome):
![image](https://user-images.githubusercontent.com/13120352/112863687-04415880-90af-11eb-8904-779a908b00b8.png)

This problem does not happens for other queries. I could not identify a pattern to replicate the bug.

**Comment by pcabritafccn** [comment]
Issue #1103 is now solved.
![image](https://user-images.githubusercontent.com/51712013/130051443-2360f981-8b1f-4ba3-885e-be9d64e6b980.png)
