### ISSUE TITLE
Replace old icon 

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1104]
If we share a page/post from sobre.arquivo.pt the old logo of Arquivo.pt is presented. See how WhatsApp displays the old logo:
![image](https://user-images.githubusercontent.com/13120352/114009763-57f43480-985b-11eb-82bd-a9edb23d7208.png)

We cannot control which image each app chooses to display, but the old logo should not be available anywhere in our site. Find where it is and replaced it with a new version of the icon based on our current logo:
https://sobre.arquivo.pt/wp-content/uploads/logo_pack_2.0.zip

**Comment by pcabritafccn** [comment]
Issue #1104 is now solved.
