### ISSUE TITLE
Change earliest date in the date filter

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1105]
**What is the URL that originated the issue?**
http://arquivo.pt

**What happened?**
Filter stops at 1996 but we have content starting at (at least) 1992

\\paris\ASA\AWP\colaborações\OldDominion 
[http://p44.arquivo.pt:8983/solr/images/select?q=*%3A*&sort=imgCrawlTimestamp%20asc](http://p91.arquivo.pt:8983/solr/images/select?q=*%3A*&sort=imgCrawlTimestamp%20asc)

**What should have happened?**
Change the date of the filter to go to 1991/1992

**Comment by VascoRatoFCCN** [comment]
First web page: August 6, 1991

**Comment by VascoRatoFCCN** [comment]
Minimum date changed to August 6, 1991 (on dev.arquivo.pt)
