### ISSUE TITLE
Create "Advanced Image search" about page

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1107]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/pt/ajuda/pesquisa-avancada-de-imagens/
https://sobre.arquivo.pt/en/help/advanced-image-search/

**What happened?**
They don't exist

**What should have happened?**
They should exist.
Start from the corresponding advanced search page after it is corrected #1106 
https://sobre.arquivo.pt/pt/ajuda/pesquisa-avancada/
https://sobre.arquivo.pt/en/advanced-search/

**Screenshots**

**Comment by dcgomes** [comment]
Something breaks on the Advanced search UI with this example link: https://arquivo.pt/image/advanced/search?l=pt&query=gato+type:gif
![image](https://user-images.githubusercontent.com/13120352/120462590-fc45b380-c392-11eb-9034-5490cf5b7fda.png)


![image](https://user-images.githubusercontent.com/13120352/120462175-93f6d200-c392-11eb-8c15-c7d1db0bf00d.png)

**Comment by dcgomes** [comment]
I edited considering the label changes proposed in https://github.com/arquivo/pwa-technologies/issues/1102

**Comment by dcgomes** [comment]
Finished editing. Please double check @amourao.

**Comment by amourao** [comment]
> Something breaks on the Advanced search UI with this example link: https://arquivo.pt/image/advanced/search?l=pt&query=gato+type:gif
> ![image](https://user-images.githubusercontent.com/13120352/120462590-fc45b380-c392-11eb-9034-5490cf5b7fda.png)
> 
> ![image](https://user-images.githubusercontent.com/13120352/120462175-93f6d200-c392-11eb-8c15-c7d1db0bf00d.png)
 
Not sure of what is happening with the UI, but it should be fixed in the new version.

> Related to #1111
> Are multiple formats supported through the operator? How?

This was not supported but a fix was already created and should be deployed in the next release.

**Comment by amourao** [comment]
Revised
