### ISSUE TITLE
API parameters name differences between query string and get parameter

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1108]
**What is the URL that originated the issue?**
Query from advanced search:

https://arquivo.pt/page/search?l=pt&adv_and=fccn&adv_phr=&adv_not=&ion-dt-0=1996-01-01&ion-dt-1=2021-04-15&dateStart=01%2F01%2F1996&dateEnd=15%2F04%2F2021&format=pdf&site=fccn.pt&hitsPerPage=10&btnSubmitBottom=Pesquisar+no+Arquivo

**What happened?**
Image search: Site filter is called `siteSearch` when it is a GET parameter but it is called `site` when it is in the query string.
There are more inconsistencies to document.

Another interesing behavior to examine is that the next page link changes parametrization to query string parameters:
https://arquivo.pt/page/search?query=fccn+site%3Afccn.pt+type%3Apdf&dateStart=01/01/1996&dateEnd=15/04/2021&pag=next&start=10&hitsPerPage=10&hitsPerDup=0&dedupField=site&l=pt

This applies both to image and page search

**What should have happened?**
Make the names consistent.
Check how this affects with WebUI behavior.

**Screenshots**

**Comment by VascoRatoFCCN** [comment]
Newest release will have the same fields between the front end and the API:

- `dateStart` and `ion-dt-0` parameters are now `from` in the format YYYYMMDD
- `dateEnd` and `ion-dt-1` parameters are now `to` in the format YYYYMMDD
- `query` parameter is now `q`
- `start` parameter is now `offset`
- `format` and `adv_mime` are now `type`
- `hitsPerPage` is now `maxItems`
- `site` is now `siteSearch`
- `hitsPerDup` is now `dedupValue` 

If a query is made using the old parameter names, the names will be automatically converted to the new homogeneous nomenclature.
