### ISSUE TITLE
Problems indexing AWP16

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#111]
Originally reported on Google Code with ID 112
```
What steps will reproduce the problem?
1. Executing the index-collection.sh with AWP16 collection.
2. The p64 is the DocServer that provides the arcfiles.
3. When the Reduce is almost finished and Map finished import phase throws and expection:
java.lang.OutOfMemoryError: GC overhead limit exceeded.

What is the expected output? What do you see instead?

Hadoop job_201503090845_0004 failures on p43


Please use labels and text to provide additional information.
```

Reported by `HugoHAViana` on 2015-03-23 14:00:09

**Comment by FCCNhviana** [comment]
Added two more nodes to clusters.

**Comment by FCCNhviana** [comment]
Increase mapredu heap memory.
<property>
    <name>mapred.child.java.opts</name>
    <value>-Xmx12000m</value>
  </property>

**Comment by FCCNhviana** [comment]
Collection was divided in two taking in consideration the biggest lengths that was indexed up till now.

**Comment by FCCNhviana** [comment]
mapred.child.java.opts
-Xmx20000m

 <property>
     <name>mapred.reduce.child.java.opts</name>
     <value>-Xmx20000m</value>
   </property>

**Comment by dcgomes** [comment]
@FCCNhviana Fixed?

Please described the applied fix and close the issue.

**Comment by FCCNhviana** [comment]
<property>
     <name>mapred.child.java.opts</name>
     <value>-Xmx26000m</value>
 </property>

Provide more memory to handle with the Reduce phase. The bellow is the changed code on hadoop-site.xml
<property>
     <name>mapred.child.java.opts</name>
     <value>-Xmx26000m</value>
 </property>

Changed the fetched documentserver machine, because occured problems when indexing, due to hardware problems. The problem was because of the disk i/o, already solved.
