### ISSUE TITLE
Page Advanced Search should support multiple format search

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1111]
**What is the URL that originated the issue?**
https://arquivo.pt/page/advanced/search

**What happened?**
On the "Format:" field only one format can be chosen at a time, even though the system supports searches with more than one file type.

**What should have happened?**
The interface should allow for multiple options to be selected using checkboxes.

**Screenshots**
![image](https://user-images.githubusercontent.com/79858044/115423633-e5d60500-a1f5-11eb-9890-b2203f33f531.png)

**Comment by amourao** [comment]
So, the behavior was fixed in the API: you can query multiple formats by separating it using a comma `format:jpg,png`
