### ISSUE TITLE
Problems collecting the response from POST URLs

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1112]
**What is the URL that originated the issue?**
https://www.boaspraticasautarquicas.gov.pt/boas-praticas/?category=sustentabilidade

**What happened?**

Trying to collect the URL --> https://www.boaspraticasautarquicas.gov.pt/boas-praticas/?category=sustentabilidade. Although there is no problem with the collection of information, the Pywb can not replay the previous URL due to the fact that the URL (https://www.boaspraticasautarquicas.gov.pt/wp-admin/admin-ajax.php), since the URL is a POST.

Example Arquivo.pt;

https://preprod.arquivo.pt/wayback/20210420115543/https://www.boaspraticasautarquicas.gov.pt/boas-praticas/?category=sustentabilidade

Example InternetArchive:

https://web.archive.org/web/20210422132837/https://www.boaspraticasautarquicas.gov.pt/boas-praticas/?category=sustentabilidade

(The URL was save with **Save Page Now** from Internet Archive --> https://web.archive.org/save/. Will the same happen with normal collections?)

**What should have happened?**
We should do the same as InternetArchive (i.e., save de response from admin-ajax.php):

https://web.archive.org/web/20210422132843/https://www.boaspraticasautarquicas.gov.pt/wp-admin/admin-ajax.php

![image](https://user-images.githubusercontent.com/25795364/115842964-417ed900-a416-11eb-8f95-92edd5b545b7.png)

**Screenshots**
Problem with our pywb when we are getting the URL ( https://www.boaspraticasautarquicas.gov.pt/boas-praticas/?category=sustentabilidade) : 
![image](https://user-images.githubusercontent.com/25795364/115741348-91628f00-a387-11eb-8d64-9919ca4445f6.png)

**Comment by PedroG1515** [comment]
The POST response is stored in the WARC.
![image](https://user-images.githubusercontent.com/25795364/117117077-04f09d00-ad87-11eb-9051-19252da08573.png)

**Comment by amourao** [comment]
So, there are two problems here:
- For the records,  the "__wb_method=post" pywb parameter is being added twice to the url (during crawling and in cdxj_indexer), resulting in records with SURTs with "__wb_method=post" twice ("__wb_method=post&__wb_method=post"). As the SURT has an extra parameter in the URL "__wb_method=post", replaying the page will result in a 404 error. This can be "fixed" by doing a check in the  (https://github.com/webrecorder/cdxj-indexer/blob/a494039d6c0c32eaffb7e5e7d1231a70c9792dd5/cdxj_indexer/postquery.py#L28)
- For the records, that are indexed without parameters, using only admin-ajax.php + timestamp for replay, pywb is returning error 503. More research in this case is needed.

**Comment by PedroG1515** [comment]
Issue solved:
--> New version cdx-indexer (pywb 2.5)
