### ISSUE TITLE
Screenshot service is not working for some pages

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1113]
**What is the URL that originated the issue?**
https://arquivo.pt/screenshot/?url=https%3A%2F%2Farquivo.pt%2FnoFrame%2Freplay%2F20180101180229%2Fhttps%3A%2F%2Fwww.dn.pt%2F&width=1440&height=810

**What happened?**
"500 Internal Error"

**What should have happened?**
Screenshot should be returned
Trying to print that same page using our print button is also not working.

**Comment by PedroG1515** [comment]
May be related to a timeout.
It works:
https://arquivo.pt/wayback/20190324061038/https://developer.microsoft.com/en-us/windows

**Comment by amourao** [comment]
It looks like the screenshot service has a timeout of 30 seconds (probably set in puppeteer).

https://arquivo.pt/screenshot/?url=https%3A%2F%2Farquivo.pt%2FnoFrame%2Freplay%2F20190324180546%2Fhttps%3A%2F%2Fwww.publico.pt%2F&width=1680&height=1050
.https://arquivo.pt/screenshot/?url=https%3A%2F%2Farquivo.pt%2FnoFrame%2Freplay%2F20190324180509%2Fhttps%3A%2F%2Fwww.dn.pt%2F&width=1680&height=1050

These two complex examples take a while to load the full DOM
The screenshot service returns an Internal Server Error for both after ~30.5 seconds, which is consistent with a timeout of 30 seconds.

We should consider increasing this timeout.
