### ISSUE TITLE
Page search filtered by site is not showing enough results

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1115]
**What is the URL that originated the issue?**
https://arquivo.pt/page/search?hitsPerPage=10&query=carnaval+site%3Awww.dn.pt

**What happened?**
Only 2 results show up, instead of the expected 10 results.
The next page buttons show up but no results are displayed.

**What should have happened?**
More results for page should show up.

The problem is that the default query is that the `maxItems` parameters is applied before site-based deduplication. Thus, increasing the `maxItems` to, for example, 100 will show up more results on the SERP.

https://arquivo.pt/textsearch?q=carnaval&from=19960101000000&to=20210430235959&offset=0&maxItems=100&siteSearch=www.dn.pt%2C*.www.dn.pt

Related https://github.com/arquivo/pwa-technologies/issues/1109

**Comment by amourao** [comment]
This was discussed in a past meeting and should already be fixed in the new version of the WebUI.
@VascoRatoFCCN can you confirm this is fixed in the new version?

**Comment by VascoRatoFCCN** [comment]
This is fixed in the most recent version, page size is increased to account for deduplicated items.
