### ISSUE TITLE
Replace footer on www.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1116]
Some of the current footer links are broken. Ideally, the same footer code should by shared between www.arquivo.pt and sobre.arquivo.pt

Replace footer on www.arquivo.pt with this new one:

= PT
== Sobre
O que é o Arquivo.pt? -> https://sobre.arquivo.pt/pt/ajuda/o-que-e-o-arquivo-pt/
Publicações -> https://arquivo.pt/publica
Exposições -> https://arquivo.pt/expos
Área de imprensa -> https://arquivo.pt/imprensa
API & Código-aberto -> https://arquivo.pt/api
Termos e Condições -> https://sobre.arquivo.pt/pt/acerca/termos-e-condicoes/
 
== Notícias
Subscrever lista de email -> https://arquivo.pt/inscrever
Últimas novidades -> https://arquivo.pt/noticias  
Twitter -> https://twitter.com/ArquivoWeb_PT
Facebook -> https://www.facebook.com/Arquivo.pt
Vídeos -> https://arquivo.pt/videos
Material de Divulgação -> https://sobre.arquivo.pt/pt/imprensa/material-de-divulgacao/

== Colabore
Prémios Arquivo.pt -> https://arquivo.pt/premios
Sugira site -> https://arquivo.pt/sugerir
Memorial -> https://arquivo.pt/memorial
Recomendações -> https://arquivo.pt/recomenda
Forneça conteúdos históricos -> https://arquivo.pt/doar
Investigação -> https://arquivo.pt/investiga 
 
== Ajuda
Pesquisa de páginas -> https://sobre.arquivo.pt/pt/ajuda/pesquisa/
Pesquisa de imagens -> https://sobre.arquivo.pt/pt/ajuda/ajuda-acerca-da-pesquisa-de-imagens/
Recolha -> https://sobre.arquivo.pt/pt/ajuda/recolha-e-arquivo-de-conteudos/
Acesso -> https://sobre.arquivo.pt/pt/ajuda/acesso-a-conteudos-arquivados/
Formação -> https://arquivo.pt/forma
Contacto -> https://sobre.arquivo.pt/pt/contacto/

= EN

== About
What is Arquivo.pt? -> https://sobre.arquivo.pt/en/help/what-is-arquivo-pt/
Publications -> https://arquivo.pt/publications
Exhibitions -> https://arquivo.pt/exhibitions
Press -> https://arquivo.pt/press
API & Open-source -> https://arquivo.pt/api
Terms and Conditions -> https://sobre.arquivo.pt/en/about/terms-and-conditions/
 
== News
Subscribe mailing list -> https://arquivo.pt/subscribe
Latest news -> https://arquivo.pt/news  
Twitter -> https://twitter.com/PT_WebArchive
Facebook -> https://www.facebook.com/PortugueseWebArchive/
Videos -> https://arquivo.pt/videos
Dissemination material -> https://sobre.arquivo.pt/en/about/press/dissemination-materials/
 
== Collaborate
Arquivo.pt Awards -> https://arquivo.pt/awards
Suggest a site  -> https://arquivo.pt/suggest
Memorial -> https://sobre.arquivo.pt/en/collaborate/web-memorial/
Recommendations -> https://arquivo.pt/recommendations
Donate historical web content -> https://arquivo.pt/donate
Research & Development -> https://arquivo.pt/research

== Help
Page search -> https://sobre.arquivo.pt/en/help/search-2/
Image search -> https://sobre.arquivo.pt/en/help/help-about-image-search/
Crawling -> https://arquivo.pt/faq-crawling
Access -> https://sobre.arquivo.pt/en/help/access-to-archived-contents/
Training courses -> https://arquivo.pt/training
Contact -> https://sobre.arquivo.pt/en/contact/

**Comment by VascoRatoFCCN** [comment]
"Memorial" link was missing in EN footer under "Collaborate". The following was implemented:
Memorial -> https://sobre.arquivo.pt/en/collaborate/web-memorial

The following URLs are not valid:
- EN -> About -> Exhibitions ->https://arquivo.pt/exhibitions  
Replaced with https://sobre.arquivo.pt/en/11557-2/collections/
- EN -> Collaborate ->Donate historical web content -> https://arquivo.pt/donate  
Replaced with https://sobre.arquivo.pt/en/collaborate/supplying-historical-portuguese-web-contents/

**Comment by VascoRatoFCCN** [comment]
Implemented footer.
PT - http://dev.arquivo.pt/
EN - http://dev.arquivo.pt/?l=en
