### ISSUE TITLE
Replace footer on Wordpress with new one

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1117]
Some of the current footer links are broken. Ideally, the same footer code should by shared between www.arquivo.pt and sobre.arquivo.pt

Replace footer on www.arquivo.pt with this new one:

= PT
== Sobre
O que é o Arquivo.pt? -> https://sobre.arquivo.pt/pt/ajuda/o-que-e-o-arquivo-pt/
Publicações -> https://arquivo.pt/publica
Exposições -> https://arquivo.pt/expos
Área de imprensa -> https://arquivo.pt/imprensa
API & Código-aberto -> https://arquivo.pt/api
Termos e Condições -> https://sobre.arquivo.pt/pt/acerca/termos-e-condicoes/
 
== Notícias
Subscrever lista de email -> https://groups.google.com/forum/#!forum/divulgarquivopt/join
Últimas novidades -> https://arquivo.pt/noticias  
Twitter -> https://twitter.com/ArquivoWeb_PT
Facebook -> https://www.facebook.com/Arquivo.pt
Vídeos -> https://arquivo.pt/videos
Material de Divulgação -> https://sobre.arquivo.pt/pt/imprensa/material-de-divulgacao/

== Colabore
Prémios Arquivo.pt -> https://arquivo.pt/premios
Sugira site -> https://arquivo.pt/sugerir
Memorial -> https://arquivo.pt/memorial
Recomendações para webmasters -> https://arquivo.pt/recomenda
Forneça conteúdos históricos -> https://arquivo.pt/doar
Investigação -> https://arquivo.pt/investiga 
 
== Ajuda
Pesquisa de páginas -> https://sobre.arquivo.pt/pt/ajuda/pesquisa/
Pesquisa de imagens -> https://sobre.arquivo.pt/pt/ajuda/ajuda-acerca-da-pesquisa-de-imagens/
Recolha -> https://sobre.arquivo.pt/pt/ajuda/recolha-e-arquivo-de-conteudos/
Acesso -> https://sobre.arquivo.pt/pt/ajuda/acesso-a-conteudos-arquivados/
Formação -> https://arquivo.pt/forma
Contacto -> https://sobre.arquivo.pt/pt/contacto/

= EN

== About
What is Arquivo.pt? -> https://sobre.arquivo.pt/en/help/what-is-arquivo-pt/
Publications -> https://arquivo.pt/publications
Exhibitions -> https://arquivo.pt/exhibitions
Press -> https://arquivo.pt/press
API & Open-source -> https://arquivo.pt/api
Terms and Conditions -> https://sobre.arquivo.pt/en/about/terms-and-conditions/
 
== News
Subscribe mailing list -> https://groups.google.com/forum/#!forum/divulgarquivopt/join
Latest news -> https://arquivo.pt/news  
Twitter -> https://twitter.com/PT_WebArchive
Facebook -> https://www.facebook.com/PortugueseWebArchive/
Videos -> https://arquivo.pt/videos
Dissemination material -> https://sobre.arquivo.pt/en/about/press/dissemination-materials/
 
== Collaborate
Arquivo.pt Awards -> https://arquivo.pt/awards
Suggest a site  -> https://arquivo.pt/suggest
Recommendations for publishers -> https://arquivo.pt/recommendations
Donate historical web content -> https://arquivo.pt/donate
Research & Development -> https://arquivo.pt/research

== Help
Page search -> https://sobre.arquivo.pt/en/help/search-2/
Image search -> https://sobre.arquivo.pt/en/help/help-about-image-search/
Crawling -> https://arquivo.pt/faq-crawling
Access -> https://sobre.arquivo.pt/en/help/access-to-archived-contents/
Training courses -> https://arquivo.pt/training
Contact -> https://sobre.arquivo.pt/en/contact/

**Comment by dcgomes** [comment]
Wait for #1117  to be closed to implement because some footer links are not working yet (Subscribe mailing list).

**Comment by pcabritafccn** [comment]
Wordpress footer is now replicated from dev.arquivo.pt. Still waiting for issue #1116 to be solved in order to close this.

**Comment by pcabritafccn** [comment]
Issue #1117 is now solved.

**Comment by dcgomes** [comment]
The footers on www.arquivo.pt and sobre.arquivo.pt are different after Eros deploy.
Replicate footer of www.arquivo.pt on sobre.arquivo.pt.

**Comment by dcgomes** [comment]
Fixed in milestone Francisco
