### ISSUE TITLE
"Subscribe to mailing list" link not working properly

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1118]
The URL for joining the mailing list simply redirects to the Google group page and does not display a "join" form. 

Additionally, Google groups seems to have disallowed users without a google account to request to join Google groups.

The URL should link to a page where any user can subscribe to the mailing list, regardless of whether they have a google account or not. 

Affected URLs:
https://arquivo.pt/inscrever
https://arquivo.pt/subscribe

**Comment by ricardobasiliopt** [comment]
The affected URLs are now pointing to two new Google Forms where any user can subscribe and then be added to the mailinglist. 
Issue arquivo/pwa-technologies#1118.
