### ISSUE TITLE
Problem replaying images

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1119]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20210510152601/https://www.publico.pt/

**Screenshots**

1. **Chrome**

![image](https://user-images.githubusercontent.com/25795364/117686797-1e428080-b1af-11eb-8182-100125c6da36.png)

2. **Firefox**

![image](https://user-images.githubusercontent.com/25795364/117687026-49c56b00-b1af-11eb-9726-6907aecb4448.png)

**Comment by VascoRatoFCCN** [comment]
Can no longer reproduce this issue, updates to pywb may have solved it.
