### ISSUE TITLE
Revise image search page on Sobre

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#1121]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/pt/ajuda/pesquisa-de-imagens/
 https://sobre.arquivo.pt/en/help/image-search/

**What happened?**

- Ex incorrecto: “6. Posso escolher o formato da imagem? Sim. Selecione “Ferramentas” e depois a a caixa de seleção “Formato””
- Incorrecto: Função inexistente
  - “14. Posso denunciar imagens com conteúdo impróprio? Sim. Porém a função “reportar problema” deve ser ativada nos casos de conteúdo impróprio quando a Pesquisa Segura estiver configurada para “Excluir imagens impróprias””
- Mover para Pesquisa Avançada de Imagens: “10. Posso escolher a fonte das imagens que eu queira pesquisar? Sim. Na pesquisa de imagens é possível restringir a pesquisa de imagens a um site específico.
- Check for more potential issues

**What should have happened?**

Correct listed problems and revise to find more.
Related https://github.com/arquivo/pwa-technologies/issues/1107

**Comment by amourao** [comment]
Fixed, add links to "Advanced Search" page

**Comment by dcgomes** [comment]
Finished review. @amourao please quickly double check and close Issue.

**Comment by amourao** [comment]
Revised
