### ISSUE TITLE
Design new concepts: Memorial page

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#1130]
**What is the URL that originated the issue?**
Example: http://www.umic.pt/

**What happened?**
Some design inconsistencies from the page needs to reconsidered.

**What should have happened?**
Design new concepts for the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/51712013/121180410-bd16d700-c858-11eb-8eff-02890dde2108.png)

**Comment by dcgomes** [comment]
@pcabritafccn please add files of the approved design to this issue.

**Comment by pcabritafccn** [comment]
Issue #1130 is now closed as new design is now implemented and in production.

![image](https://user-images.githubusercontent.com/51712013/129726716-cdfe1e5c-b165-4d00-b918-bf452ccf0a70.png)
