### ISSUE TITLE
search box and button aren't completely visible after searching on sobre.arquivo.pt

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#1133]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/pt/pesquisar/?q=geocities

**What happened?**
The search box and search buttons aren't completely visible after searching on sobre.arquivo.pt

**What should have happened?**
The search box and search buttons should be completely visible

**Screenshots**

![image](https://user-images.githubusercontent.com/67018/122534318-50e76080-d01a-11eb-9135-0ab923b306e9.png)

**Comment by pcabritafccn** [comment]
Issue #1133 is now closed: Search box and button are now completely visible on both EN and PT page versions.

![image](https://user-images.githubusercontent.com/51712013/129734874-a26e010e-dc31-45ea-8c1d-b1abe7c19227.png)
