### ISSUE TITLE
recomendacoes shortlink on footer is broken

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#1134]
**What is the URL that originated the issue?**
https://arquivo.pt/

**What happened?**
The shortlink on footer "Crie sites preserváveis" that goes to https://arquivo.pt/recomendacoes is broken.

**What should have happened?**
Fix the short link https://arquivo.pt/recomendacoes

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/122534777-c3f0d700-d01a-11eb-991f-53ed31f57a9c.png)

**Comment by igobranco** [comment]
Another on "Exemplos de páginas preservadas"  https://arquivo.pt/exemplos

**Comment by dcgomes** [comment]
https://arquivo.pt/recomendacoes was replaced by https://arquivo.pt/recomenda
https://arquivo.pt/exemplos was aggregated into page https://arquivo.pt/expos
