### ISSUE TITLE
"Last updated on XX"  needs to go to the bottom of the page  (sobre.arquivo.pt)

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1135]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/en/collaborate/suggest/

**What happened?**
On all pages the phrase "Last updated on XX" must be at the bottom of the page.
Solve with css?

**Screenshots**
![image](https://user-images.githubusercontent.com/25795364/122775647-450dcf80-d2a2-11eb-9a07-8b3a5ddc3205.png)

**Comment by pcabritafccn** [comment]
Issue #1135 is now closed as this is a form page and not a blog page. There's no need of showing info about dates. So, in this case we've applied CSS to remove this specific info from the page.

**Comment by PedroG1515** [comment]
We need to remove in the Portuguese version (also)

**Comment by pcabritafccn** [comment]
Update: Issue #1135 is now closed for both page languages: EN and PT.

EN
![image](https://user-images.githubusercontent.com/51712013/129732474-69d56599-f5c9-48e9-8e11-2acb20eea803.png)

PT
![image](https://user-images.githubusercontent.com/51712013/129732583-4a0d988e-181d-4487-acdd-a1727b05e641.png)
