### ISSUE TITLE
New form for Page Save Now (arquivo.pt)

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1136]
Create a form "arquivo.pt/savepagenow" with the following template:

![Template](https://user-images.githubusercontent.com/25795364/122956619-10b91280-d379-11eb-800c-c35452e5ecd3.JPG)

**Comment by VascoRatoFCCN** [comment]
https://dev.arquivo.pt/services/savepagenow

**Comment by VascoRatoFCCN** [comment]
Page is created, design improvements to the page in issue https://github.com/arquivo/pwa-technologies/issues/1139
