### ISSUE TITLE
Bug found in dev.arquivo.pt environment: image is not appearing in the image search results page (image is loaded but disappears after some seconds).

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#1138]
**What is the URL that originated the issue?**
http://dev.arquivo.pt/image/search?q=pedro+alvares+cabral&l=en&from=19910806&to=20210629&adv_and=pedro+alvares+cabral&offset=350

**What happened?**
Bug found in dev.arquivo.pt environment: image is not appearing in the image search results page (image is loaded but disappears after some seconds).

**What should have happened?**
Correct this in order to show all images.

**Screenshots**
![image](https://user-images.githubusercontent.com/51712013/123783608-756ef280-d8ce-11eb-8351-bdd1445b6082.png)

**Comment by PedroG1515** [comment]
I think the problem is not replay.
![image](https://user-images.githubusercontent.com/25795364/123924820-3ac69200-d982-11eb-8681-b0a0313a7114.png)

**Comment by amourao** [comment]
https://arquivo.pt/wayback/20180413215423im_/http://www.ubi.pt/Ficheiros/Sites/71/Paginas/803/PL997695.jpg

That image file is malformed: 
- on Chrome it starts loading and when it reaches the broken part it changes to the broken image symbol.
- on Firefox, it loads the image partially and keeps going as is.
 
Either keep it as is or do the same "hide if fails loading procedure as in https://github.com/arquivo/pwa-technologies/issues/1088

**Comment by arquivo-awp** [comment]
Cannot reproduce error from provided examples.
