### ISSUE TITLE
Generate and deploy graphical artes for “Conheça os vencedores do Prémio Arquivo.pt 2021”

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1140]
See last year's arts.

“Conheça os vencedores do Prémio Arquivo.pt 2021” link to "arquivo.pt/vencedores2021"
“Meet the winners of the Arquivo.pt Award 2021” “Conheça os vencedores do Prémio Arquivo.pt 2021”

Also create the Zoom backgrounds

**Comment by pcabritafccn** [comment]
Closing issue #1140 as this is already done.
