### ISSUE TITLE
Suggestion not aligned

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1142]
**What is the URL that originated the issue?**
http://dev.arquivo.pt/url/search?q=defr.pt&l=pt&from=19910806&to=20210712&adv_and=defr.pt

**What should have happened?**
1. Not aligned to the right
2. Arquivo.pt prodution do not show a suggestion:
     a. https://arquivo.pt/page/search?hitsPerPage=10&query=defr.pt&l=pt&ion-dt-1=1996-01-01&ion-dt-0=2021-07-12&dateStart=01%2F01%2F1996&dateEnd=12%2F07%2F2021 

**Screenshots**
![image](https://user-images.githubusercontent.com/25795364/125295007-b4646580-e31c-11eb-87bd-bfca40b22c75.png)

**Comment by VascoRatoFCCN** [comment]
Alignment fixed. Production almost never shows suggestions when no results are found, this seems to me like a bug in production and not in development.
