### ISSUE TITLE
Advance search button incorrect layout

### ISSUE THREAD

**Issue by vitgou** [arquivo/pwa-technologies#1159]
![Screenshot from 2021-08-31 15-22-20](https://user-images.githubusercontent.com/3265240/131520279-9d890c93-eaa1-4cc7-8b5e-1f0faacb333a.png)

With the introduction of the `narrative` button the layout of `advance search button` is not consistent. 

**DoD**

Modify the css so that `advance search button`  layout is consistent across multiple devices.

![Screenshot from 2021-08-31 15-26-37](https://user-images.githubusercontent.com/3265240/131520766-8f32c50c-45af-4714-b4eb-95a165daf2fe.png)

**Comment by pcabritafccn** [comment]
Issue #1159 is now solved and closed.

![image](https://user-images.githubusercontent.com/51712013/131548795-209c816a-f72e-410c-80fc-662a66e93e02.png)
