### ISSUE TITLE
Save Page Now with URL parameter

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1162]
**What is the URL that originated the issue?**
https://dev.arquivo.pt/services/savepagenow?your-sites=http://example.com/1.html

**What should have happened?**
1. https://dev.arquivo.pt/services/savepagenow?your-sites=http://example.com/1.html
2. The URL "http://example.com/1.html" need to be filled in th URL field.

**Screenshots**
![image](https://user-images.githubusercontent.com/25795364/132339385-c1acf167-27c0-4f6a-b5a5-5167b1cf6c2c.png)

**Comment by VascoRatoFCCN** [comment]
Added the url parameter to the savepagenow: 
[](https://dev.arquivo.pt/services/savepagenow?url=testing.url)
