### ISSUE TITLE
Create new roll-up for Arquivo.pt Award

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#1164]
**What is the URL that originated the issue?**
None

**What happened?**
Arquivo.pt award roll-up have an old _look and feel_ and not suitable to its new brand design.

**What should have happened?**
We will redesign a new roll-up to match the new Arquivo.pt brand design.

**Screenshots**

![image](https://user-images.githubusercontent.com/51712013/133777515-17daca2a-d56b-4d1a-8f40-8d32626abcbe.png)

**Comment by dcgomes** [comment]
Done: https://drive.google.com/open?id=1fS0NyJuA4Mc_Safpf3uZV7zWq6tgEGOn&authuser=sawfccn%40gmail.com&usp=drive_fs
