### ISSUE TITLE
Designing Arquivo.pt Award 2022 graphics for dissemination. 

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#1165]
Designing Arquivo.pt Award 2022 graphics for dissemination, including posters, flyers, social media and all related.

**Comment by dcgomes** [comment]
Publicly available for reuse at:
https://drive.google.com/open?id=1-DrBOs6VyR6Dlh3fsjjO14dtva8emVzL&authuser=sawfccn%40gmail.com&usp=drive_fs
