### ISSUE TITLE
MOOC Arquivo.pt

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1178]
Organize training resources and create a MOOC in colaboration with NAU-FCCN.

**Comment by ricardobasiliopt** [comment]
Has been postponed to the next milestone.

**Comment by arquivo-awp** [comment]
Postponed is not Closed :-)

**Comment by igobranco** [comment]
It was launched during this year:
- https://www.nau.edu.pt/pt/curso/pesquisar-e-aceder-ao-passado-com-o-arquivopt/
- https://www.nau.edu.pt/pt/curso/bem-publicar-para-bem-preservar/
- https://www.nau.edu.pt/pt/curso/casos-de-uso-do-arquivopt/
- https://www.nau.edu.pt/pt/curso/preservacao-da-web-e-arquivos/
