### ISSUE TITLE
Create new cards for homepage: Memorial

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#1182]
**What is the URL that originated the issue?**

arquivo.pt

**What happened?**

We need to implement new rows of cards for the homepage: **Memorial**

**What should have happened?**

We will implement new cards for the homepage.

**Screenshots**

![image](https://user-images.githubusercontent.com/51712013/140513485-bc47251e-74e8-4bce-8089-2c9fc2ad46de.png)

**Comment by dcgomes** [comment]
Ask Diogo or @hmendes from AMC for graphical help
