### ISSUE TITLE
Create a link on sobre.arquivo.pt with all information about SavePageNow

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1185]
Create a link on sobre.arquivo.pt with all information from SavePageNow

**Comment by arquivo-awp** [comment]
Add "Learn more"/"Saber mais" links below the existing description to: 
- https://sobre.arquivo.pt/en/savepagenow-to-record-webpages-immediately-on-arquivo-pt/
- https://sobre.arquivo.pt/pt/grave-paginas-no-arquivo-pt-com-o-savepagenow/
