### ISSUE TITLE
Page search Index small collections

### ISSUE THREAD

**Issue by vitgou** [arquivo/pwa-technologies#1188]
**DoD**

Page search index all small collections as a single large collection to save memory in the query servers.

AWP24 (0,42 TB) 
EAWP20 (0,01TB)
EAWP22 (sem infor) 3 WARCs
EAWP25 (1,5 TB)
EAWP26,  (0,54TB) 
Weblog (0,03 TB)
BlocoEsquerda (0,00TB)
BlogsSapo2018 (0,20TB)
DEM-IST (0,00TB)
DinisAlves2018 (0,00TB)
NON (0,00TB)
RAQ2017 (0,01TB)
RAQ2018 (0.10TB)
RAQ2019 (0,51TB)
PATCHING2019 (0,04TB)
CEGER (0,00TB)

To try:

page search indexing multi-version
separated url indexing
separated image indexing

We assume that there will be inconsistency between page, url and images

**Comment by PedroG1515** [comment]
related with #1078
