### ISSUE TITLE
Encoding URL on replay

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1195]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20211112094054/https://ec.europa.eu/research/participants/documents/downloadPublic?documentIds=080166e5c0231ec0&appId=PPGMS

**What happened?**
No versions

**What should have happened?**
https://preprod.arquivo.pt/wayback/cdx?url=https://ec.europa.eu/research/participants/documents/downloadPublic%3FdocumentIds=080166e5c0231ec0%26appId=PPGMS&output=json

**Solution**
'?' --> '%3F'
'&' --> '%26'

**Comment by VascoRatoFCCN** [comment]
This issue no longer seems to be present. The way URLs are handled on the replay page (arquivo.pt/wayback/...) was reviewed and in the process this issue seems to have been solved.
