### ISSUE TITLE
URL error on the top of the frame

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1196]
**What is the URL that originated the issue?**
The URL of a preserved webpage appears incomplete with one slash as http:/www.grandemercado.pt etc

**What should have happened?**
Print as http://www.grandemercado.pt etc

**Screenshots**
<img width="966" alt="print_issue-url-top" src="https://user-images.githubusercontent.com/44206545/142419070-5ca7f54a-0524-4d04-9938-cd47282a038e.png">

**Comment by ricardobasiliopt** [comment]
URL that originated the issue:
https://preprod.arquivo.pt/wayback/20170222034805/http:/www.grandemercado.pt/s/praia-p1.htm

**Comment by VascoRatoFCCN** [comment]
This might be an issue on either pywb or malformed CDX, either way it doesn't affect the ability to replay the website so it'll be postponed to a later milestone.

**Comment by VascoRatoFCCN** [comment]
Closing this issue as it can no longer be replicated:
https://arquivo.pt/wayback/20190323231701/https://www.grandemercado.pt/

Note: Probably had to do with the following apache configuration: https://httpd.apache.org/docs/2.4/mod/core.html#mergeslashes
