### ISSUE TITLE
result redirected to the live web for "www.cm-marco-canaveses.pt"

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#12]
Originally reported on Google Code with ID 13
```
What steps will reproduce the problem?
1. query: câmara municipal do marco de canaveses 
2. return as first result: http://www.cm-marco-canaveses.pt/ [html] (794 bytes) - 2008-03-12
3. when you click, the result redirects to the live web

What is the expected output? What do you see instead?

The archived page should be presented.

```

Reported by `migcosta` on 2012-02-03 10:52:57

**Comment by Fernando-Melo** [comment]
The following url leaks to the live web: arquivo.pt/wayback/20091218023553/http://www.cm-marco-canaveses.pt/

**Comment by Fernando-Melo** [comment]
#37

**Comment by dcgomes** [comment]
Test if this issue will be fixed with the adoption of PyWB for the Janus release.

**Comment by danielbicho** [comment]
Same problem with the resource: http://arquivo.pt/wayback/20030212194802/http://www.vodafone.pt/
The current wayback dont rewrite URLs from scripts at HEAD section of HTML

**Comment by Fernando-Melo** [comment]
All fixed with pywb that correctly rewrites redirect urls not leaking to the live Web.
