### ISSUE TITLE
Arquivo404 Should point towards the oldest version of a website

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1203]
Arquivo404 currently defaults to loading the most recent version available on Arquivo.pt . This shouldn't be the case for several reasons:

- Often when a website is faced with a 404, it simply redirects the user to the main page, and sometimes the most recent version of a page in Arquivo.pt reflects this behavior. (ex: [This Arquivo404 link](https://www.fccn.pt/SCCN/))
- An archive is more valuable the older its preserved contents are, we should give emphasis to the more valuable content and not the more easily available one.
- From our own experience, users usually are looking for the older versions of websites, as such this change would improve user experience.

**Comment by dcgomes** [comment]
Test again after milestone Francisco.

**Comment by VascoRatoFCCN** [comment]
Fixed in https://github.com/arquivo/arquivo404/commit/01801dd93e3e6160521a7f6a8c92ca074163180b
