### ISSUE TITLE
Arquivo404 does not display in framed replay

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1205]
As of the Eros deploy, our memento timemap replies link towards arquivo.pt/noFrame/replay rather than arquivo.pt/wayback. 
A consequence of this is that arquivo404 links towards the unframed (fullscreen) version of archived websites.

Should arquivo404 redirect the user to the framed version of a page or the fullscreen version?
- Showing the framed version would allow the user to see all the different versions of the page we have archived, while also promoting Arquivo.pt
- On the other hand, returning the unframed version looks more natural and may avoid user confusion, while at the same time people might feel more inclined to use arquivo404 if there is no "Arquivo.pt" branding on it.

Should our memento timemap replies link towards the fullscreen version?
  - Linking the framed version is what other web archives do, like the Internet Archive. It also allows the user to explore different versions available on Arquivo.pt and have access to other services like "completePage" which increases the usefulness of the linked resource.

**Comment by dcgomes** [comment]
arquivo404 should link to framed replay.

**Comment by VascoRatoFCCN** [comment]
Latest Francisco release fixed this issue by hosting the framed replay directly on pywb, consequently the memento API does too, which is what arquivo404 uses to find an archived page.
