### ISSUE TITLE
Investigate why search results lead to "Resource Not In Archive"

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#121]
Originally reported on Google Code with ID 122
```
Search for: www.oniweb.pt

All listed versions lead to an error:
http://arquivo.pt/search.jsp?l=pt&query=www.oniweb.pt&btnSubmit=Pesquisar+no+Arquivo&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2014

Investigate why?
```

Reported by `danielcoelhogomes` on 2015-04-20 16:57:12

**Comment by Fernando-Melo** [comment]
This problem occurs simply because the page www.oniweb.pt at the time we collected it redirected to www.oniweb.pt/Home . As we didnt archive www.oniweb.pt/Home , the redirect will lead to a page that we did not archive thus the error

**Comment by Fernando-Melo** [comment]
Close?

**Comment by dcgomes** [comment]
Close.

On 04-03-2016 18:12, Fernando-Melo wrote:
> Close?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arquivo/pwa-technologies/issues/121#issuecomment-192387967>.
> 

-- 
Daniel Gomes
Gestor do Arquivo.pt, Área de Serviços Avançados
Head of Arquivo.pt - the Portuguese Web Archive, Advanced Services
Department

Fundação para Ciência e a Tecnologia
Unidade FCCN - Computação Científica Nacional
Av. do Brasil, 101, 1700-066 Lisboa, Portugal
T: [+351] 300 005 190
daniel.gomes@fccn.pt   |   www.fccn.pt
