### ISSUE TITLE
Integrate new cards in home page

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1216]
Analyse new graphical concepts to make the home page cards to improve visual coherence among them and reduce graphical noise.
https://www.figma.com/file/okO3abLl7zSgY7dlDUfpzZ/Proposal-of-new-homepage-cards-for-Futura-version?node-id=0%3A1

**Comment by arquivo-awp** [comment]
Add 2 lines with short links to:
- Memorial
- SavePageNow
- Sugira site
- Arquivo404

**Comment by VascoRatoFCCN** [comment]
merging this issue with https://github.com/arquivo/pwa-technologies/issues/1280

Add card for news.
Links to:

PT:
https://arquivo.pt/news

EN:
https://arquivo.pt/noticias
