### ISSUE TITLE
Banner and Logo from SavePageNow are not positioned correctly

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1217]
**What happened?**
1.  https://arquivo.pt/services/savepagenow?l=pt
2.  Search for "beruby.com"
3.  Click on "Aceitar todos" (accept all cookies from the site)
4.  The arquivo.pt banner is on top of the site and the arquivo.pt logo appears in the lower left corner.

**What should have happened?**
The banner should not be on top of the site. The logo that appears in the corner should not appear.

**Screenshots**
![sdxdsa](https://user-images.githubusercontent.com/25795364/148924449-71b8e4cb-ad30-48a2-adfd-1872f4a514e6.JPG)

**Comment by VascoRatoFCCN** [comment]
Closing this issue as it seems to have been fixed

**Comment by PedroG1515** [comment]
![image](https://user-images.githubusercontent.com/25795364/184832707-b4ac9087-e0c1-41af-af35-6e95aad75687.png)
