### ISSUE TITLE
Finalize CentOS 7 upgrade

### ISSUE THREAD

**Issue by vitgou** [arquivo/pwa-technologies#1219]
Some of ours servers are still running old versions of CentOS (6), and the EOL was on 2020-11-30. We need to update Arquivo.pt infrastructure so that we are up-to-date with the latest security patches. The main objective of this story is to update the remaining CentOS 6 to CentOS 7. This is a transitory update until we decide which platform we should move to after 2024.

**Definition of Done (DoD)**
All servers are running at least CentOS 7.

**Comment by franciscoesteveira** [comment]
Closed. Not worth the effort, will upgrade every server to a new platform at the same time.
