### ISSUE TITLE
Address not found Save Page Now

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1223]
**What is the URL that originated the issue?**
https://arquivo.pt/services/savepagenow?l=en

**What happened?**
1. https://arquivo.pt/services/savepagenow?l=en
2. Search www.tebeosfera.es
3. Returns "Address not found. Make sure the address is correct." , but the website is available
**Screenshots**

**Screenshots**
![image](https://user-images.githubusercontent.com/25795364/149762491-de0ba6d8-c9e6-4439-a140-43d0e16e9c1b.png)

**Comment by arquivo-awp** [comment]
Pre-validation of URLs will be removed in #1284
