### ISSUE TITLE
SavePageNow/Complete page does not archive embeded images

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1224]
**What is the URL that originated the issue?**
https://antt.dglab.gov.pt/exposicoes-virtuais-2/a-viagem-de-circum-navegacao-de-fernao-de-magalhaes/

https://arquivo.pt/services/savepagenow

https://arquivo.pt/services/complete-page?url=http://antt.dglab.gov.pt/exposicoes-virtuais-2/a-viagem-de-circum-navegacao-de-fernao-de-magalhaes/&timestamp=20210301195008

**What happened?**
When we try to save/complete https://antt.dglab.gov.pt/exposicoes-virtuais-2/a-viagem-de-circum-navegacao-de-fernao-de-magalhaes/ the images are not displayed and not archived.

https://arquivo.pt/wayback/20210301195008/http://antt.dglab.gov.pt/exposicoes-virtuais-2/a-viagem-de-circum-navegacao-de-fernao-de-magalhaes/

**What should have happened?**
Images such as:
https://antt.dglab.gov.pt/wp-content/uploads/sites/17/2019/09/20190319_142253-249x300.jpg
Should have been archived.

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/150531572-75f42d31-fe44-4805-ae37-152f5b852084.png)

**Comment by PedroG1515** [comment]
Pywb did not rewrite:
![image](https://user-images.githubusercontent.com/25795364/175944803-f52c615c-4b73-4785-bfc3-34bb69330651.png)

**Comment by PedroG1515** [comment]
Same issue #1225
