### ISSUE TITLE
Save Page Now UI should present URL being archived

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1227]
What is the URL that originated the issue?
https://arquivo.pt/services/savepagenow

The "Save Page Now" UI should present on the top bar:
* URL of the page being archived

Notice that this URL must change as the user navigates to other pages and saves them.

Screenshots
![image](https://user-images.githubusercontent.com/13120352/150533723-62197da5-53ac-4389-af65-0042ec9c44e7.png)

**Comment by arquivo-awp** [comment]
Integrate URL as in top bar of replay: https://arquivo.pt/wayback/19980215101645/http://www.fccn.pt:80/

**Comment by VascoRatoFCCN** [comment]
Implemented in dev.arquivo.pt:

![image](https://user-images.githubusercontent.com/79858044/183036549-ed165902-a626-4e72-bcf8-1d6a4c6ec951.png)

**Comment by VascoRatoFCCN** [comment]
Make font and font-size the same as in replay:

![image](https://user-images.githubusercontent.com/79858044/186152292-31818ac9-6b5f-4da8-ab0d-696ad6a84e2d.png)

Do the same for CompletePage
