### ISSUE TITLE
Add new links to arquivo404 and Open datasets on www.arquivo.pt and sobre.arquivo.pt footers

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1228]
**What is the URL that originated the issue?**
www.arquivo.pt
sobre.arquivo.pt

**What happened?**
Change www.arquivo.pt footer to be consistent with sobre.arquivo.pt, take notice to use the short links.

**Screenshots**

www.arquivo.pt (Francisco milestone)
![image](https://user-images.githubusercontent.com/13120352/150534091-d4e1aea7-e782-4648-9525-969c8b288f9f.png)

sobre.arquivo.pt (Francisco milestone)
![image](https://user-images.githubusercontent.com/13120352/150534155-b2a7203b-80a8-41b2-9410-47ed76362909.png)

**Comment by dcgomes** [comment]
Add link to open data on footers on the "About" column:

PT
- "Dados abertos" -> https://arquivo.pt/dadosabertos

EN
- "Open datasets" -> https://arquivo.pt/dadosabertos

Put link after [API & Código-aberto](https://arquivo.pt/api)

**Comment by VascoRatoFCCN** [comment]
Simply adding the new links to the footer makes it unbalanced, now the columns are of different sizes:

![image](https://user-images.githubusercontent.com/79858044/182630150-738729b6-f3f3-459d-97ab-7ecfd8931d6d.png)

We should either be replacing old footer links with these new ones, or adding additional ones to the other columns so all 4 columns have the same number of entries.

**Comment by VascoRatoFCCN** [comment]
dev.arquivo.pt implements this

**Comment by dcgomes** [comment]
Unbalanced columns are acceptable.
