### ISSUE TITLE
Replace links on home page to short links

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1231]
**What is the URL that originated the issue?**
* https://arquivo.pt/
* https://arquivo.pt/?l=en

**What happened?**
The URLs linked by the cards should reference [short URLs](https://docs.google.com/spreadsheets/u/1/d/1jin1xWdUAR7MrONLyH-w_FNr2241_CR9Q1l_iBsE2dY/edit?usp=drive_web&ouid=103980846838708736063) whenever possible to facilitate maintenance and don't require deploy when a linked URL, for instance hosted on sobre.arquivo.pt changes.

**What should have happened?**
PT:
* O que é o Arquivo.pt?
* Testemunhos de utilizadores (test if embed video works properly with short url and if so, create new short url to apply same process to Testemunhos de utilizadores)
* Exemplos de páginas preservadas -> https://arquivo.pt/exemplos
* Exposições temáticas ->https://arquivo.pt/expos

EN:
* What is Arquivo.pt? -> https://arquivo.pt/embed/videoen
* Users testimonials  (test if embed video works properly with short url and if so, create new short url to apply same process to User testimonials)
* Examples of preserved pages -> https://arquivo.pt/examples
* Themed exhibitions -> https://arquivo.pt/exhibitions

**Screenshots**

**Comment by VascoRatoFCCN** [comment]
Created shortlink for testimonials:

PT - arquivo.pt/embed/testemunhos
EN - arquivo.pt/embed/testimonials

**Comment by dcgomes** [comment]
There are still links on the home page that are NOT short links. Please replace and create new ones if necessary:

PT:
- On the 2 embedded videos use:
https://arquivo.pt/embed/videopt
https://arquivo.pt/embed/testemunhos
- https://arquivo.pt/services/savepagenow -> https://arquivo.pt/savepagenow
- https://sobre.arquivo.pt/pt/category/noticias/ -> https://arquivo.pt/noticias

EN:
- On the 2 embedded videos use:
https://arquivo.pt/embed/videoen
https://arquivo.pt/embed/testimonials

- https://arquivo.pt/services/savepagenow -> https://arquivo.pt/savepagenow?l=en
- https://sobre.arquivo.pt/en/category/news-en/ -> https://arquivo.pt/news


Footer
- https://arquivo.pt/services/savepagenow?l=pt -> https://arquivo.pt/savepagenow
- https://arquivo.pt/services/savepagenow?l=en ->  https://arquivo.pt/savepagenow?l=en
