### ISSUE TITLE
Click on image should show image in original size

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1234]
**What is the URL that originated the issue?**
On the Details UI of any image such as:
https://arquivo.pt/image/search?q=c%C3%A3o&from=19910806&to=20220121&trackingId=a818e153c6ddf3385cbd_ae076c3c321a7fe9ce52

**What happened?**
On mouse over over the image presented on the Details UI, the cursor changes to hand, suggesting that the image is clickable. However, when the users click, nothing happens.

**What should have happened?**
Two possible approaches to fix this issue:
1. Remove On mouse over behavior of the cursor OR
2. Display image in original size on click.

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/150564253-aa6b71f2-53a0-4e9e-a3d0-c83573a5b83a.png)

**Comment by VascoRatoFCCN** [comment]
https://github.com/arquivo/arquivo-webapp-eros/commit/882cf1cf35f62b4089e55f361f45a0331a90e876 fixes this issue
