### ISSUE TITLE
Advanced search parameters disappear between Image Advanced Search UI and SERP

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1235]
**What is the URL that originated the issue?**
https://arquivo.pt/image/search?adv_and=uni%C3%A3o+europeia&adv_phr=uni%C3%A3o+europeia&adv_not=uni%C3%A3o+europeia&from=19910806&to=20220121&type=all&size=all&safeSearch=on&siteSearch=&trackingId=2250ef93a34adb4c5daf_bcc12a0ed547a831c31b

**What happened?**

1. Advanced search with "União Europeia" on the 3 input fields:
![image](https://user-images.githubusercontent.com/13120352/150565055-3fcd2175-a081-4a6e-9497-6be333419014.png)

2. SERP with operators for the the 3 input fields with value "União Europeia":
![image](https://user-images.githubusercontent.com/13120352/150565103-393f1a07-d361-4d54-a012-18634371e606.png)

3. If we click again on the Advanced search button, "Europeia" disappears, and the fields only include "União", instead of  "União Europeia":
![image](https://user-images.githubusercontent.com/13120352/150565414-4de28cb3-00a6-4852-96b1-56148c469c66.png)

**What should have happened?**
Input values must be maintained across UIs. 
This problem does not occur on the Page Advanced Search UIs.

**Comment by VascoRatoFCCN** [comment]
https://github.com/arquivo/arquivo-webapp-eros/commit/7cf93986d9b6107fa6fcdf609b3ed5698c6325ea fixes this issue
