### ISSUE TITLE
Image Advanced Search should support multiple format search

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1236]
What is the URL that originated the issue?
https://arquivo.pt/image/advanced/search?q=&from=19910806&to=20220121&trackingId=2250ef93a34adb4c5daf_39afec52f3282ff9d9b3

What happened?
On the "Images with the format:" input field only one format can be chosen at a time, even though the system supports searches with more than one file type.

What should have happened?
The user interface should allow for multiple options to be selected.
https://arquivo.pt/image/search?q=publico+format%3Agif%2Cjpg&l=en&from=19910806&to=20220121&trackingId=2250ef93a34adb4c5daf_4934ad1eedfe5d91065b

It also seems to exist some inconsistency with behavior of commands "type" and "format".

* **type**: it is referenced on the documentation of the [Image Search API](https://github.com/arquivo/pwa-technologies/wiki/ImageSearch-API-v1.1-(beta)). However, it does not support multiple values: https://arquivo.pt/image/search?q=publico+type%3Agif%2Cjpg&l=en&from=19910806&to=20220121&trackingId=2250ef93a34adb4c5daf_97b093a4382349b48e3b
* **format**: it is not referenced on the documentation of the [Image Search API](https://github.com/arquivo/pwa-technologies/wiki/ImageSearch-API-v1.1-(beta)). However, it seems to work with multiple values: https://arquivo.pt/image/search?q=publico+format%3Agif%2Cjpg&l=en&from=19910806&to=20220121&trackingId=2250ef93a34adb4c5daf_64ef54fee5d51dc8cbd1

* Screenshots 
![image](https://user-images.githubusercontent.com/13120352/150566211-263f1ce6-c37b-444f-9f57-18ae7dd499f8.png)

**Comment by VascoRatoFCCN** [comment]
the `fixed advanced image search issue` commit was supposed to reference #1235

**Comment by VascoRatoFCCN** [comment]
The *format:* tag does not do anything, you can check that by using both tags at the same time:

https://arquivo.pt/image/search?q=format%3Agif%2Cpng+type%3Ajpeg

All the results have names like "image.png" but their actual type is JPEG.
Currently there is no way to search multiple formats.

**Comment by VascoRatoFCCN** [comment]
https://github.com/arquivo/image-search-api/commit/c6b113037897c1c4521f79f280ee81d615935c28 fixed this issue.

Can be tested at https://dev.arquivo.pt/image/search?q=publico+type%3Agif%2Cpng

**Comment by arquivo-awp** [comment]
Looks OK. Ready to deploy.
