### ISSUE TITLE
bportugal.pt can not be properly crawl

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1245]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20220204093343/https://www.bportugal.pt/

**What happened?**
We are not being able to save some elements (css or js)

**Comment by arquivo-awp** [comment]
Try with Browsertrix

**Comment by ricardobasiliopt** [comment]
A high quality recording has been added and the CSS is now available in this collection. Closed #1245
