### ISSUE TITLE
SavePageNow, problems with the replay of the URL "rnca.fccn.pt"

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1246]
**What is the URL that originated the issue?**
https://arquivo.pt/savepagenow

**What happened?**
Problems with the replay of the URL "rnca.fccn.pt"

However, save page now is working correctly since the versions are going into production:
https://arquivo.pt/wayback/20220215164606/https://rnca.fccn.pt/

**Screenshots**
![image](https://user-images.githubusercontent.com/25795364/154319433-0bc8544c-d723-46c2-8746-5b269522ce79.png)

**Comment by VascoRatoFCCN** [comment]
doing it directly ( https://arquivo.pt/save/now/record/https://rnca.fccn.pt/ ) still doesn't work. This seems to be a pywb issue

**Comment by PedroG1515** [comment]
https://arquivo.pt/save/now/record/https://rnca.fccn.pt/ --> Works but It is slow.
![Capture](https://user-images.githubusercontent.com/25795364/159018296-8ba52bb4-2556-4ee3-94af-39761b193a0c.JPG)

**Comment by PedroG1515** [comment]
I think the problem is related to the internal network.
When I make a request through the Broker (wget) it is much slower than a request through my computer.
