### ISSUE TITLE
Repository agilejava.com it is broken

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#125]
Originally reported on Google Code with ID 126
```
I upgraded urls to:
http://central.maven.org/maven2


```

Reported by `borowiak` on 2015-05-17 07:50:30

**Comment by FCCNhviana** [comment]
This was already done and commited in the last release. 
The pom.xml was changed and tested with java version "1.7.0_71" and apache-maven-3.2.5.
