### ISSUE TITLE
Analyze results of security audit performed by RCTS CERT

### ISSUE THREAD

**Issue by franciscoesteveira** [arquivo/pwa-technologies#1251]
Report location: \\paris\ASA\AWP\Maintenance and Operations\Auditorias Segurança\Auditoria arquivo.pt fccn.pt FCCN.pdf

**Comment by franciscoesteveira** [comment]
- Test removal of Wordpress admin user in testing environment, before replicating in production.

**Comment by dcgomes** [comment]
Begin by trying to fix the 3 security Issues publicly accessible listed on the new version of the report:
\\paris\ASA\AWP\Maintenance and Operations\Auditorias Segurança\Auditoria arquivo.pt fccn.pt FCCNv2.pdf

**Comment by franciscoesteveira** [comment]
Wordpress updated to latest version.
