### ISSUE TITLE
Configure new servers - 105 -> 108

### ISSUE THREAD

**Issue by franciscoesteveira** [arquivo/pwa-technologies#1255]

**Comment by arquivo-awp** [comment]
p105.arquivo.pt (24 TB SSD): broker ramal A + pywb frame e noframe (migrar da p85)
p106.arquivo.pt (24 TB SSD): broker ramal B + pywb frame e noframe (migrar da p89)
p107.arquivo.pt (24 TB SSD): recorder ramal A: pywb completepage (migrar da p48), autopatching, pywb save (migrar da p85), citationsaver (não implementado)
p108.arquivo.pt (24 TB SSD): recorder ramal B: pywb completepage (migrar da p48), autopatching, pywb save (migrar da p89), citationsaver (não implementado)
p85.arquivo.pt antigos (8 TB SSD): dev.arquivo.pt (migrar da p50)
p89.arquivo.pt antigos (8 TB SSD): preprod.arquivo.pt (migrar da p82)
