### ISSUE TITLE
No version is being presented on CDX

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1258]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20210303061928/https://www.cm-castrodaire.pt/index.php?option=com_content&view=article&id=131&Itemid=166

**What happened?**
CDXJ is empty
https://arquivo.pt/wayback/cdx?url=https://www.cm-castrodaire.pt/index.php?option=com_content&view=article&id=131&Itemid=166

The problem may be related with & (SURT does not like &)

**Comment by VascoRatoFCCN** [comment]
If the URL is encoded, the CDX API works:

https://arquivo.pt/wayback/cdx?url=https%3A%2F%2Fwww.cm-castrodaire.pt%2Findex.php%3Foption%3Dcom_content%26view%3Darticle%26id%3D131%26Itemid%3D166

**Comment by VascoRatoFCCN** [comment]
#1285 fixed this
