### ISSUE TITLE
Include "byFCCN" logo on sobre.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1260]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt

**What happened?**
HTML: Adicionar a seguinte <td> após o <td class=".gsc-search-button">:
<td class="by-fccn"><a href=["http://www.fccn.pt"](http://www.fccn.pt/) target="_blank">by FCCN</a></td>

CSS:
.gsc-search-box .by-fccn a { color: transparent !important; padding: 2em 2em 3em; background: transparent url(["https://www.fccn.pt/media/2022/04/by_fccn_positive.svg"](https://www.fccn.pt/media/2022/04/by_fccn_positive.svg)) center center no-repeat; background-size: 5em; }

Involve @hmendes for web design development (markup/html).

**Comment by hmendes** [comment]
HTML: Add the follow <td> after <td class=".gsc-search-button">:
<td class="by-fccn"><a href="https://www.fccn.pt" target="_blank">by FCCN</a></td>

CSS:
.gsc-search-box .by-fccn a { color: transparent !important; padding: 2em 2em 3em; background: transparent url("https://www.fccn.pt/media/2022/04/by_fccn_positive.svg") center center no-repeat; background-size: 5em; }

**Comment by VascoRatoFCCN** [comment]
![image](https://github.com/arquivo/pwa-technologies/assets/79858044/94862293-70bd-4747-95de-0b57be4c6fbd)

Done
