### ISSUE TITLE
SavePageNow check URL

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1264]
**What is the URL that originated the issue?**
https://arquivo.pt/services/savepagenow?l=pt

**What happened?**
1. https://arquivo.pt/services/savepagenow?l=pt
2. Search "www.farfetch.com"
3. Error --> "The page is inaccessible. Make sure the address is correct."

**Screenshots**
![image](https://user-images.githubusercontent.com/25795364/163358487-8ed03560-4423-4978-9bd3-210e2dd75a46.png)

**Comment by arquivo-awp** [comment]
Remove pre-validation of submitted URL, will be fixed in #1284
