### ISSUE TITLE
esquerda.net not archiving 

### ISSUE THREAD

**Issue by lisbonjoker** [arquivo/pwa-technologies#1265]
**What is the URL that originated the issue?**
https://arquivo.pt/services/savepagenow?l=pt

**What happened?**
Trying to archive esquerda.net, got an error "A página está inacessível. Verifique se o endereço está correto." even tho the website is indeed working.

**What should have happened?**
SavePageNow working

**Screenshots**
![image](https://user-images.githubusercontent.com/80425961/164022606-7b043183-8a4a-466f-bda2-00eb9b141225.png)

**Comment by VascoRatoFCCN** [comment]
The cause for this is described in the following issue: https://github.com/arquivo/pwa-technologies/issues/1284

**Comment by dcgomes** [comment]
Fixed
