### ISSUE TITLE
New crawl of RCAAP citations using RCAAP API v.2

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1275]
Periodically we have been crawling the citations contained in the open-access publications of the [RCAAP network of OA repositories](https://www.rcaap.pt/directory.jsp) by parsing their exported sitemaps.

The sitemaps of the repositories hosted at FCCN (SARI service) are exported daily at 6h00.
For the other repositories we don't have control of their update frequency.

The [RCAAP API](https://www.rcaap.pt/api/) v.2, to be released until August 2022, will enable automatically query all the Portuguese open-access repositories, even if they are hosted externally to FCCN (e.g. [RepositoriUM](https://repositorium.sdum.uminho.pt/?locale=en)).

RCAAP API v.2 will export links to PDFs and allow us to restrict the “published” date, so that we can select only the new records of articles published since the last crawl of the RCAAP citations.

The obtained URLs from RCAAP API should be ingested on the workflow of the new [CitationSaver service](https://github.com/arquivo/CitationSaver)(see also Issue #1147).

**Comment by PedroG1515** [comment]
Done.
Check the documentation: [APISeedsGetter](https://github.com/arquivo/APISeedsGetter)
Collection : EAWP43
