### ISSUE TITLE
Add "Reconstruct page" feature from memento time travel to new Replay bar interface 

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#128]
Originally reported on Google Code with ID 129
```
The memento time travel service enables to invoke a service to reconstruct a given page
by obtaining information from several web archives.

For example, this Wikipedia page misses images in the PWA:
http://public.web.cern.ch/public/, 13:13:12 16 Julho, 2009
http://arquivo.pt/wayback/wayback/20090716131312/http://public.web.cern.ch/public/

But we can recover the page with images invoking the Time Travel Reconstruct feature:
http://timetravel.mementoweb.org/reconstruct/20090716211936/http://public.web.cern.ch/public/

We just need to construct and had an URL to the Replay bar.
```

Reported by `danielcoelhogomes` on 2015-06-11 13:41:14

**Comment by Fernando-Melo** [comment]
We decided to delay this to Hercules. Right?

**Comment by dcgomes** [comment]
Right.

On 04-03-2016 18:07, Fernando-Melo wrote:
> We decided to delay this to Hercules. Right?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arquivo/pwa-technologies/issues/128#issuecomment-192386687>.
> 

-- 
Daniel Gomes
Gestor do Arquivo.pt, Área de Serviços Avançados
Head of Arquivo.pt - the Portuguese Web Archive, Advanced Services
Department

Fundação para Ciência e a Tecnologia
Unidade FCCN - Computação Científica Nacional
Av. do Brasil, 101, 1700-066 Lisboa, Portugal
T: [+351] 300 005 190
daniel.gomes@fccn.pt   |   www.fccn.pt
