### ISSUE TITLE
Create new card on Arquivo.pt home page: Notícias

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1280]
Our news are very important and there should a card on the first or second row of the home page to:

Ask Diogo or @hmendes from AMC for graphical help

**Comment by dcgomes** [comment]
Links to:

PT:
https://arquivo.pt/news

EN:
https://arquivo.pt/noticias

**Comment by VascoRatoFCCN** [comment]
Closing this issue as it was merged with https://github.com/arquivo/pwa-technologies/issues/1216
