### ISSUE TITLE
SavePageNow can't record websites whose CA certificate is slightly misconfigured

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1284]
When trying to record some websites like www.essv.ipv.pt or [stayawaycovid.pt](https://stayawaycovid.pt/) we get the following response:

![image](https://user-images.githubusercontent.com/79858044/172445544-a0c9a6a5-4091-4be0-8605-4cba7adc424f.png)

However, web browsers have no problem accessing these websites:

![image](https://user-images.githubusercontent.com/79858044/172446056-07dfa2ed-cfdd-4be7-a40a-ad3da804cf89.png)

It happens because the CA certificate is missing some information that most web browsers can easily fill in. SavePageNow before starting to record a webpage, it tries to do a http request to the requested website. If anything goes wrong it doesn't start recording, in this case we get an error due to a misconfigured CA certificate.

**Comment by VascoRatoFCCN** [comment]
A related problem, SavePageNow can be used to bypass security verification, it works on many of https://badssl.com/ examples of bad SSL.
How the browser reacts:
![image](https://user-images.githubusercontent.com/79858044/173860299-52196c1d-3823-4763-b189-9e0d036bc679.png)
How SavePageNow reacts:
![image](https://user-images.githubusercontent.com/79858044/173860157-1e8e184e-7b3e-44eb-95ae-cb3a7d8a8cfb.png)

**Comment by arquivo-awp** [comment]
Remove pre-validation of URL on front-end.
Configure default error message on Pywb to avoid "ugly" error message.

**Comment by dcgomes** [comment]
Fixed
