### ISSUE TITLE
Verify if removed URLs were/are being removed from Image search indexes

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1287]
**What is the URL that originated the issue?**
https://arquivo.pt/image/search?q=Ricardo+Jorge+Salvador+Lopes&from=19910806&to=20220627&trackingId=2a18c5e9a9e75f395049_847e54c3a30159ce25e3

Check procedure "[Procedimento para pedidos de remoção](https://docs.google.com/document/d/1z3waCtjeGNez1OKHBpG5guljV3cWEYGC6Z-6Pm-4NvE/edit#)":

"
5. Procedimento técnico de remoção – ASA
...
5.4. Pesquisa de imagens:
Estes resultados podem ser bloqueados dos resultados de pesquisa utilizando como inspiração o script [update_block.py](https://github.com/arquivo/solr-cloud-scripts)"

**Comment by VascoRatoFCCN** [comment]
Updated procedure

**Comment by VascoRatoFCCN** [comment]
Updated documentation, will leave automation for a new issue
