### ISSUE TITLE
"Visit" button is broken

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1288]
**What is the URL that originated the issue?**
https://arquivo.pt/image/search?q=Ricardo+Jorge+Salvador+Lopes&from=19910806&to=20220627&trackingId=2a18c5e9a9e75f395049_847e54c3a30159ce25e3

**What happened?**
"Visit" button does not work:
![image](https://user-images.githubusercontent.com/13120352/175912647-33abf833-d032-4cd9-86cb-d5714d42b832.png)

https://arquivo.pt/wayback/20090925074609/http://www.alvorada.pt/noticia.php?

But link on the page title is correct:
![image](https://user-images.githubusercontent.com/13120352/175912918-9443a2a1-e619-4ec8-8c86-6a0140951892.png)

https://arquivo.pt/wayback/20090925074609/http://www.alvorada.pt/noticia.php?id=3480

It could be related with #1011 

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/175911699-db35c09b-d43a-4643-8a7b-3d8ba41c29fd.png)

**Comment by VascoRatoFCCN** [comment]
https://github.com/arquivo/arquivo-webapp-eros/commit/882cf1cf35f62b4089e55f361f45a0331a90e876 fixes this issue
