### ISSUE TITLE
Option to search on Memento Time Travel when we don't have results for URL search 

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#129]
Originally reported on Google Code with ID 130
```
When we do not have any result to present for a given URL (e.g. http://angelsanddemons.cern.ch/)

The error message page:
http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fangelsanddemons.cern.ch%2F&btnSubmit=Pesquisar+no+Arquivo&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2014

Should also include an option to search on the Memento Time Travel service:
http://timetravel.mementoweb.org/list/20090716211936/http://angelsanddemons.cern.ch/

Minor issue: " Sugira a página para que seja arquivada.": has an extra space in the
begining.

Fix also on English version.
```

Reported by `danielcoelhogomes` on 2015-06-11 13:47:51

**Comment by dcgomes** [comment]
Provide less and simpler alternatives:

"
We suggest that you:
- Verify the URL
- Suggest the site to be archived. (link with URL pre-filled on form http://sobre.arquivo.pt/collaborate/suggest-a-site)
- Search the Internet Archive (link with URL as query to archive.org) 
- Search other web archives (link with URL as query to http://timetravel.mementoweb.org/).
"

The texts of these options may need to be revised.

**Comment by Fernando-Melo** [comment]
The suggestions when URL not found were changed in the new PyWb version

**Comment by danielbicho** [comment]
The robots.txt have to be updated for the syntax /wayback, nothing in robots exclude the directory /wayback/help.jsp
