### ISSUE TITLE
Several different versions of an URL point to the same archived version.

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#13]
Originally reported on Google Code with ID 14
```
What steps will reproduce the problem?
1. Search for "www.dn.pt"
2. Open the first version of 2004: 9 Feb (http://arquivo.pt/wayback/wayback/id35066index0)
3. The archived page of 14 Feb 2005 is shown.
4. Go back.
5. Open the version 31 Mar 2004 (http://arquivo.pt/wayback/wayback/id36964index0)
6. The archived page of 14 Feb 2005 is shown.

The same behavior can be observed for every version up until 2006.
From 2006 to 2008, the same behavior happens with another archived version (http://arquivo.pt/wayback/wayback/20080212134236/http://dn.sapo.pt/).

Other archived websites present this behavior, e.g. "www.expresso.pt".

```

Reported by `devel.david@vcruz.net` on 2012-02-03 14:51:06

**Comment by Fernando-Melo** [comment]
I think this issue should be closed, because the strange redirects to further dates happened because of the closest date problem. However the above examples should be kept, and we should debug to understand why the above versions do not exist (although now there is a correct redirect to the version with the closest date avaliable)

**Comment by dcgomes** [comment]
Close after testing the examples over the Janus milestone.

**Comment by Fernando-Melo** [comment]
http://mega.ist.utl.pt/~sinfo is not working on pywb due to the ~ character. Try to fix it.

**Comment by Fernando-Melo** [comment]
Check with @FCCNhviana  the problems with the 2005 versions of the URL ipb.pt

**Comment by Fernando-Melo** [comment]
The remaining problems are fixed with PyWb

**Comment by FCCNhviana** [comment]
Me and @Fernando-Melo will solve together this problems next week.

**Comment by FCCNhviana** [comment]
http://www.ipb.pt:80/ 193.136.195.224 20050522010508 text/html 1284
HTTP/1.1 200 OK
Date: Sun, 22 May 2005 01:05:08 GMT
Server: Apache
Last-Modified: Fri, 25 Feb 2005 00:22:26 GMT
ETag: "8fba7-406-421e6fc2"
Accept-Ranges: bytes
Content-Length: 1030
Connection: close
Content-Type: text/html; charset=iso-8859-1

 <html>
 
<head>
<title>IPB - Instituto Politécnico de Bragança</title>
 <META name="description" content="O Instituto Politécnico de Bragança, foi criado em Dezembro de 1979 , tendo neste momento 5700 alunos distribuídos por 34 licenciaturas, no âmbito das Ciências A        grárias, Biotecnologia, Ciências da Educação, Ciências Empresariais, Artes, Desporto, Ciências da Engenharia e da Saúde.">
<META name="keywords" content="ipb, instituto, politecnico, politécnico, bragança, escola, superior, agrária, tecnologia, educação, enfermagem, esa, ese, estig, estgm, esenf">
<META HTTP-EQUIV="Pragma" CONTENT="no-cache">

 </head>
 
<frameset rows="0,*" framespacing="0" border="0" frameborder="0">
<frame name="cabecalho" scrolling="no" noresize target="principal">
<frame name="principal" src="http://portal2.ipb.pt/pls/portal/url/page/home_ipb/copy_of_home_ipb" scrolling="auto" noresize>
<noframes>
<body>


 <p>Esta página utiliza frames, mas o seu browser não as suporta.</p>
 
</body>
</noframes>


</frameset>

</html>

**Comment by FCCNhviana** [comment]
The above HTML code is an extract of ArcFile named FCCN-PT-HISTORICAL-ia400130.20090107153800. Therefore, there was a problem on the crawling and the web page was the properly archived.
