### ISSUE TITLE
Remove double "/wayback/" URL searches

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#130]
Originally reported on Google Code with ID 131
```
URL searches are sent to double "/wayback/" URLs:

http://arquivo.pt/wayback/wayback/20010603172030/http://www.fccn.pt/DNS/?in_menu_option=80000

This is confusing and worthless.

We should fix and use a more meaningful URL shcema like:

http://arquivo.pt/list/20010603172030/http://www.fccn.pt/DNS/?in_menu_option=80000

Or at least use just one "wayback":

http://arquivo.pt/wayback/20010603172030/http://www.fccn.pt/DNS/?in_menu_option=80000
```

Reported by `danielcoelhogomes` on 2015-06-11 16:51:22

**Comment by danielbicho** [comment]
Dont forget to change robots.txt after this issue being resolved.

**Comment by danielbicho** [comment]
I think this is a balanced aproach, doenst add much complexity and it keeps old syntax on.
Further tests will be made.

Apache Rule:
RewriteRule ^/wayback/wayback/(.*) /wayback/$1
RewriteRule ^/wayback/(.*) ajp://127.0.0.1:8009/wayback/wayback/$1 [P,L]
RewriteRule ^/(.*) ajp://127.0.0.1:8009/$1 [P]

Wayback Configuration:
Change replayURIPrefix to http://<server_name>/wayback/

Nutchwax Configuration:
Change wax.host t to http://<server_name>/wayback
