### ISSUE TITLE
Site recorded with SavePageNow giving error 429 - Too Many Requests

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1300]
I recorded the following website using SavePageNow on my phone: https://www.wamae.org/ 

It was added to Arquivo.pt some time later, it's available for consulting on https://arquivo.pt/wayback/20220818202323/https://www.wamae.org/  

However when trying to access it, there are missing elements:

![image](https://user-images.githubusercontent.com/79858044/186942731-d7f0e52e-b160-43a0-8697-01bb607508a3.png)

Looking in the devtools we can see that pywb's requests are being blocked with error 429 Too Many Requests:

![image](https://user-images.githubusercontent.com/79858044/186943155-d24373d1-8819-4972-84a9-fd9b6abd39ce.png)

Afterwards if we try to navigate the Arquivo.pt website we are still blocked with error 429:

![image](https://user-images.githubusercontent.com/79858044/186943619-a8a325ad-21b7-433f-92d8-9d0b70e54dad.png)

**Comment by franciscoesteveira** [comment]
Too Many Requests threshold was being triggered by a path of the recorded website which contained "/services". This wrongly matched against a configured QoS rule "/services".
Fixed QoS rules to match only against the start of the path string.
