### ISSUE TITLE
"Advanced search" label get cropped on the button only on English version

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1301]
**What is the URL that originated the issue?**
https://arquivo.pt/page/search?q=prezydent+RP&l=en&from=19910806&to=20220829&trackingId=f70fa4cddac7896a09e1_bfe9ed3d993527625e8f

https://arquivo.pt/image/search?q=prezydent+RP&from=19910806&to=20220829&trackingId=f70fa4cddac7896a09e1_4df9f8f3449b2f400f08

**What happened?**
The "search" on the "Advanced search" button goes to the next line and gets cropped.

![image](https://user-images.githubusercontent.com/13120352/187245088-0bed037f-07ef-4b78-b386-da3cb16aee57.png)

Same problem on image search UI:
![image](https://user-images.githubusercontent.com/13120352/187245616-3c98e282-d980-45a3-ac5f-6c5c378c9ed8.png)

Notice that this problem only happens on the English UI.

**What should have happened?**
Quick fix: add additional width to the "Advanced search" button to avoid that "search" jumps to the next line. 
Please make it a quick fix for milestone Fortuna.

**Comment by VascoRatoFCCN** [comment]
will change button width to 130px
