### ISSUE TITLE
Migrate to Google Analytics 4 property

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1304]
**What is the URL that originated the issue?**
https://support.google.com/analytics/answer/10759417

**Comment by VascoRatoFCCN** [comment]
GA4 structures data in a completely different way than UA. Stuff like the "Views" tab is completely gone in GA4.

UA:
![image](https://user-images.githubusercontent.com/79858044/191278977-3086fc45-e210-4b8e-a711-57c973e43b4e.png)

GA4:
![image](https://user-images.githubusercontent.com/79858044/191279437-f69e59ed-17b4-4c35-bf56-0b6a1141e1f2.png)



ContaMeHistorias is fully implemented in GA4 already, we can take inspiration on them to do the migration. This will affect not only Arquivo.pt analytics, but also other services that are managed by the same account:

- colibri
- LIAAD Demos
- Mundo na escola
- RCAAP
- SARC <- some properties already migrated to GA4
- SARI
- SciELO Portugal
- speedmeter.fccn.pt

**Comment by VascoRatoFCCN** [comment]
https://github.com/arquivo/arquivo-webapp-eros/commit/5e72872ec9dbd274845a389ab51dd23d05981773
https://github.com/arquivo/pywb-arquivo/commit/2504ac13c3b58ec6cd1db818d5f68156a551f762
