### ISSUE TITLE
Change arquivo404 arquivo.pt archiveApiUrl

### ISSUE THREAD

**Issue by franciscoesteveira** [arquivo/pwa-technologies#1305]
Make arquivo404 request arquivo.pt/arquivo404 and redirect these requests to the memento api URL.

This allows us to easily gather statistics about the usage of this service.

Also change the Internet Archive commented example to a working URL.

**Comment by dcgomes** [comment]
1. Create redirect https://arquivo.pt/arquivo404server to https://arquivo.pt/wayback
2. Change https://arquivo.pt/arquivo404.js (https://github.com/arquivo/arquivo404/blob/master/arquivo404.js)
		{ timeout: 2000, archiveName: "Arquivo.pt", archiveApiUrl: "https://arquivo.pt/wayback/timemap/link/" } 
to 
		{ timeout: 2000, archiveName: "Arquivo.pt", archiveApiUrl: "https://arquivo.pt/arquivo404server/timemap/link/" } 
3. Deploy to production

**Comment by dcgomes** [comment]
This change was deployed to production in 6  October 2022.
@PedroG1515 check logs and awstats to see if we can get the required usage stats for arquivo404.
