### ISSUE TITLE
Review About tab on Collections Table

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1309]
**What is the URL that originated the issue?**
https://docs.google.com/spreadsheets/d/1hfLyq9N2ZJEd1hra2V0OPI24jTy42ByR6M667rG-oHo/edit#gid=809941708

**What happened?**
Explain the meaning of the collection ID prefixes and contents of the Sheet.

Add link on the Public list available at https://arquivo.pt/collections
https://docs.google.com/spreadsheets/d/1lmlOLv_CHr3dQKL8bNwIDLAAPA2smZvJDoupl692D08/edit#gid=0

**Comment by arquivo-awp** [comment]
Adicionar Comment em cada coluna da [Collections Table 2.0 - publicly available to support deploys](https://docs.google.com/spreadsheets/u/1/d/1hfLyq9N2ZJEd1hra2V0OPI24jTy42ByR6M667rG-oHo/edit) a descrever a origem de cada valor em inglês.

PG adicionam Comments
FE revê os Comments
