### ISSUE TITLE
Link of the MCTES logo in the footer is out of date

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1311]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/

**What happened?**
The link of the MCTES logo in the footer is pointing to https://www.portugal.gov.pt/pt/ministerios/mctes.aspx

**What should have happened?**
Shoud point to https://www.portugal.gov.pt/pt/gc23/area-de-governo/ciencia-tecnologia-e-ensino-superior

**Screenshots**
<img width="954" alt="2022_10_18_16_27_45_Arquivo pt_pesquise_páginas_do_passado_Mozilla_Firefox" src="https://user-images.githubusercontent.com/44206545/196476649-4e59768a-b019-4322-9329-7fd9c5afa956.png">

**Comment by dcgomes** [comment]
Add logo on footer:
- ByFCCN

**Comment by VascoRatoFCCN** [comment]
The original issue has been fixed. Closing this since we have a separate issue for the "byFCCN" logo: https://github.com/arquivo/pwa-technologies/issues/1259
