### ISSUE TITLE
Link on the card "News" and "Notícias"

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1314]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/pt/category/noticias/

**What happened?**
News are displayed by category in Wordpress and images are repeated (the featured image and the image that is inside the text). Doesn´t look well.

**What should have happened?**
Card in Portuguese, should link to https://arquivo.pt/noticias
Card in English, should link to: https://arquivo.pt/news

**Screenshots**
<img width="951" alt="2022_10_20_10_41_10_WhatsApp" src="https://user-images.githubusercontent.com/44206545/19
<img width="951" alt="2022_10_20_10_55_09_WhatsApp" src="https://user-images.githubusercontent.com/44206545/196919834-54db00c0-f507-499d-be4a-bd61aa3292a9.png">
6919795-6622bbaf-32c6-4f11-a3db-440dfe4270e3.png">

**Comment by VascoRatoFCCN** [comment]
Fixed by https://github.com/arquivo/arquivo-webapp-eros/commit/d0eada78b160b8d8ecb2565bebbe8b396363602f
