### ISSUE TITLE
Remove the camera icon from the card "SavePageNow" on home page

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1317]
On the home page at https://www.arquivo.pt remove the camera icon from the card "SavePageNow" for consistency with the remaining cards that do not have any associated card.

![image](https://user-images.githubusercontent.com/13120352/200641382-1f16cf11-340b-468a-a211-01128b0b5bac.png)

**Comment by VascoRatoFCCN** [comment]
Fixed by https://github.com/arquivo/arquivo-webapp-eros/commit/efa85b9a5cca2a601d8ce1762778a8d96a3dac9d
