### ISSUE TITLE
Wrong charset on Query Suggestions

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1327]
The query suggestion function is displaying suggested query terms with wrong charset for accented characters.

https://arquivo.pt/page/search?q=cao+de+ca%C3%A7a+para+dar&l=pt&from=19910806&to=20230110&trackingId=ac9f882ba4c5f7888c48_b5a49ece67c57d9dd48d

![image](https://user-images.githubusercontent.com/13120352/211574124-bfea77df-fa5f-47f7-87bf-bfa88e31c5c1.png)

https://arquivo.pt/page/search?q=camara+municipal+de+leiria&l=pt&from=19910806&to=20230110&trackingId=ac9f882ba4c5f7888c48_e09763123fde4f038c29

![image](https://user-images.githubusercontent.com/13120352/211574233-1ded6b0d-e2e8-4832-b1de-689b6de9e8ea.png)

https://arquivo.pt/page/search?q=municipio+de+leiria&l=pt&from=19910806&to=20230110&trackingId=ac9f882ba4c5f7888c48_b2c8ab886ded7d7ac6f9

![image](https://user-images.githubusercontent.com/13120352/211574326-85eef6ba-5ae4-46ec-a06e-8f9094e4d0e4.png)

**Comment by VascoRatoFCCN** [comment]
The problem is on the spellchecker API:
https://arquivo.pt/spellchecker/checker?l=pt&query=cao%20de%20caça%20para%20dar 

![image](https://user-images.githubusercontent.com/79858044/212913933-d664702e-ece5-4abc-91f7-613394d20257.png)

**Comment by PedroG1515** [comment]
The problem disappeared

**Comment by dcgomes** [comment]
Bug persists on the branch of p106.arquivo.pt.

Branch p105.arquivo.pt is OK.

**Comment by franciscoesteveira** [comment]
Fixed.
