### ISSUE TITLE
Technical details of a Website appear many times

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1341]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20220521175334/https://jornaldeca.pt/

**What happened?**
Technical details of a Website appear many times, repeated. I used Vivaldi browser.

Screen capture, Gif:

![Recording 2023-05-24 at 15 21 26](https://github.com/arquivo/pwa-technologies/assets/44206545/d4a4d23c-cb23-4fbf-ac6f-321acccf436f)

**Comment by VascoRatoFCCN** [comment]
Seems to be fixed. Tried in multiple browsers and could not reproduce this issue,
