### ISSUE TITLE
Improve Query Suggestion

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#136]
Improve the query suggestion, so that the examples written in the technical report suggest the correct spelling, namely
amiaça  -> ameaça
corassão -> coração
escluir -> excluir
igienico -> higiénico
mangerico -> manjerico
rédia -> rédea

**Comment by Fernando-Melo** [comment]
For the imagesearch service we can maybe use solr features to replace spellchecker such as: 

- Solr spell checking https://lucene.apache.org/solr/guide/6_6/spell-checking.html
- https://lucene.apache.org/solr/guide/8_1/suggester.html for autocompleting

**Comment by PedroG1515** [comment]
Finished!
We use the Spellchecker from Bing API!
