### ISSUE TITLE
Block URL requests to textsearch using the q parameter

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1368]
Requests to the textsearch API using an URL in the q paramenter are slow to process and can sometimes be a heavy burden to our system. We already provide plenty of alternatives for URL searching: the CDX API, the VersionHistory parameter and the Memento API.

We should identify and block any URL requests on the textsearch API with code 400 - Bad Request, with links to the VersionHistory parameter, the CDX API and the Memento API.

**Comment by dcgomes** [comment]
@vitgou check if we can implement this blocking in Apache httpd, maybe through mod_qos.

**Comment by VascoRatoFCCN** [comment]
Blocked on the API using the same REGEX the frontend uses to redirect searches to /url/search
