### ISSUE TITLE
Fix broken links on Work descriptions og 2019 Awards

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1379]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/pt/conheca-os-vencedores-do-premio-arquivo-pt-2019/

**What happened?**
Links to [Descrição do trabalho 404](https://drive.google.com/open?id=1lOIa53dHB_7-D2Y2f9BdHbkZN2JNZ9Kr) are broken because they link to Google drive

**What should have happened?**
They should link to PDF files uploaded to sobre.arquivo.pt

**Screenshots**
![image](https://github.com/arquivo/pwa-technologies/assets/13120352/049c0697-fc68-4cf4-b6f2-62a232a91940)

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by ricardobasiliopt** [comment]
![image](https://github.com/user-attachments/assets/63782481-5317-4757-b6de-adc23aa8f558)

Closed #1379
