### ISSUE TITLE
Date Picker , all years should be shown in the date search

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#138]
As you can see in the attached image, when searching the date picker only shows the years from 1996 to 2011. A scrolling option should be added and all years should be shown.
![picker](https://cloud.githubusercontent.com/assets/13658607/9109946/a05d379e-3c31-11e5-89d1-69620b5b7fee.png)

**Comment by FCCNhviana** [comment]
Done.
