### ISSUE TITLE
Add links to "Memória descritiva" on the 2018 Award Winners

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#1380]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/pt/vencedores-premios-arquivo-pt/

**What happened?**
Files and links to the "Memória descritiva" of "1º classificado – “Conta-me Histórias”"
and "3º classificado – “Arquivo de Opinião”" are missing.

**Screenshots**
![image](https://github.com/arquivo/pwa-technologies/assets/13120352/ea9679ef-da0f-48df-a724-f2e043785451)

![image](https://github.com/arquivo/pwa-technologies/assets/13120352/3b2eb78b-6a29-40ef-b9df-ac5cfcfe4c7e)

**Comment by ricardobasiliopt** [comment]
Closed #1380
