### ISSUE TITLE
Emails sent to the wrong address

### ISSUE THREAD

**Issue by vitgou** [arquivo/pwa-technologies#1382]
Currently, some emails are being sent to `techiesarquivopt@googlegroups.com` or arquivo collaborators. Change the emails on  all jobs (production) to `awp@asa.fccn.pt`

**DoD**

There are no emails sent to techiesarquivopt@googlegroups.com. 
There are no emails sent to arquivo collaborators.
Everything goes to awp@asa.fccn.pt.

**Comment by dcgomes** [comment]
Looks fixed but continue monitoring.
