### ISSUE TITLE
CompletePage displaying accentuated characters as "�"

### ISSUE THREAD

**Issue by VascoRatoFCCN** [arquivo/pwa-technologies#1389]
This page was missing images: https://arquivo.pt/wayback/20070119120355/https://saude.sapo.pt/gk1/359925.html
![image](https://github.com/user-attachments/assets/50077eeb-7e9e-4877-9b30-293d4120de89)

Using CompletePage some of the images were retreived, but the character encoding broke, accentuated characters are being displayed as "�":
![image](https://github.com/user-attachments/assets/b2c06f61-a411-4dff-8b39-c4f98507211f)

**Comment by PedroG1515** [comment]
This issue does not affect the final result of the wayback
