### ISSUE TITLE
Implement the new interface for viewing archived pages

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#14]
Originally reported on Google Code with ID 15
```
Implement the new interface for archived pages (internally named "replay bar").
The new viewer supports in-place navigation of the different versions of the viewed
archived page and sharing features.
```

Reported by `devel.david@vcruz.net` on 2012-02-13 16:29:20
- **Blocking**: #16

**Comment by Fernando-Melo** [comment]
We don't need to update our interfaces (i.e. to create a new interface XML/Jason), because pywb comes with the cdx-server API, which outputs the list of versions as JSON
