### ISSUE TITLE
Correct footer links on sobre.arquivo.pt and www.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#140]
Novo footer para sobre.arquivo.pt e www.arquivo.pt

Dúvidas: daniel.gomes@fccn.pt

PT:
Sobre
    Objetivos -> O que é o Arquivo.pt? -> http://sobre.arquivo.pt/sobre/o-que-e-o-arquivo.pt
    
	Publicações -> arquivo.pt/publicacoes -> http://sobre.arquivo.pt/sobre/publicacoes-1/publicacoes
    
	Vídeos: Remover
	
	Páginas de exemplo -> Exemplos de páginas preservadas -> arquivo.pt/exemplos -> http://sobre.arquivo.pt/sobre/paginas-de-exemplo-no-arquivo-da-web-portuguesa/
    
	Área de imprensa -> arquivo.pt/imprensa -> http://sobre.arquivo.pt/sobre/area-de-imprensa  
	
	Serviços e Software em código-aberto -> arquivo.pt/servicos -> http://sobre.arquivo.pt/sobre/servicos/software
	
	Avisos Legais: OK
	
Notícias
	Últimas novidades -> arquivo.pt/news -> http://sobre.arquivo.pt/news/portuguese-web-archive-news
    
	Twitter: OK
    
	Facebook: OK
    
	Linkedin: Remover
    
	RSS -> Subscreva RSS -> arquivo.pt/rss -> http://sobre.arquivo.pt/news/portuguese-web-archive-news/RSS?set_language=pt

Colabore

    Sugira um sítio web -> Sugira para arquivo -> arquivo.pt/sugerir -> http://sobre.arquivo.pt/colaboracao/sugerir-um-sitio
    
	Divulgue o Arquivo.pt -> arquivo.pt/divulgar -> http://sobre.arquivo.pt/colaboracao/apoie-o-arquivo-da-web-portuguesa-divulgando-o
	
	Respeite recomendações -> Crie sites preserváveis -> arquivo.pt/recomendacoes -> http://sobre.arquivo.pt/colaboracao/recomendacoes-para-autores-de-sitios-web/
    
	Forneça conteúdos para serem preservados -> http://sobre.arquivo.pt/colaboracao/fornecimento-de-conteudos-historicos-da-web/
    
    Projetos de I&D -> Investigação e Desenvolvimento -> arquivo.pt/ID -> http://sobre.arquivo.pt/colaboracao/actividades-de-investigacao-e-desenvolvimento

Ajudas -> Ajuda
	Pesquisa -> http://sobre.arquivo.pt/ajuda/pesquisa
	
	Pesquisa avançada -> http://sobre.arquivo.pt/ajuda/pesquisa-avancada
	
	Acesso a conteúdos arquivados -> http://sobre.arquivo.pt/ajuda/acesso-a-conteudos-arquivados 
	
	Recolha -> http://sobre.arquivo.pt/ajuda/acesso-a-conteudos-arquivados
	
	Mapa do sítio: Remover
    
	Perguntas frequentes-> arquivo.pt/faq -> http://sobre.arquivo.pt/ajuda
	
	Contacto: OK

EN:
About
    Objetives -> What is Arquivo.pt - the Portuguese Web Archive? -> http://sobre.arquivo.pt/about-the-archive/project
    
	Publications -> arquivo.pt/publications -> http://sobre.arquivo.pt/about-the-archive/publications-1
    
	Videos: Remover
	
	Examples pages -> Examples of preserved pages -> arquivo.pt/examples -> http://sobre.arquivo.pt/about-the-archive/example-pages-in-the-portuguese-web-archive
    
	Press -> arquivo.pt/press -> http://sobre.arquivo.pt/about-the-archive/press 
	
	Services and open-source projects -> arquivo.pt/services -> http://sobre.arquivo.pt/about-the-archive/services-and-open-source-projects
	
	Legal Notices: OK
	
News
	Latest news -> arquivo.pt/news -> http://sobre.arquivo.pt/news-1/news/news_old/aggregator
    
	Twitter: OK
    
	Facebook -> Change https://www.facebook.com/ArquivoWebPortuguesa to https://www.facebook.com/PortugueseWebArchive
    
	Linkedin: Remover
    
	RSS -> Subscribe RSS -> arquivo.pt/rss -> http://sobre.arquivo.pt/news-1/news/news_old/aggregator/RSS

Colaborate

    Suggest a site -> Suggest a site to be archived -> arquivo.pt/suggest -> http://sobre.arquivo.pt/collaborate/suggest-a-site
    
	Spread the word -> Disseminate Arquivo.pt -> arquivo.pt/disseminate ->  http://sobre.arquivo.pt/collaborate/support-the-portuguese-web-archive-spreading-it
	
	Follow recommendations -> Publish preservable web content -> arquivo.pt/recomendations -> http://sobre.arquivo.pt/collaborate/recommendations-for-web-authors-to-enable-web/recommendations-for-web-authors-to-enable-web
	
	Supply contents -> Supply historical web content to be preserved -> http://sobre.arquivo.pt/collaborate/supplying-historical-portuguese-web-contents
	
    R&D Projects -> Research & Development -> arquivo.pt/RD -> http://sobre.arquivo.pt/collaborate/research-and-development-activities-1

Help
	Search -> http://sobre.arquivo.pt/help/search-1
	
	Advanced search -> http://sobre.arquivo.pt/help/advanced-search

	Access to archived contents -> http://sobre.arquivo.pt/help/access-to-archived-contents
	
	Crawling and archiving Web content -> http://sobre.arquivo.pt/help/content-crawling-and-archiving
	
	Site Map: Remove
    
	FAQ -> Frequently Asked Questions -> arquivo.pt/faq-en -> http://sobre.arquivo.pt/help
	
	Contact: OK

**Comment by danielbicho** [comment]
Shortlinks Rewrites are done, will be updated at productions servers when hviana starts working in the issue.

**Comment by FCCNhviana** [comment]
Footer on arquivo.pt updated.

**Comment by FCCNhviana** [comment]
Waiting for judgment department review about legal terms.
Two terms conditions pages with different messages.
http://plone.arquivo.pt/sobre/avisos-legais 
http://p21.arquivo.pt/terms-conditions.jsp?l=pt

**Comment by FCCNhviana** [comment]
Done.
