### ISSUE TITLE
Fix .EU crawl log broken link

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#145]
On http://plone.arquivo.pt/news/a-first-attempt-to-archive-the-.eu-domain,

Fix broken link http://arquivo.pt/crawlreport/heritrix.crawlog.tar.gz
Heritrix original crawl log (19,6 GB);

The URL http://arquivo.pt/crawlreport/heritrix.crawlog.tar.gz should be valid.

**Comment by danielbicho** [comment]
Everything is working OK. Paths and permissions checked.

The file cannot be downloaded from the corporation network due too firewall policies, but is **acessible** from other networks.
