### ISSUE TITLE
Verify property sobre.arquivo.pt on Google Webmaster Tools

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#146]
https://www.google.com/webmasters/tools/home?hl=en&pli=1

Xenu (http://home.snafu.de/tilman/xenulink.html) does not handle properly the PT and EN versions of the development version of the site (plone.arquivo.pt). It provides too many false positives for errors.

Must test links again after deploy to production (sobre.arquivo.pt) using Google Webmaster Tools or other online tool.

**Comment by danielbicho** [comment]
The property of sobre.arquivo.pt was verified.

Waiting for new release to check broken links.

**Comment by danielbicho** [comment]
Checking of broken links after a release of sobre.arquivo.pt on Issue #85

Verified property sobre.arquivo.pt on Google Webmaster Tools resolved.
