### ISSUE TITLE
Not listing https urls when searching for a site using http://site.com or when searching for www.site.com

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#147]
When you introduce a url in the search box without writing https:// , the https site is not listed

Either when searching for a website writing http://www.site.com or when writing www.site.com, the https version of the site should also appear in the list of versions for the site.

**Comment by Fernando-Melo** [comment]
These are search problems and not Wayback problems.
In pywb version the replay of https Web sites will work.
However there are still the same search problems with HTTPS websites to be solved

**Comment by FCCNhviana** [comment]
The user have to introduce the full URL that they are looking for. We could add an expand for https://, but i think we should keep it simple and search for only for the URL that users set on the search text box. 
The user could always use the full-text search if we do not remember the URL.
