### ISSUE TITLE
"other dates" link on results pages has low users' usage

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#15]
Originally reported on Google Code with ID 16
```
The "other dates" link on search results pages has low information scent and is thus
skipped by users.

Greater highlight should be given to this feature.

Solving issue 15 should minimize the impact of users skipping the "other dates" links.

```

Reported by `devel.david@vcruz.net` on 2012-02-13 16:38:58
- **Blocked on**: #15

**Comment by Fernando-Melo** [comment]
Change the name other dates to Table of versions as suggested by @dcgomes (do it both when presenting the search results list, and on the replay bar)

**Comment by dcgomes** [comment]
The labels are: "Versions table" (EN) and "Tabela de versões" (PT)

**Comment by dcgomes** [comment]
The labels are: "Versions table" (EN) and "Tabela de versões" (PT).
