### ISSUE TITLE
Resource not found malformed redirect

### ISSUE THREAD

**Issue by FCCNhviana** [arquivo/pwa-technologies#150]
If user searches for a URL and  page is not archived,  the error page returned  is not the correct.

The wrong result page:
http://arquivo.pt/wayback/wayback/20100603041224/http://www.asds.pt/
http://arquivo.pt/wayback/wayback/20110630225443/http://rss.feedsportal.com/c/32443/f/475617/s/163d4a15/l/0L0Sjn0Bpt0CPaginaInicial0CTecnologia0CInterior0Baspx0Dcontent0Iid0F1890A566/story01.htm?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+JN-TECNOLOGIA+%28JN+-+Tecnologia%29

The correct result page:
http://arquivo.pt/search.jsp?l=pt&query=fgyjhyhfh.pt&btnSubmit=Pesquisar
http://arquivo.pt/resaw

**Comment by Fernando-Melo** [comment]
The expected result is a specific Web page for not found resources (currently the text is only NOT Found) and not the http://arquivo.pt/search.jsp?l=pt&query=fgyjhyhfh.pt&btnSubmit=Pesquisar
http://arquivo.pt/resaw So our current resourcenotfound page specially the part Enter Web Address

**Comment by Fernando-Melo** [comment]
We have to decide which will be our ResourceNotFound page for Arquivo.pt with PyWb
