### ISSUE TITLE
Calendar Display When searching by URL

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#157]
Instead of displaying all the years when searching by url (e.g., http://arquivo.pt/search.jsp?l=pt&query=sapo.pt&btnSubmit=Pesquisar), make a dynamic table that only displays the years where there is at least one version.

Put the embargo message in the last year of the table instead of having a seperate column ('more results')

**Comment by dcgomes** [comment]
Will not do this because hiding the years without versions would provide an inconsistency between the space on the table and the years, that would confuse the interpretation of the provide results by the users.
