### ISSUE TITLE
Wayback HTTP partial request

### ISSUE THREAD

**Issue by FCCNhviana** [arquivo/pwa-technologies#158]
Wayback made use of http partial request for streaming a web content. However, in each connection arcproxy streams the all web content, which is  from the offset until the end of file. This could be reproduce a slow response to an end-user. Hence, we have to append only length (i.e. web content + header) of the resource to the response , in the sense that only the web content is sent to the user.

Suggestion:
We could try adding some fixed size to the content-length to estimate the ARC record length, like content-length + 2048, to account for the ARC record size.

This is the actual range response
Range: 11852-
This would be a better response
Range: 11852-(20548) 

This class could be helpfully
ArcProxyServlet.java.

**Comment by dcgomes** [comment]
I suggest to close this issue because the TCP buffer reader only downloads the required until the end of the ARC record. The possible overhead is just a few bytes.

@danielbicho analyzed this info with data from real usage (Google Sheet Workload Characterization).
