### ISSUE TITLE
Fix Google Analytics of sobre.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#159]
It seems it stopped working since 20 October 2014.

https://www.google.com/analytics/web/?hl=en#report/visitors-overview/a21825027w43114507p47220271/%3F_u.date00%3D20141001%26_u.date01%3D20151028/

Verify javascript code on the page.

**Comment by FCCNhviana** [comment]
Java script was updated for last release of google. Additionally, documentation was improved into wiki page Plone.
