### ISSUE TITLE
Nutchwax: Inconsistent status codes when retrieving a resource

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#163]
There are many resources that sometimes are sucessfully presented to the user (200 http code) and other times are not found (404 http code), thus offering an inconsistent replay of the web pages for the user.

One such example is when replaying the web page http://europa.eu some css sometimes are not loaded such is the case of http://europa.eu/eu_portal/stylesheets/splashpage.css (this happens both on pywb and openwayback).

**Comment by Fernando-Melo** [comment]
#164

**Comment by FCCNhviana** [comment]
We should postpone this issue and #164 for the milestone of SOLR.

**Comment by dcgomes** [comment]
Still happens with PyCDX? If not, close.

**Comment by Fernando-Melo** [comment]
solved with CDX records
