### ISSUE TITLE
"See more>>" on arquivo.pt should link directly to list of example pages at sobre.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#165]
The link "See more>>" on arquivo.pt should link directly to the list of example pages managed through the CMS at sobre.arquivo.pt (http://sobre.arquivo.pt/about-the-archive/example-pages-in-the-portuguese-web-archive).

The page "Highlighted archive pages" http://arquivo.pt/highlights.jsp?l=en just presents 4 additional examples than those presented on the home page Arquivo.pt and the page is hard to manage because it is static HTML.

Thus, in sum on arquivo.pt change the links: 

- "Ver mais >>" to: http://sobre.arquivo.pt/about-the-archive/example-pages-in-the-portuguese-web-archive
- "See more>>" to: http://sobre.arquivo.pt/about-the-archive/example-pages-in-the-portuguese-web-archive?set_language=en

**Comment by FCCNhviana** [comment]
The webpagehttp://sobre.arquivo.pt/about-the-archive/example-pages-in-the-portuguese-web-archive?set_language=pt does not return a portuguese page.
It was used http://sobre.arquivo.pt/sobre/paginas-de-exemplo-no-arquivo-da-web-portuguesa, instead.

JSTL script was developed to choose the page to return.

**Comment by FCCNhviana** [comment]
This was deployed along with the update of tomcat version. Therefore, it was already deployed .
