### ISSUE TITLE
Page is replayed correctly with /wayback in the url but enters a loop with /wayback/wayback/

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#166]
This url works:
 http://p58.arquivo.pt/wayback/20130320160310/http://www.iol.pt/

Whereas this is not working (enters a loop)
http://p58.arquivo.pt/wayback/wayback/20130320160310/http://www.iol.pt/

**Comment by danielbicho** [comment]
@Fernando-Melo , double check if this issue persist. With the current rewrite configuration seems fixed with my browser.

**Comment by Fernando-Melo** [comment]
Seems fixed
