### ISSUE TITLE
Version is not referencing the closest date before

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#170]
Search for URL history of http://www.publico.clix.pt/.
http://arquivo.pt/search.jsp?query=http%3A%2F%2Fwww.publico.clix.pt%2F&dateStart=01/01/1996&dateEnd=31/12/2014&pos=5

Observe the following verisions:
- 17 Dez: link to http://arquivo.pt/wayback/20091217212753/http://publico.clix.pt/
  Replayed page: http://arquivo.pt/wayback/20091217212753/http://publico.clix.pt/
  17 Dezembro, 2009: OK
- 18 Dez: link to http://arquivo.pt/wayback/20091218133010/http://www.publico.clix.pt/
  Replayed page: http://arquivo.pt/wayback/20091218133010/http://www.publico.clix.pt/
  18 Dezembro, 2009: OK
- 25 Dez: link to http://arquivo.pt/wayback/20091225184303/http://www.publico.clix.pt/index.asp
  Replayed page: http://arquivo.pt/wayback/20091217212753/http://publico.clix.pt/
  17 Dezembro, 2009: NOT OK

Even if there was a problem with the 25 Dez version, the presented result should be the version from 18 Dez and NOT 17 Dez.

This bug seems to be somehow related to the URL expansion of searched URLs http://www.publico.clix.pt/ (17, 18 Dez) to http://www.publico.clix.pt/index.asp (25 Dez).

**Comment by Fernando-Melo** [comment]
When you click on the version of 25 Dez , you are searching for the link http://www.publico.clix.pt/index.asp (notice the extension index.asp). 
So the Nutchwax will search for the closest version of the file index.asp, which is on the 17th December (no version of index.asp on the 18th December) .

**Comment by dcgomes** [comment]
It should also expand URLs to look for closest versions.

**Comment by danielbicho** [comment]
I dont understand why sometimes the links have index.asp and sometimes not. The expand url make sense when the user searchers for a link, but in the listed versions it should all be without index.asp, i mean why index.asp? In the AWP6 Crawl Logs the crawler never fetched a index.asp. And the site was harvested with one heritrix job, so how we have 3 versions of this site? Being the 25 Dec the same version of 17 Dec, and 18 Dec a new one.

**Comment by dcgomes** [comment]
Fixed on Milestone PyCDX.
