### ISSUE TITLE
Wayback pages that should NOT available and are listed on Google search results

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#173]
These Wayback pages should NOT available and are listed on Google search results
http://arquivo.pt/wayback/wayback/index.jsp
http://arquivo.pt/wayback/help.jsp

Listed on: https://www.google.pt/search?q=site%3A.pt+%22internet+archive%22&oq=site%3A.pt+%22internet+archive%22&aqs=chrome..69i57j69i58.7799j0j4&sourceid=chrome&es_sm=93&ie=UTF-8

Fix with the adoption of PyWB?

**Comment by Fernando-Melo** [comment]
What should I do?
Option a) Nothing, and when you click on those urls it would show our default Not archived page (that happens every time we don't have the resource)
Option b) Redirect the help.jsp to sobre.arquivo.pt/ajuda , and redirect the http://arquivo.pt/wayback/wayback/index.jsp to http://arquivo.pt ?

**Comment by danielbicho** [comment]
Robots.txt was updated to not let googlebot reach that path.

Although, in their documentation the proper way to do this is using the metatag noindex.

Dont know the how much time we have to wait for this changes to take action.

**Comment by danielbicho** [comment]
Arquivo.pt Wayback pages dont appear anymore on Google Search results. 

Closing
