### ISSUE TITLE
Página já não exite

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#186]
Na página sobre.arquivo.pt  - Noticias ma comunicação social o link (http://sobre.arquivo.pt/sobre/publicacoes-1/publicacoes)

- Alex da Silveira, Preservação da Web - Análise do Arquivo da Web Portuguesa, Bibliotecno, 26 de Fevereiro de 2010 (jpg,pdf)

Já está não está válido, sugiro a alteração para a versão arquivada?

**Comment by dcgomes** [comment]
Altera se a encontrares. :-P

On 14-03-2016 11:06, Daniel Bicho wrote:
> Na página sobre.arquivo.pt - Noticias ma comunicação social o link
> (http://sobre.arquivo.pt/sobre/publicacoes-1/publicacoes)
> 
>   * Alex da Silveira, Preservação da Web - Análise do Arquivo da Web
>     Portuguesa, Bibliotecno, 26 de Fevereiro de 2010 (jpg,pdf)
> 
> Já está não está válido, sugiro a alteração para a versão arquivada?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arquivo/pwa-technologies/issues/186>.
> 

-- 
Daniel Gomes
Gestor do Arquivo.pt, Área de Serviços Avançados
Head of Arquivo.pt - the Portuguese Web Archive, Advanced Services
Department

Fundação para Ciência e a Tecnologia
Unidade FCCN - Computação Científica Nacional
Av. do Brasil, 101, 1700-066 Lisboa, Portugal
T: [+351] 300 005 190
daniel.gomes@fccn.pt   |   www.fccn.pt

**Comment by dcgomes** [comment]
Not found.
