### ISSUE TITLE
Self Redirects when replaying some Web Pages

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#189]
This is one problem that often occurs in Arquivo.pt.
Here is an example http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
Here are the redirects that occured (used the tool http://www.redirect-checker.org/)
http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
302 Found
http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
302 Found
http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
302 Found
http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
302 Found
http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
302 Found
http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
302 Found
http://arquivo.pt/wayback/20140528220946/http://www.jn.pt/
302 Found ... (until browser prevents the page from continuing)

**Comment by Fernando-Melo** [comment]
Here is the entry of the ARC file (as you can observe there was a redirect from the website without www (jn.pt) to the website with wwww (www.jn.pt)

http://jn.pt/ 80.251.169.146 20140724155446 text/html 368
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.6.0
Date: Thu, 24 Jul 2014 15:54:46 GMT
Content-Type: text/html
Content-Length: 160
Connection: close
Location: http://www.jn.pt/

**Comment by Fernando-Melo** [comment]
We think that these redirects occur because both the opensearch query parameters (exacturl and exacturlexpand) used to search for the closest version of a given URL, consider that a page with the WWW is the same that a page without the WWW

**Comment by dcgomes** [comment]
Examples of self-redirects for testing using PyWB:
- Search: dados-cientificos.pt
- Self-redirect: http://p27.arquivo.pt/pywb/replay/20140925145532/http://www.dados-cientificos.pt/

**Comment by Fernando-Melo** [comment]
So far we have found out that:
1) PyWb mitigates number of self redirects, if the version is doing self redirects it reproduces the next closest version to that date;
2) By applying the quick fix of always listing all versions in OpenSearch (instead of only the closest version per collection), we are mitigating the risc of self redirects, and avoiding large temporal gaps such as the one that is occurring with the jn.pt example.

The disadvantage is that this solution slows down the performance when replaying archived Web pages

**Comment by Fernando-Melo** [comment]
Fixed with the adoption of CDX indexes
