### ISSUE TITLE
Page does not appear in URL search results but it is archived

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#192]
URL Search: http://tvnet.pt/noticias/detalhes.php?id=29669

Not results found both in:
- PyWB: http://p27.arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Ftvnet.pt%2Fnoticias%2Fdetalhes.php%3Fid%3D29669&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2015

- ArquivoWB: http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Ftvnet.pt%2Fnoticias%2Fdetalhes.php%3Fid%3D29669&btnSubmit=Pesquisar

But it is archived:
http://arquivo.pt/wayback/20081024153055/http://tvnet.pt/noticias/detalhes.php?id=29669

http://p27.arquivo.pt/pywb/replay/20081024153055/http://tvnet.pt/noticias/detalhes.php?id=29669

However it appears on full-text search results:

http://arquivo.pt/search.jsp?l=pt&query=melhor+jogador+%22EURO+2008%22&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2008

On the 3rd result:

"Euro 2008
23 Outubro, 2008 - outras datas
Euro 2008 Infografia Os estádios do Euro Infografia As bolas e as mascotes dos Euros           Jorge Ribeiro Posição: Defesa/médio esquerdo Clube: Boavista Idade: 26 anos (9/11/1981 ... foi aproveitado. Apesar de jogar como médio (ou até como defesa), é o melhor marcador do Boavista com ... http://euro2008.publico.clix.pt/jogador.aspx?id=1329584

Euro 2008
23 Outubro, 2008 - outras datas
Euro 2008 Infografia As bolas e as mascotes dos Euros Infografia Os estádios do Euro ... ) Internacionalizações: 60 Golos: 14 Presenças em fases finais: Euro 2004, Mundial 2006 Boa – não espectacular, mas boa - temporada em Espanha de Simão, o terceiro melhor marcador do Atlético de Madrid (dez golos ... http://euro2008.publico.clix.pt/jogador.aspx?id=1329579

TVNET - Xavi eleito o melhor jogador do Euro 2008
24 Outubro, 2008 - outras datas
TVNET - Xavi eleito o melhor jogador do Euro 2008 Sexta, 24 de Outubro de 2008 Todas Notícias ...                  Xavi eleito o melhor jogador do Euro 2008 O espanhol Xavi encabeça a lista dos 23 melhores jogadores ... o melhor jogador da Euro 2008, encabeçando a lista dos 23 melhores jogadores do torneio, conquistado ... http://tvnet.pt/noticias/detalhes.php?id=29669 "

**Comment by Fernando-Melo** [comment]
I think this is a bug in the search.jsp that is interpreting the question mark (?).
For instance if you search for the expression with the url, you get the expected result.

http://arquivo.pt/search.jsp?l=pt&query=%22http%3A%2F%2Ftvnet.pt%2Fnoticias%2Fdetalhes.php%3Fid%3D29669%22&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2015
