### ISSUE TITLE
Change News items on footer

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#193]
Change News items on footer of www.arquivo.pt and sobre.arquivo.pt.

The items list and corresponding links under News should be:

## EN:

News

Subscribe mailing list -> https://groups.google.com/forum/#!forum/divulgarquivopt/join
Twitter: NO CHANGE
Facebook: NO CHANGE
Latest news: NO CHANGE
Videos-> http://sobre.arquivo.pt/about-the-archive/publications-1/publications?set_language=en#section-3

## PT

Subsescrever lista de email -> https://groups.google.com/forum/#!forum/divulgarquivopt/join
Twitter: NO CHANGE
Facebook: NO CHANGE
Últimas novidades: NO CHANGE
Videos-> http://sobre.arquivo.pt/sobre/publicacoes-1/publicacoes?set_language=pt#section-3

**Comment by FCCNhviana** [comment]
Footer changed.
