### ISSUE TITLE
Create The PyWb Error Page

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#200]
We should define the Web page for when a PyWb error occurs (this is different from the ResourceNotFound error page). 

For development and pre-production we have the default error page that outputs the PyWb stack trace.
We should create a specific page for production.
How should this page be @dcgomes ?

**Comment by dcgomes** [comment]
Can use this default message:

"Não conseguimos encontrar a página
O nosso arquivo voltou atrás no tempo mas não encontrou a página que pediu.
Poderá:

Avisar-nos do problema
Voltar à página inicial
Ver como pode contribuir na preservação da Web portuguesa"

http://p41.arquivo.pt/kjhjkhkjh
