### ISSUE TITLE
Add "Details" feature at Replay bar to display meta-data about preserved page

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#204]
On the Replay bar, probably next to the URL, we could had a "Details" function that on-click would display existing meta-data about preserved page in human-readable format.

For example:
- page title
- provenance (crawl id)
- file size
- media type
- other relevant information available through OpenSearch

**Comment by Fernando-Melo** [comment]
Display a modal with the info from textsearch - metadata API
e.g. http://arquivo.pt/textsearch?metadata=http%3A%2F%2Fquiz.musicbox.sapo.pt%2F%2F20131108093638&prettyPrint=true

**Comment by dcgomes** [comment]
Put underline on all fields that are links (e.g. originalURL, linkToArchive) of the Details page, including link to "field description" on th header.

**Comment by Fernando-Melo** [comment]
Added text-decoration:underline to all anchors in the metadata modal
