### ISSUE TITLE
Screenshot did not work

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#209]
The Screenshot feature did not work for the following versions:

http://arquivo.pt/wayback/20150108053852/http://observador.pt/2015/01/07/especialistas-falam-em-ataque-muito-profissional-e-terroristas-com-treino-militar/

http://arquivo.pt/wayback/20150107184157/http://www.tvi24.iol.pt/internacional/tiroteio/quem-sao-os-jornalistas-mortos-no-ataque-ao-charlie-hebdo

http://arquivo.pt/wayback/20150508175906/http://www.jornaldoalgarve.pt/abatido-lider-da-al-qaeda-que-reivindicou-ataque-ao-charlie-hebdo/

**Comment by Fernando-Melo** [comment]
It worked for me in all the 3 links above. Can you please try again?

**Comment by dcgomes** [comment]
Cannot reproduce.
