### ISSUE TITLE
The Print feature did not work

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#210]
The Print feature did not work for the following version:

http://arquivo.pt/wayback/20150107184157/http://www.tvi24.iol.pt/internacional/tiroteio/quem-sao-os-jornalistas-mortos-no-ataque-ao-charlie-hebdo

**Comment by Fernando-Melo** [comment]
It worked for me. Can you please try again?

**Comment by dcgomes** [comment]
Cannot reproduce.
