### ISSUE TITLE
The full original URL of the archive page must be available even if it is a long string

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#211]
The full original URL of the archive page must be available even if it is a long string. 

For instance:
http://arquivo.pt/wayback/20141201082217/http://www.contrelislam.eu/necessite_reforme_islam.php

The users cannot obtained the original URL through the UI, for instance to include on a citation.

We should:
- show full URL on mouse-ouver and click on the URL displayed on the top bar. The users must be able to copy this full URL string.
- increase number of initially displayed chars.

**Comment by Fernando-Melo** [comment]
What should be the max number of characters?
