### ISSUE TITLE
Versions drill down on the left appears empty

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#213]
The Versions Drill Down bar on the left appears empty, without presenting any version.

However, it is displayed one version of 20150106184813:
http://arquivo.pt/wayback/20150106184813/http://www.rtp.pt/noticias/index.php

The Versions Table also appears empty:
http://arquivo.pt/search.jsp?l=pt&query=http://www.rtp.pt/noticias/index.php&btnSubmit=Pesquisar

**Comment by Fernando-Melo** [comment]
On my computer both links appear to be working. Can you try again and see if the problem remains?

**Comment by Fernando-Melo** [comment]
It is a problem that often occurs in more instable networks.
I've just made a quick-fix in p27. 
Now it retries to get the list of versions in the left menu 3 times.
I've tried to simulate 3g and 4g networks in google chrome, and this simple solution fixes the problem most of the times.
