### ISSUE TITLE
Fix/replace footer links on Arquivo.pt and sobre.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#228]
PT version:
- "Serviços e código-aberto" -> "Código-aberto & APIs" (link to https://github.com/arquivo/pwa-technologies/wiki)
- "Subsescrever lista de email" -> "Subscrever lista de email"
- "Videos" -> "Vídeos" (link to: http://sobre.arquivo.pt/sobre/publicacoes-1/publicacoes?set_language=pt#section-4)
- "Sugira para arquivo" -> "Sugira site"
- "Divulgue o Arquivo.pt" -> "Material de divulgação" (link to: http://sobre.arquivo.pt/sobre/area-de-imprensa/material-de-comunicacao/material-de-divulgacao)

EN version:
- Publications -> link to: http://sobre.arquivo.pt/about-the-archive/publications-1
- Videos -> link to: http://sobre.arquivo.pt/about-the-archive/publications-1/publications?set_language=en#section-4
- "Disseminate Arquivo.pt" -> "Dissemination materials" link to: http://sobre.arquivo.pt/about-the-archive/press/dissemination-materials
- "Research & Development" -> link to: http://sobre.arquivo.pt/collaborate/research-and-development-activities-1

Then reproduce footer on Plone (sobre.arquivo.pt)

**Comment by Fernando-Melo** [comment]
The footer and respective constants in p27 are outdated. I need to do a merge between the version of p27 and the one in the github before updating links.
