### ISSUE TITLE
Text on snippet does not appear on archived page

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#229]
Search for: "i23169"

http://arquivo.pt/search.jsp?l=pt&query=i23169&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2015

The snippet on the SERP presents the string "i23169":

Index of /images/alunos
10 Julho, 1997 - Tabela de versões
i23125.gif 14-Dec-96 16:15 17K i23168.gif 14-Dec-96 16:15 11K i23169.gif 14-Dec-96 16:15 16K jcrp.gif 19

However, the archived page does contain the string "i23169":
http://arquivo.pt/wayback/19961127024305/http://caravela.di.fc.ul.pt/images/alunos

It seems it is a problem related to redirects since the result on the SERP is:
http://arquivo.pt/wayback/19970710230814/http://caravela.di.fc.ul.pt/images/alunos/
But the presented archived page is:
http://arquivo.pt/wayback/19961127024305/http://caravela.di.fc.ul.pt/images/alunos
Which as different date and presents a "/" at the end.

At least we have archived one URL with the string "i23169" that should also be presented on the search results:
http://arquivo.pt/wayback/19970710201009/http://caravela.di.fc.ul.pt/images/alunos/i23169.gif

Other results also link to the wrong version:
http://arquivo.pt/search.jsp?query=http%3A%2F%2Fcaravela.di.fc.ul.pt%2Fimages%2Falunos%2Fimages%2F..&dateStart=01/01/1996&dateEnd=31/12/2015&pos=1

When click on:
http://arquivo.pt/wayback/19961201132229/http://caravela.di.fc.ul.pt/images/alunos/
http://arquivo.pt/wayback/19970710230814/http://caravela.di.fc.ul.pt/images/alunos/

The users go to:
http://arquivo.pt/wayback/19961127024305/http://caravela.di.fc.ul.pt/images/alunos

**Comment by Fernando-Melo** [comment]
There is an archived record for the url http://caravela.di.fc.ul.pt/images/alunos/images/..     in 1997

Notice the relative path ( the .. at the end).

**Comment by Fernando-Melo** [comment]
So if you search for that relative path you will see that there are 2 archived  versions for that url both in 1996 and 1997 

http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fcaravela.di.fc.ul.pt%2Fimages%2Falunos%2Fimages%2F..&btnSubmit=Pesquisar

**Comment by Fernando-Melo** [comment]
But if we interpret the relative path, the path now becomes:
 http://caravela.di.fc.ul.pt/images/alunos/

So if we search for this URL we can observe that there is only one version in 1996

http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fcaravela.di.fc.ul.pt%2Fimages%2Falunos%2F&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2015

**Comment by Fernando-Melo** [comment]
So the problem is that browsers will also interpret the URL. If I try to insert the URL:

http://arquivo.pt/wayback/19961127024305/http://caravela.di.fc.ul.pt/images/alunos/images/.. 

the browser will translate that URL to:
http://arquivo.pt/wayback/19961127024305/http://caravela.di.fc.ul.pt/images/alunos/

And with that URL we only have 1 archived version as I showed in the above post
