### ISSUE TITLE
Remove left 0 on days lower than 10

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#230]
On the Table of Versions:
http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fcaravela.di.fc.ul.pt&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2015

The left 0 on the days lower than 10 are unnecessary and burden the users with unnecessary congnitive processing. 

For example, instead of "01 Mar" it should be "1 Mar"

**Comment by Fernando-Melo** [comment]
Fixed in p27
