### ISSUE TITLE
Try Malihu Scrollbar Plugin

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#238]
Try using Malihu Scrollbar plugin, to replace default scrollbar on the left menu of the ReplayBar page.

http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/scrollbar_themes_demo.html

**Comment by dcgomes** [comment]
Replace default toolbars is an usability/compatibility nightmare. Will not spend resources on this.

https://www.nngroup.com/articles/scrolling-and-scrollbars/
http://baymard.com/blog/inline-scroll-areas
http://ux.stackexchange.com/questions/33384/accessible-custom-scrollbars
