### ISSUE TITLE
Update Arquivo.pt footer

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#242]
The url: http://www.portugal.gov.pt/pt/os-ministerios/ministerio-da-educacao-e-ciencia.aspx
no longer exists, so we need to update the government footer in arquivo.pt and in sobre.arquivo.pt.

Luckily Arquivo.pt preserved the previous link for future reference :) 
http://arquivo.pt/wayback/20141015185132/http://www.portugal.gov.pt/pt/os-ministerios/ministerio-da-educacao-e-ciencia.aspx

**Comment by dcgomes** [comment]
Replace footer link "Facebook":
https://www.facebook.com/ArquivoWebPortuguesa

by:
https://www.facebook.com/Arquivo.pt/

**Comment by Fernando-Melo** [comment]
New footer in p27.
