### ISSUE TITLE
Bad Replay Quality with observador.pt

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#245]
The observador.pt website at 2015 have a poor replay quality. This is not a robots.txt problem and this websites is being harvested daily. http://arquivo.pt/wayback/20150419012300/http://observador.pt/

Some web archived versions are good http://arquivo.pt/wayback/20150511170208/http://observador.pt/, but most of them are bad.

This need be verified and check if the problem spreads to other daily harvested seeds.

**Comment by arquivo** [comment]
The problem spreads to daily harvests. The website uses a lot of other hosts, that were identified. But the biggest problem is that Heritrix-1.14 is not extracting from the HTML tag attributes like data-* (ex: data-src). This is a very severe problem, because a lot of websites today use those attributes.

Need further testing to check if more recent Heritrix version handle those URLs.

**Comment by danielbicho** [comment]
The problem spreads to daily harvests. The website uses a lot of other hosts, that were identified. But the biggest problem is that Heritrix-1.14 is not extracting from the HTML tag attributes like data-* (ex: data-src). This is a very severe problem, because a lot of websites today use those attributes.

Need further testing to check if more recent Heritrix version handle those URLs.

**Comment by danielbicho** [comment]
Verify, this should be a lot better with H3, checkAlsoVia parameter and explicit robots policy.

**Comment by danielbicho** [comment]
Create a sheet at h3 to increase some current configuration limits for observador.pt

2018-10-30T11:07:20.087Z 7 TooManyPathSegmentsDecideRule REJECT https://wmcdn.observador.pt/wm/obs/l/https://imageproxy-observadorontime.netdna-ssl.com/770x403,q80/https://s3cdn-observadorontime.netdna-ssl.com/wp-content/uploads/2018/07/03114419/10375605_770x433_acf_cropped.jpg

2018-10-30T00:30:31.306Z 2 TooManyHopsDecideRule REJECT https://s3cdn-observadorontime.netdna-ssl.com/wp-content/uploads/2018/06/24025903/24405341_1280x720_acf_cropped.jpg

2018-10-29T23:54:36.369Z 0 RejectDecideRule REJECT https://s3cdn-observadorontime.netdna-ssl.com/favicon.ico

**Comment by danielbicho** [comment]
Brozzler has also trouble to get the images. Patching is the only way to solve this currently.

**Comment by igobranco** [comment]
> Brozzler has also trouble to get the images. Patching is the only way to solve this currently.

@danielbicho couldn't we do a continuous patching of its homepage on preprod environment? When the FAWP is updated weekly/daily on preprod environment?

**Comment by danielbicho** [comment]
@igobranco I think that is a good step to increase the overall quality of the archived resources, well at least the homepage.

**Comment by dcgomes** [comment]
Check if 2020 crawls (FAWPs) with Brozzler crawls on the first day of the month are better.

**Comment by ricardobasiliopt** [comment]
The replay improved. The lacking of images happens sometimes, but can be solved with patching
<img width="960" alt="print_observador_04" src="https://user-images.githubusercontent.com/44206545/111626846-5ac4b200-87e6-11eb-950c-91dc47284326.png">
<img width="943" alt="print_observador_05" src="https://user-images.githubusercontent.com/44206545/111626892-62845680-87e6-11eb-93fe-d0ec9993fd40.png">
