### ISSUE TITLE
[OpenSearch & search.jsp] Search with "site:" operator  with date other than default gives wrong results

### ISSUE THREAD

**Issue by jnobre** [arquivo/pwa-technologies#249]
### Expected behavior
Search with the "site:" search operator within a defined period of time and return results within the period chosen by the user

### Actual behavior
Searching with the "site:" search operator in a defined time period does not return results or returns the wrong results.

### Steps to reproduce the behavior
Search for terms with the "site:" operator, in a chosen time period other than the default
Example
- Search for [2001 "Vasco Matos Trigo" site:programas.rtp.pt] between 01/01/2006 and 01/12/2012.

Error occurs in **search.jsp** and in **opensearch**

**Review the tests** to catch these types of errors

**Comment by Fernando-Melo** [comment]
Reactivate the method searchURL() in the AdvancedTest class in the functional-tests project after fixing this issue

**Comment by jnobre** [comment]
Understand why not search for subdomain search terms.

**Comment by jnobre** [comment]
I added an assert (checkOPSite) to the AdvancedPage test, to verify the "site:" operator.
