### ISSUE TITLE
arquivo.pt responds with 502 - Bad request, for specific searches

### ISSUE THREAD

**Issue by jnobre** [arquivo/pwa-technologies#250]
### Expected behavior
Search for "_protocolo de coprodução portugal brasil instituto cinema_" and _arquivo.pt_ respond with documents found

### Actual behavior
Arquivo.pt response: **502 - Bad Gateway** 

### Steps to reproduce the behavior
Access the full-text of the arquivo.pt and search for "_protocolo de coprodução portugal brasil instituto cinema_"

**Review the tests** to catch these types of errors

**Comment by jnobre** [comment]
The response time for searching in the AWP19 collection takes a long time to return. If we increase the response timeout for this collection, it returns 0 results.
The collection has 7.1 TB of disk size and 2.1 size of indexes.
It seems to me that the problem is not only in this collection, but in the worst case of the search algorithm: for large collections to search many terms without any result.

**Comment by jnobre** [comment]
Neext Steps:
1. Check if timeout is per collection.
2. Check if there is a problem with the AWP19 collection.

**Comment by dcgomes** [comment]
Another example for testing:
http://arquivo.pt/search.jsp?l=pt&query=%22Os+inc%C3%AAndios+e+a+desertifica%C3%A7%C3%A3o+de+Portugal+florestal%22%2C&btnSubmit=Pesquisar

Check if the origin of the problem is also AWP19?

**Comment by dcgomes** [comment]
Another example for testing:
http://arquivo.pt/search.jsp?l=pt&query=tempo+4+de+julho+de+2012&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2003

**Comment by jnobre** [comment]
Issue resolved by implementing a timeout in the **hadoop-common** project and a **timer** on multiple queries to the queryServer.

Files changed:

- hadoop-common/conf/**hadoop-default.xml**
- PwaArchive-access/projects/nutchwax/nutchwax-thirdparty/nutch/src/java/org/apache/nutch/searcher/**DistributedSearch.java**
- PwaArchive-access/projects/nutchwax/nutchwax-thirdparty/nutch/src/java/org/apache/nutch/searcher/**NutchBean.java**

Sent to preprod for the **test phase**.
