### ISSUE TITLE
Versão base do Wordpress e plugins utilizados

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#253]
Criar documento com detalhes sobre versão do Wordpress, lista de plugins utilizados e respetivos licenciamentos

**Comment by dcgomes** [comment]
Põe no Wiki.

**Comment by Fernando-Melo** [comment]
Pus uma primeira versão no google docs do AWP https://docs.google.com/spreadsheets/d/16IdlN-V9OIPxUv2B-_iT02JlwIgbr8hQKg1kyn0vrRs . Depois quando tivermos uma versão mais definitiva posso pôr na nossa Wiki também.

**Comment by Fernando-Melo** [comment]
Adicionar link da wiki para o documento
