### ISSUE TITLE
Segurança contra pirataria informática e comunicações não solicitadas (spam)

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#259]
Segurança contra pirataria informática e comunicações não solicitadas (spam). A
título de exemplo, todos os endereços e comunicações através de correio eletrónico
deverão apresentar mecanismos de proteção, e deverão ser garantidos mecanismos
de ofuscação de endereços de correio eletrónico em código fonte;

**Comment by dcgomes** [comment]
Captcha is enough.
