### ISSUE TITLE
add new examples of archived pages

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#26]
Originally reported on Google Code with ID 27
```
Check examples at:
http://wiki.priv.fccn.pt/P%C3%A1ginas_de_exemplo_no_arquivo.pt

And add new ones to the highlights page at:

http://www.arquivo.pt/highlights.jsp?l=pt

Maintain the same examples at the PT and EN version.
```

Reported by `danielcoelhogomes` on 2012-02-20 10:20:20

**Comment by dcgomes** [comment]
Done at http://sobre.arquivo.pt/about-the-archive/example-pages-in-the-portuguese-web-archive?set_language=en.
