### ISSUE TITLE
link to other services

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#27]
Originally reported on Google Code with ID 28
```
The PWA should refer other services provided by FCCN in the footer. For instance, it
can link to a page describing all the other services. The other services should do
the same to redirect users between services.

```

Reported by `migcosta` on 2012-02-22 12:21:20

**Comment by Fernando-Melo** [comment]
Is the idea to add a link to all the services of FCCN such as https://www.fccn.pt/pt/servicos/ ?
Should we do it or close this issue?

**Comment by dcgomes** [comment]
Close, this is not relevant to improve the service quality.
