### ISSUE TITLE
Temporal span replaying archived pages

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#273]
Add a maximum temporal span when replaying an archived web page.
When replaying a Web page, one should only load resources up to 1 month before and after the requested timestamp.

**Comment by danielbicho** [comment]
Exemplo site FCT, 1998

**Comment by Fernando-Melo** [comment]
Not implemented, it would have to be done by the author of pywb Ilya Kreymer.

**Comment by dcgomes** [comment]
"up to 1 month before and after the requested timestamp."
It hard to decide the "magical number" for an adequate time span. 1 month sounds OK for daily crawls but it is to close for older collections from the 90s for which there is very limited information along time.

**Comment by danielbicho** [comment]
With the patching feature a lot of content drift probably will be created and the only easy way to understand what is happening would be an advanced option where the user specify an requests time stamp.
