### ISSUE TITLE
Accessibility level A WCAG 2.0

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#275]
Enhance accessibility in arquivo.pt, attempt to obtain level A in WCAG 2.0 validator.

**Comment by Fernando-Melo** [comment]
Test with real people instead of the validator.

**Comment by Fernando-Melo** [comment]
Maybe delay the accessibility validation to a future release

**Comment by pcabritafccn** [comment]
Accessibility check in progress. Will close this issue as soon as the AL will be acceptable.

**Comment by vitgou** [comment]
Acessibility check is now part of the deploy process.
