### ISSUE TITLE
Analyze the impact of the "Sobre.arquivo.pt" links on the homepage

### ISSUE THREAD

**Issue by jnobre** [arquivo/pwa-technologies#280]
Analyze in the logs (google analytics / awstats) the behavior of the users in relation to the links of "Sobre.arquivo.pt".

**Comment by jnobre** [comment]
The google analytics script has been added on the main page to review the clicks on the link to the "Sobre.arquivo.pt"

**Comment by igobranco** [comment]
Won't do.
