### ISSUE TITLE
Arquivo.pt search box bug

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#295]
Arquivo.pt search box don't display correctly the last words written when query exceeds the search box size.

To reproduce the problem:
1. Go to http://arquivo.pt
2. Write a long query until it overflow the search box size.

Notice that the last written chars are not displayed.

**Comment by Fernando-Melo** [comment]
cannot reproduce @danielbicho

**Comment by danielbicho** [comment]
This problem does not exist anymore closing
