### ISSUE TITLE
Problem with encoding in the spellchecker when using internet explorer.

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#30]
Originally reported on Google Code with ID 31

```
What steps will reproduce the problem?
1. Open IE and arquivo.pt and type: recuperação do chiado
2. The Spellchecker returns, and it shouldn't.
3. The Spellchecker also returns with encoding problems:"recupera��o do chiado"

What is the expected output? What do you see instead?
The spellchecker shouldn't return at all.

Note:
The versions of spellchecker and configurations where confirmed and are correct.

Please use labels and text to provide additional information.


```

Reported by `simaofontes` on 2012-03-28 14:47:15

**Comment by dcgomes** [comment]
@FCCNhviana verify if you can replicate the problem?
If not, close.

**Comment by dcgomes** [comment]
Try with Windows 10. Only 8.59% of our users have IE.

**Comment by dcgomes** [comment]
Problem still happens on Internet Explorer v.11.0.9600.18349IS
Windows 7

**Comment by Fernando-Melo** [comment]
Fixed in preprod.
Todo: add a regression test in saucelabs.

**Comment by jnobre** [comment]
Added a regression test in [functional-tests](https://github.com/arquivo/functional-tests): SpellcheckerTest.java.
