### ISSUE TITLE
broken link on Suggest site for archive

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#315]
http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Flopezio.blogspot.pt&btnSubmit=Pesquisar

If we click on the link "Sugira":

"Não foram encontrados resultados para a sua pesquisa:
http://lopezio.blogspot.pt
Sugerimos que:
Verifique o URL
Sugira a página para que seja arquivada.
Pesquise noutros arquivos."

We get a broken link to:
http://sobre.arquivo.pt/colaboracoes/sugerir-um-sitio?endereco-a-sugerir=http://lopezio.blogspot.pt

Fix link or put a redirect to the new URL on Wordpress.

Fix also for English version.

**Comment by Fernando-Melo** [comment]
fixed in p27
