### ISSUE TITLE
Back Page button mislead results

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#320]
At Arquivo.pt search for sapo.pt. It will display the table versions for sapo.pt websites.
Now perform another query for iscte-iul.pt, it will display the table versions for iscte-iul.pt websites.

If press back page button it will display the results for sapo.pt but it will say that is for iscte-iu.pt misleading the user.
The same behavior occurs for full text search.

**Comment by Fernando-Melo** [comment]
Add attribute `autocomplete="off"` to the search text form. Modern browsers attempt to fill forms with previous values when clicking in the back button, the proposed solution fixes this problem.

**Comment by Fernando-Melo** [comment]
already added
