### ISSUE TITLE
Leak to live web publico.pt 2016 versions

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#325]
The 2016 versions of publico.pt are leaking to live web.

The archived versions is somehow redirected and the publico.pt live web site is placed inside the iframe.

http://arquivo.pt/wayback/20160516125808/https://www.publico.pt/ compare with the live version http://www.publico.pt/

It is really misleading

**Comment by Fernando-Melo** [comment]
Fixed

**Comment by Fernando-Melo** [comment]
Fixed with pywb 2
