### ISSUE TITLE
fix message "1 versões de http://remediospierce.ifrance.com/straight-edge.html"

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#326]
On:
http://arquivo.pt/search.jsp?l=pt&query=http://remediospierce.ifrance.com/straight-edge.html&btnSubmit=Pesquisar

It is displayed: "1 versões de http://remediospierce.ifrance.com/straight-edge.html"

It should be:
"1 versão de http://remediospierce.ifrance.com/straight-edge.html"

Or to simplify:

"Número de versões de $URL: $NUMBER"

**Comment by Fernando-Melo** [comment]
fixed in p27
