### ISSUE TITLE
Search box, in chrome, while pasting text, text goes up some px

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#33]
Originally reported on Google Code with ID 34
```
What steps will reproduce the problem?
1. Open arquivo.pt Google Chrome in windows or Chromium in Linux
2. Paste a string in searchbox

What is the expected output? What do you see instead?
The result of pasting the text, the text should be in the same position.
The output that occurs  is the text goes up some px.

Added 2 images for diagnosis.
```

Reported by `simaofontes` on 2012-06-25 10:53:59

<hr>
 * *Attachment: Screenshot at 2012-06-25 11:52:15.png<br>![Screenshot at 2012-06-25 11:52:15.png](https://storage.googleapis.com/google-code-attachments/pwa-technologies/issue-34/comment-0/Screenshot at 2012-06-25 11:52:15.png)*
 * *Attachment: Screenshot at 2012-06-25 11:52:33.png<br>![Screenshot at 2012-06-25 11:52:33.png](https://storage.googleapis.com/google-code-attachments/pwa-technologies/issue-34/comment-0/Screenshot at 2012-06-25 11:52:33.png)*

**Comment by Fernando-Melo** [comment]
Cannot reproduce the error. Tested on chrome 46.0.2490.86 
Close or test in several previous versions of chrome?
