### ISSUE TITLE
Wrong Title in some pdfs wordpress

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#337]
http://sobre.arquivo.pt/pt/pesquisar/?q=preserva%C3%A7%C3%A3o+web

Fix all the pdfs with wrong Title

**Comment by Fernando-Melo** [comment]
Find all the pdfs uploaded in https://sobre.arquivo.pt check the title, if it is not correct update it and reupload them.

**Comment by dcgomes** [comment]
Wont fix. Too much work.
