### ISSUE TITLE
Wordpress page shortlink near page title

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#363]
Change css layout so that page shortlink appears near the page title

**Comment by Fernando-Melo** [comment]
E.g.
https://arquivo.pt/sugerir redirects to https://sobre.arquivo.pt/pt/colabore/sugerir/

in the sobre page https://sobre.arquivo.pt/pt/colabore/sugerir/ near the page title show the shortlink i.e. https://arquivo.pt/sugerir

**Comment by dcgomes** [comment]
Won't do. Add short links within body text when necessary.

**Comment by dcgomes** [comment]
See: https://sobre.arquivo.pt/pt/colabore/sugerir/
