### ISSUE TITLE
Improve image thumbnails

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#367]
There are some image thumbnails too large (e.g. 912px by 80px)
Most of them are just banners from websites.

Possible solutions:
 - Give a very low ranking to those cases
-  Crop images in thumbnails
- Ignore image ratio and force those images to have max-width of 400px
- Remove those images from the results

**Comment by amourao** [comment]
https://preprod.arquivo.pt/images.jsp?l=pt&size=all&type=&tools=off&safeSearch=on&query=collection%3ATomba&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2019

It seems some thumbnails are being generated with incorrect colors.
This particular example seems to be of a PNG image with a JPEG mimetype and extension.

![image](https://user-images.githubusercontent.com/2866295/73285013-4a6e0400-41ed-11ea-92e9-a9e5bd2f6d15.png)

**Comment by amourao** [comment]
Issue is possibly related to #729

**Comment by amourao** [comment]
The thumbnails will be revamped to a different SOLR index, and this should be addressed there
