### ISSUE TITLE
Archived pages try to load resources from live Web before archived resources

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#37]
Originally reported on Google Code with ID 38
```
When a page is loaded, the original contents are loaded from the original servers (for
instance, images) and only then the javascript functions rewrite the links to display
the archived embedded contents.
This originates a load of calls to the servers where the contents were originally located,
producing a burst of 404 and 3XX Status Codes in the original hosts.

This may:
- present additional load to the servers by doing a GET request for every resource
in the page that may be long gone. For big pages and popular pages, this could to a
huge number of HTTP GET request of old/inexistent resources.
- lead to a flash of still existing content that wasn't retrieved by the Web Archive,
confusing the users.
- if there are newer version of resources (e.g., images) for a given URL, a newer version
of the resource can flash before being replaced by the archived older version.

I attached a report from WebPageTest that details the requests done for the archived
version of 20 jan 2011 from www.fccn.pt (http://arquivo.pt/wayback/wayback/20110120234828/http://fccn.pt/index.php?module=pagemaster&PAGE_user_op=view_page&PAGE_id=430&MMN_position=230:4:229

Example of file to look at: "b-on.gif":
1) GET b-on.gif in live Web / Got 302
2) GET b-on.gif in live Web / Got 404
3) GET b-on.gif in Web Archive / Got 302
4) GET b-on.gif in Web ARchive / Got 200
```

Reported by `whispsil` on 2012-07-30 16:00:51

<hr>
 * *Attachment: [webtest-www.fccn.pt.pdf](https://storage.googleapis.com/google-code-attachments/pwa-technologies/issue-38/comment-0/webtest-www.fccn.pt.pdf)*

**Comment by danielbicho** [comment]
In Wayback configuration is possible  to change the rewrite behavior to Server Rewrite ONLY. This is the recommended setup for Wayback:

`Currently, we are recommending the entirely server-side rewriting method, and are deprecating the original server-side plus Javascript method, but this functionality is still available in Wayback. Neither method is perfect, not all URLs are rewritten correctly, particularly URLs that are created by JavaScript in the original pages, and specialized file types containing links like Flash and PDF documents.`

In p41.arquivo.pt, server rewriting is enabled for test purposes. Below the configuration change:

`
        <property name="replay">
            <bean class="org.archive.wayback.archivalurl.ArchivalUrlReplayDispatcher">
                <property name="serverSideRendering" value="true" />
                <property name="jspInserts">
                    <list>
                        <value>/replay/ArchiveComment.jsp</value>

                        <value>/replay/Disclaimer.jsp</value>
                        <value>/replay/analytics.jsp</value>
                    </list>
                </property>
            </bean>
        </property>
`

**Comment by Fernando-Melo** [comment]
Fixed with Pywb
