### ISSUE TITLE
Improve Image Viewer UI

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#373]
![image](https://user-images.githubusercontent.com/13658607/33715276-e352df18-db49-11e7-9523-e73648352f9e.png)

- Remove blinking when navigating to the next and previous images
- Improve buttons style
- Allow arrows to navigate to the next and previous images
- Always show image viewer in a fixed position (for now the image viewers changes position when viewing a new line of images).

**Comment by Fernando-Melo** [comment]
Maybe this issue should not be done if we decide to expand the mobile version and discard the desktop one

**Comment by amourao** [comment]
Closed, as the Desktop UI is being depreciated and this is being done as a part of the Mobile UI.
