### ISSUE TITLE
Add near-text-above and near-text-below attributes to Image Search Indexes

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#374]
The surrounding text near an image may contain important information regarding the image (e.g. sometimes it is a brief descritpion, others a caption). 
Add **near-text-above** and **near-text-below** attributes to Image Search Indexes.
Define the maximum number of words each attribute should have.

**Comment by amourao** [comment]
After discussing this with @dcgomes, we are considering examining top 50 words / top 10% in HTML documents, measured by TF, TF/IDF or an equivalent metric.

**Comment by amourao** [comment]
Added above, below text in https://github.com/arquivo/image-search-indexing/commit/bc636413f59995439a7c15c791bcda987593643e
