### ISSUE TITLE
Show the end of the URL of the search results

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#38]
Originally reported on Google Code with ID 39
```
When URL of the search results are too long, URLs are shortened. However, the current
shortening cuts the last part of the URL thus removing information such as the destination
page and extension (e.g., ".html") that is crucial for users' decision process.

Steps to reproduce the problem:
1. Go to "http://arquivo.pt/"
2. Search for "http://www.footballportugal.com.pt/ winner final euro 2004"
3. Observe the URL os the search results.

What is the expected output?
Something along the line of: 
http://www.footballportugal.com.pt/_euro_2004_/.../euro_2004_-_fixtures.html

What do you see instead?
http://www.footballportugal.com.pt/_euro_2004_/euro_2004_-_fixtures/euro_2004...


For a visual example, see the attached image.

```

Reported by `whispsil` on 2012-07-30 17:56:43

<hr>
 * *Attachment: issue-39.png<br>![issue-39.png](https://storage.googleapis.com/google-code-attachments/pwa-technologies/issue-39/comment-0/issue-39.png)*

**Comment by Fernando-Melo** [comment]
@dcgomes what have we decided about this?
The length of the display of the url is 80 characters.
Do you want me to change the way to display an URL to show the first 40 characters  + ... + the last 37 characters when the url is longer than 80 characters ?

**Comment by Fernando-Melo** [comment]
done in p27
