### ISSUE TITLE
Index field lucene collection with name in uppercase.

### ISSUE THREAD

**Issue by jnobre** [arquivo/pwa-technologies#389]
The Lucene index **collection** field is being entered with the uppercase characters.

Lucene query uses the standard for query analysis, which in turn uses LowerCaseFilter which means it lowercases your queries and data.

Therefore, a query through the collection returns no value.

**Comment by Fernando-Melo** [comment]
collection parameter is returned incorrectly in the first example
http://arquivo.pt/textsearch?prettyPrint=true&versionHistory=expresso.pt&maxItems=5
collection parameter is returned empty in the second example
http://arquivo.pt/textsearch?prettyPrint=true&versionHistory=sapo.pt&maxItems=5
