### ISSUE TITLE
Empty content 

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#395]
Search:
http://arquivo.pt/search.jsp?l=pt&query=http://www.tsf.pt/&btnSubmit=Pesquisar

All these versions present blank content:
http://arquivo.pt/wayback/19981212033620/http://www.tsf.pt/
http://arquivo.pt/wayback/19990125092423/http://tsf.pt/
http://arquivo.pt/wayback/19990125104046/http://www.tsf.pt/
http://arquivo.pt/wayback/19990208021031/http://www.tsf.pt/
http://arquivo.pt/wayback/19990422030219/http://www.tsf.pt/

Can't we remove them from the results?

**Comment by Fernando-Melo** [comment]
won't fix
