### ISSUE TITLE
Hostnames with capitalized letters are treated as being different

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#40]
Originally reported on Google Code with ID 41
```
What steps will reproduce the problem?
1. Go the the homepage (http://arquivo.pt/index.jsp?l=en)
2. Search for: http://tumba.pt and submit.
3. The history page for that URL appear.
4. Submit a new query but this time insert: http://tumba.PT
5. An message appear saying: "No results were found for the query:
http://www.tumba.PT"

What is the expected output?
The Web archive should treat capitalized (parts of) hostnames as being the same.

```

Reported by `devel.david@vcruz.net` on 2012-07-31 16:02:58

**Comment by dcgomes** [comment]
Verify if problem persists with PyWB.

**Comment by Fernando-Melo** [comment]
Bug persists using Nutchwax indexes. Bug disappears using CDX indexes

**Comment by FCCNhviana** [comment]
A valid solution could be to set all the parameters of the hostname to lower case and process it as a normal URL.

**Comment by FCCNhviana** [comment]
[Commit reference](https://github.com/arquivo/pwa-technologies/commit/1a25a4cd232512b5cfd04f649cc38a9acd8cc980)

**Comment by FCCNhviana** [comment]
Same as issue #165.
