### ISSUE TITLE
CDX Records with Status Code 400 or other type of errors degrade the Replay Quality

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#402]
Those kind of records should not be used when a archived web page is being replayed.
For instance if a cdx record have these entries:

Even if we have available an archived version of the resource, the replay system will always load the closest one, so the record with 400 BadRequest will always be the one used.

(simplified urls)
`
com,wp,s0)/_static... 2016032413409 {"url": "https://s0.wp.com/_static/....", "mime": "application/x-javascript", "status": "400", "offset": "1075716", "filename": "IAH-2016.warc.gz"}
com,wp,s0)/_static... 20180323143409 {"url": "https://s0.wp.com/_static/....", "mime": "application/x-javascript", "status": "200",  "filename": "jornadas-patching.warc.gz"}
`
For a date near 2016, the bad request will always be the closest and the resource will not be loaded.

Solutions:
1. Delete this kind of record from the cdx index.
2. Modify Pywb to not use these records while replaying (similar to how we handle an Web Page archived versions.)

I don't see any advantage of keeping this kind of records. They could be shown while using the API, like metadata, but for replaying an Web Page they just hurt the replay quality.

**Comment by Fernando-Melo** [comment]
done
