### ISSUE TITLE
File extension misinterpreted as url/tld 

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#41]
Originally reported on Google Code with ID 42
```
For instance, searching for an image:
http://arquivo.pt/search.jsp?query=type%3Ajpeg+mcd102g.jpg&hitsPerPage=10&dateStart=01%2F01%2F1996&dateEnd=01%2F12%2F2009

the ".jpg" extension is misinterpreted as a tld and, therefore, "mcd102g.jpg" as a
URL.

This doesn't happen if you remove the "type:jpeg" operator:
http://arquivo.pt/search.jsp?query=mcd102g.jpg&hitsPerPage=10&dateStart=01%2F01%2F1996&dateEnd=01%2F12%2F2009
```

Reported by `devel.david@vcruz.net` on 2012-08-01 11:08:32

**Comment by dcgomes** [comment]
I am not sure if this is a NutchWax or Wayback.

@Fernando-Melo please also check this issue.

**Comment by Fernando-Melo** [comment]
It is NutchWax and it is related with the image search, maybe assign this to the future milestone where we will have an image search prototype

**Comment by Fernando-Melo** [comment]
Can't seem to reproduce this issue in the new version of arquivo.pt

**Comment by dcgomes** [comment]
It seems that all the query strings containing a dot are considered to be URLs.

Maybe we should identify URLs by host TLD. Check: https://www.icann.org/resources/pages/tlds-2012-02-25-en

Must them refresh the list periodically.

**Comment by dcgomes** [comment]
Let's try a easy fix and then validate through usability testing:
- same font size on datepicker dates as query textbox
- remove italic

**Comment by Fernando-Melo** [comment]
Done both the changes in style in the date, and also the TLD approach in p27
