### ISSUE TITLE
Add navigation icons to internal search engine results page

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#417]
When users perform an internal search within the sobre.arquivo.pt website such as:
http://sobre.arquivo.pt/pt/pesquisar/?q=teste

To browse the several results pages, the users must use the tiny numbers at the footer of the page:
"1 2 3 4"
The light grey color also makes this numbers almost invisible to the users.

An additional "Next page" icon or link would improve the UX.

**Comment by pcabritafccn** [comment]
Issue #417 is now solved.

**Comment by pcabritafccn** [comment]
Issue #417 is now closed as navigation has highlighted links now (as one of two options: highlighted links or icons).

![image](https://user-images.githubusercontent.com/51712013/129730966-0f736dd2-d23a-4c63-8c95-c0a11b43df4f.png)
