### ISSUE TITLE
Integration with oldweb.today in Replay bar. 

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#418]
Integration with oldweb.today in Replay bar: "view page with a browser from the past". 

Drop-down menu with browser list to access preserved page. 

Use oldweb.today API?

**Comment by dcgomes** [comment]
Just need to add one icon on the Replay bar and generate a link:
http://oldweb.today/firefox/$DATE/$URL

Example:
http://oldweb.today/firefox/20031212160948/http://sapo.pt

**Comment by dcgomes** [comment]
The icon label can be:

PT:
Veja com browser antigo

EN:
Replay with old browser

**Comment by igobranco** [comment]
@pcabritafccn send the icon and I add the menu replay option.

**Comment by igobranco** [comment]
@pcabritafccn I've added the functionality. You need to add the icon.

**Comment by pcabritafccn** [comment]
This issue is now solved.
