### ISSUE TITLE
Index base64 images

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#423]
Improve the indexing job so that it also indexes images with src in base 64 like

<img src="data:image/jpeg;base64,/9j/4AA...QSkZJRgA==>"

**Comment by Fernando-Melo** [comment]
maybe there is no need to index those images

**Comment by amourao** [comment]
On the new indexer version, images are being identified by url (as SURT).
What to do with these images that do not have an url?
Maybe use domain + a hash of the base64string/content as it will enable matching the image across pages of the same domain.

**Comment by amourao** [comment]
https://github.com/arquivo/image-search-indexing/commit/2bb977fe41fc9b3810746b6f524cda10d351d8f7 added base64 support, using the full "data:image" as the canonical url in place of surl
