### ISSUE TITLE
Apache not interpreting HTML encodings

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#439]
If you enter the following url:
http://arquivo.pt/wayback/20110323155356/http://dn.sapo.pt/Inicio/
you will be redirected to
http://arquivo.pt/wayback/20110316160248/http://www.dn.pt/%2fInicio%2f

We are getting an apache error instead of a 404 error.

**Comment by PedroG1515** [comment]
Examples:
http://sol.sapo.pt/inicio/%2finicio%2fEconomia%2fdefault.aspx
http://sol.sapo.pt/PaginaInicial/%2finicio%2fdefault.aspx
