### ISSUE TITLE
site: search gives different results with and without www

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#440]
search in arquivo.pt

- site:sapo.pt

- site:www.sapo.pt

Different results. Should the number of results be the same for these queries?

**Comment by igobranco** [comment]
With (www):
![image](https://user-images.githubusercontent.com/67018/67478962-fafbc300-f654-11e9-862f-8e7ef693d6c4.png)

With:
![image](https://user-images.githubusercontent.com/67018/67479006-0ea72980-f655-11e9-8927-95ce3b3403d1.png)

**Comment by igobranco** [comment]
Implement on subdomain search on solr text search.
