### ISSUE TITLE
Arquivo.pt icon is not transparent

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#444]
See the top bar of the browser. The background of the ico is white instead of transparent.

Try on Firefox: https://arquivo.pt/wayback/19980205082901/http://www.caleida.pt/saramago/
![iconsemtransparencia](https://user-images.githubusercontent.com/13120352/47167615-cf822200-d2f6-11e8-9a06-7a90d10fcc7d.jpg)

**Comment by dcgomes** [comment]
On Firefox the logo on Replay bar also has transparency problems check on RB computer.

**Comment by Fernando-Melo** [comment]
It is cache. I also had this showing white on firefox I cleared cookies and cache and is transparent now.
