### ISSUE TITLE
END DATE Advance Search is Not Working

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#445]
Quando se faz uma pesquisa e se escolhe uma data como a data mais recente para a qual quero obter informação (ex.: pesquisar até 31/12/1999), o sistema simplesmente ignora a restrição que fizémos e continua a apresentar páginas guardadas em anos mais recentes. Sugiro que isto seja corrigido o quanto antes, pois não está a ser possível utilizar convenientemente o Arquivo.

Com os melhores cumprimentos,

Pedro Vasconcelos

**Comment by Fernando-Melo** [comment]
@danielbicho fixed it
