### ISSUE TITLE
PhantomJS is not able to ssl handshake NoFrame Endpoint with TLS

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#446]
Currently PhantomJS is not able to SSL Handshake Arquivo.pt without using SSLv3. Even using the more recent version (2.1) and specifying the TLS as protocol don't work.

The provided CipherSuites by the WebServer are supported by PhantomJS. Enabling SSLv3 at Web Server works.

SSLv3 is vunerable to POODLE attacks and is degrading the SSL Rating of the Website.
If we are not able to solve this at PhantomJS level we need to configure an private endpoint for PhantomJS connect without HTTPs.

**Comment by danielbicho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ScreenShot server Problem with SSL Configurations](https://trello.com/c/VltGIkMn/818-screenshot-server-problem-with-ssl-configurations)

**Comment by igobranco** [comment]
@danielbicho maybe this could be closed because we redirect the requests to print and screen shot servers to http on localhost. Both this changes are already in production.

**Comment by danielbicho** [comment]
Still not solve the problem. The implementation of #500 will solve this.

**Comment by Fernando-Melo** [comment]
maybe use a real google-chrome instead of phantomjs, they now support full-page screenshots

**Comment by danielbicho** [comment]
Fixed on preprod.arquivo.pt
Before:
![image](https://user-images.githubusercontent.com/13105310/74963774-32fbf280-540a-11ea-9a74-4afc588174bb.png)

After replacing the Screenshost Service:
![image](https://user-images.githubusercontent.com/13105310/74963846-4dce6700-540a-11ea-8139-e1ae0205b0a3.png)
