### ISSUE TITLE
Images result doesn't appear on corresponding page

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#448]
Image search for: Vanda Miranda

http://p28.arquivo.pt/images.jsp?l=pt&size=all&type=&tools=off&safeSearch=on&query=vanda+miranda&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2017

When we click "Visit page" on this image result:
src: http://radiocomercial.clix.pt/upload/V/vanda_miranda.jpg

The page does not contain the image:
http://p28.arquivo.pt/wayback/20110704010116/http://radiocomercial.clix.pt/equipa/mario_rui.html

Same problem for image:
https://arquivo.pt/wayback/20120123020021/http://www.radiocomercial.iol.pt/images/menu/vanda_miranda_menu.png

Does not appear on corresponding host page:
http://p28.arquivo.pt/wayback/20120130225431tf_/http://www.radiocomercial.iol.pt/musica/body.aspx?id=48075

Another example:
- Image
https://arquivo.pt/wayback/20120123020021/http://www.radiocomercial.iol.pt/images/menu/vanda_miranda_menu.png
- Page
http://p28.arquivo.pt/wayback/20120130225431/http://www.radiocomercial.iol.pt/musica/body.aspx?id=48075

**Comment by Fernando-Melo** [comment]
The images are on the page. So they were extracted as linking to the page. If you inspect the archive page you will notice that the images are in the html code. What happens in those particular examples is that the images are hidden although they are inside the html

**Comment by Fernando-Melo** [comment]
![image](https://user-images.githubusercontent.com/13658607/49461099-dbfd0400-f7ea-11e8-9787-a91bfa678172.png)
