### ISSUE TITLE
Add a metadata link to the not rewritten archived page ('original' HTML)

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#450]
Rewritten HTML:
https://arquivo.pt/wayback/19980205082901/http://www.caleida.pt/saramago/

Not rewritten HTML:
https://arquivo.pt/wayback/19980205082901id_/http://www.caleida.pt/saramago/

**Comment by dcgomes** [comment]
Include new element "linkToOriginalFile" on response to call to show all meta-data:
- https://arquivo.pt/textsearch?metadata=http%3A%2F%2Fwww.caleida.pt%2Fsaramago%2F%2F19980205082901

All the metadata response elements should be showed on the UI through the "Technical details" link.
