### ISSUE TITLE
TextSearch API wrong collection names

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#479]
TextSearch API is giving wrong collection names for FAWP and IA collections due to OpenSearch.

e.g. https://arquivo.pt/textsearch?q=Albert%20Einstein&maxItems=10&prettyPrint=true&to=2006&fields=collection

returns 

{
      "collection": "IA20031030"
    },
    {
      "collection": "IA20040707"
    },
...
}

**Comment by Fernando-Melo** [comment]
Possible solution: quick fix on the servlet, by changing the name of the collection if it its IA or a FAWP collection

**Comment by danielbicho** [comment]
This need to be fixed at indexing time and not at runtime. Also it will make the search by collection not work well :\. A fuzzy search at Collection field can solve temporarily this problem.

**Comment by danielbicho** [comment]
Fixed in indexing time #543. Need re-indexing.
