### ISSUE TITLE
Add elapsed time to ImageSearchAPI

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#480]
Return the elapsed time as a field in the response header. Add it also in textsearch api?

**Comment by danielbicho** [comment]
Why does that matter for the end user?

**Comment by igobranco** [comment]
The idea is to monitor the performance of the APIs, but on the end user perspective. 
Maybe it can be done directly on javascript monitoring ajax call time. 
The idea is to push this time as an event to google analytics. 
Maybe the archived collection could be sent as a new google analytics dimension.

**Comment by dcgomes** [comment]
Won't do. This kind of performance information must be gathered from log analysis or monitoring tools.
