### ISSUE TITLE
From and to dates are lost when entering advanced search

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#486]
From and to dates are lost, when the user goes from normal search to the advanced search.

1. [Normal text search](https://arquivo.pt/search.jsp?l=en&query=fccn&dateStart=26/06/2007&dateEnd=27/06/2007)

2. When clicking on _Advanced search_ the specific date interval is lost.

This problem affects both text and image user interfaces.

Possible fix:
Pass the specific from and to dates to the advanced search link.

**Comment by danielbicho** [comment]
Related and duplicated issue: #678 #689
