### ISSUE TITLE
Improve anti-spam on contact form

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#487]
We are receiving increasing spam messages through our contact form: https://sobre.arquivo.pt/en/contact/
Specially with text in Russian.
This situation may lead us to lose important contact messages among all the spam messages.

**Comment by igobranco** [comment]
@dcgomes  Could this be not done if we replace the functionality with google forms ? #643

**Comment by dcgomes** [comment]
Fix by closing issue #643
