### ISSUE TITLE
Error loading more images

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#497]
https://preprod.arquivo.pt/images.jsp?l=pt&size=all&type=gif&tools=on&safeSearch=on&query=homer&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018

Keep requesting for more images until it hangs.

**Comment by igobranco** [comment]
This isn't a problem on mobile version, because the desktop version is going to be retired, I'm going to close this issue.
