### ISSUE TITLE
Replace ScreenShot and Print Servers with a more robust technology

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#500]
Replace this services(servers) with other more robust technology:
- [ScreenShotServer](https://github.com/arquivo/ScreenShotServer)
- [PrintServer](https://github.com/arquivo/PrintServer)

There is different options like [Chrome Headless](https://developers.google.com/web/updates/2017/04/headless-chrome), [Puppeteer](https://developers.google.com/web/tools/puppeteer/), [browserless](https://github.com/joelgriffith/browserless). 

Like execute this command on your desktop:
`google-chrome --headless --disable-gpu --screenshot --window-size=1280,1696 https://arquivo.pt`

For server that receives the screenshot requests it could be used the nodejs server or java web app that run on tomcat. 

### NodeJs
It receives the requests on a path and invoke the Puppeteer library directly on nodejs.

### Java web app
Use [Selenium+Chrome](https://www.built.io/blog/run-selenium-tests-in-headless-browser) like a test but instead of click, take a screenshot, read the file and return it as a result.
[Other example](https://stackoverflow.com/questions/25320890/how-to-launch-chrome-browser-from-java).
Selenium code that take a screenshot:
```
package chrome;
       public class HeadlessTesting {
            public static void main(String[] args) throws IOException{
                System.setProperty("webdriver.chrome.driver",
                        "ChromeDriverPath");
                ChromeOptions options = new ChromeOptions();
                options.addArguments("headless");
                options.addArguments("window-size=1200x600");
                WebDriver driver = new ChromeDriver(options);
                driver.get("https://contentstack.built.io");
                driver.get("https://www.google.co.in/");
                System.out.println("title is: " + driver.getTitle());
                File scrFile = ((TakesScreenshot) driver)
                        .getScreenshotAs(OutputType.FILE);
                FileUtils.copyFile(scrFile, new File("pathTOSaveFile"));
                driver.quit();
            }
        }
```
We can also use our own [functional tests](https://github.com/arquivo/functional-tests). 

To limit the number of request, use a Servlet Filter or a [Java only](https://stackoverflow.com/questions/5563442/how-to-set-limit-to-the-number-of-concurrent-request-in-servlet) [Semaphore](https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/Semaphore.html).

For [PrintServer](https://github.com/arquivo/PrintServer) use the same approach that was used for current print server. Print a pdf of a page that only contains a image html element of the screenshot service.

**Comment by igobranco** [comment]
Use [browserless](https://github.com/joelgriffith/browserless) on a docker to run chrome as a service.
Put this service behind a load balancer.
Connect it using webdriver protocol implemented by selenium.

**Comment by Fernando-Melo** [comment]
check if selenium takes screenshot to full page or only visible screen

**Comment by danielbicho** [comment]
To replace this component: https://github.com/arquivo/puppeteer-webrender

**Comment by danielbicho** [comment]
screenshotserver replaced, will open a issue to replace the printserver that would be just another feature on https://github.com/arquivo/puppeteer-webrender
