### ISSUE TITLE
Remove Opensearch API

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#510]
It's still needed to remove the open search API from source code.

The servlet and its reference on web.xml.

./PwaArchive-access/projects/nutchwax/nutchwax-core/src/main/java/org/archive/access/nutch/NutchwaxOpenSearchServlet.java

PwaArchive-access/projects/nutchwax/nutchwax-webapp/src/main/webapp/WEB-INF/web.xml

URL: https://arquivo.pt/opensearch?query=

Preprod: https://preprod.arquivo.pt/opensearch?query=

**Comment by Fernando-Melo** [comment]
done
