### ISSUE TITLE
Encoding problem in spell checker

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#517]
Será que quis dizer: Lisboa venda^-50 aluguer^-50 apartamento^-50 imobili�rio-50

https://arquivo.pt/images.jsp?l=pt&size=all&type=&tools=off&safeSearch=on&query=Lisboa+venda%5E-50+aluguer%5E-50+apartamento%5E-50+imobiliario%5E-50&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018

**Comment by PedroG1515** [comment]
Done with issue #136
