### ISSUE TITLE
Remove total_items from Arquivo.pt API

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#520]
Remove **total_items** response element from Arquivo.pt API

**Comment by dcgomes** [comment]
Change total_items to estimated_nr_results
Update documentation

**Comment by dcgomes** [comment]
Present this estimated number on the SERP. Researchers that a apply a thorough reading methodology need an estimation of the amount of results involved to define an adequate strategy to study them.

**Comment by igobranco** [comment]
@dcgomes  I'm going to change the PT expression of the total items, so it's more similar to Google:
PT: “Cerca de $NRESULTS resultados desde $OLDEST_DATE”.

**Comment by igobranco** [comment]
> @dcgomes I'm going to change the PT expression of the total items, so it's more similar to Google:
> PT: “Cerca de $NRESULTS resultados desde $OLDEST_DATE”.

Done.
