### ISSUE TITLE
Textsearch forcing CDX API requests to https

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#521]
`2019-04-05 14:47:08,385 INFO  CdxParser - [getResults] CDX-API URL[https://p28.arquivo.pt/wayback/cdx?url=http%3A%2F%2Fsapo.ua.pt%2Fteste%2F&output=json&from=19960101000000&to=20191231235959&reverse=true]`

In this case the request to cdx API should have been made in http instead of https

**Comment by Fernando-Melo** [comment]
Add the property wax.protocol in the hadoop-site.xml of the nutchwax webapp (default is https)
`  <property>` 
`   <name>wax.protocol</name>` 
`     <value>http://</value>` 
`   </property>`

**Comment by igobranco** [comment]
Already done.
Added broker_arquivo_protocol ansible variable with protocol to use.

https://gitlab.fccn.pt/awp-arquivo-da-web-portuguesa/ansible/blob/master/roles/broker_server/templates/hadoop-site.xml.j2
