### ISSUE TITLE
List versions - show list view by default and not table view

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#534]
- When searching by text on the mobile version, the 'List versions' anchor should always show the 'List of versions' view by default.

- On the replay of pywb the 'List versions' button should always show the 'List of versions' view by default

**Comment by dcgomes** [comment]
Consider show Table view by default on desktop (wide screens) and List view on mobile (narrow screens)

**Comment by arquivo-awp** [comment]
Seems to be OK at current version. Cannot reproduce problem with provided examples.
