### ISSUE TITLE
New Web.xml for imagesearch project

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#537]
Old configuration:

    <init-param>
         <param-name>solrServer</param-name>
         <param-value>http://p63.arquivo.pt:8983/solr/SAFE</param-value>
         <description>Location to the SOLR collection</description>
     </init-param>

New configuration:

     <init-param>
         <param-name>solrServer</param-name>
         <param-value>http://p63.arquivo.pt:8983/solr/</param-value>
         <description>Location to the SOLR collection</description>
     </init-param>         
    <init-param>
         <param-name>solrCollection</param-name>
         <param-value>SAFE</param-value>
         <description>Name of the SOLR collection</description>
    </init-param>

now solrServer parameter can be a single server or a zookeeper e.g.

     <init-param>
         <param-name>solrServer</param-name>
         <param-value>p24.arquivo.pt:2181,p26.arquivo.pt:2181,p28.arquivo.pt:2181</param-value>
         <description>Location to the SOLR</description>
     </init-param>

**Comment by igobranco** [comment]
Changed deployment configurations for dev and stage. 

For prod env the configuration change will only be applied on next image search api web application upgrade.
