### ISSUE TITLE
Show error stack trace in development and preprod environments

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#538]
errorstacktrace.html

- empty in production

- with the following code in development and preprod environments

```
<h2>Pywb Error</h2>
<p>{{ err_msg }}</p>
{% if err_details %}
<p>Error Details:</p>
<p>
<p>
{{ err_details }}
</p>
</p>
{% endif %}
```

**Comment by Fernando-Melo** [comment]
Example page https://arquivo.pt/wayback/20151001174403/http://repositorio-tematico.up.pt/handle/10405/10766

**Comment by igobranco** [comment]
Done.
On production environment this tracked file is replaced with an empty file (with a html comment in it).
