### ISSUE TITLE
Verify why our crawler was blocked

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#542]
Its not the first time that we find Heritrix being blocked by robots.txt,despite our current ExplicitRobotsPolicy. 

Usually is always by hosts with this big robots.txt list - https://journals.cambridge.org/robots.txt At first glance i dont see any reason to be blocked.

**Comment by PedroG1515** [comment]
In this specific case, the robots.txt from https://journals.cambridge.org/robots.txt explicitly blocks the User-Agent "Heritrix" and in our case, our User Agent has the substring "heritrix" (i.e., Arquivo-web-crawler (compatible; heritrix/...) ) being also blocked.
