### ISSUE TITLE
Apply site:$HOST instead of site:$URL when the query is an URL

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#552]
On image search tab, if the user queries for an URL:
https://arquivo.pt/images.jsp?l=pt&size=all&type=&tools=off&safeSearch=on&query=http%3A%2F%2Fwww.fccn.pt%2Findex.php%3Fmodule%3Dpagemaster%26PAGE_user_op%3Dview_page%26PAGE_id%3D100%26MMN_position%3D6%3A6&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018

The system should make a search for the images of that site (site:$HOST) and not not apply the site operator to the full URL. The site operator does make sense for a specific URL.

**Comment by igobranco** [comment]
@dcgomes is this still relevant to desktop version? Or could this be done only on the mobile version?

**Comment by igobranco** [comment]
It's fixed on mobile version.
