### ISSUE TITLE
Change the way database is populated when indexing Multiple Captures collection

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#557]
While indexing, sometimes the process breaks because of malformed lines when importing to database.

This line screams for trouble:
`arcreader -p $line 2>/dev/null | awk '{if (NR!=1) {print}}' | awk '{printf("\42%s-%s-%s %s:%s:%s\42", substr($1,0,4), substr($1,5,2), substr($1,7,2), substr($1,9,2), substr($1,11,2), substr($1,13,2))}; {print ",\42"gensub(/\"/,"\"\"","g",$3)"\42,\42"$4"\42,"$5","$8",\42"$9"\42"}' >> $csv_file`

**Comment by vitgou** [comment]
Reviewed and improved current database import, currently available in the ansible repo.
