### ISSUE TITLE
Forbidden suggest site

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#576]
When you click on suggest site, you may get a 403 Forbidden response:
e.g. https://arquivo.pt/sugerir?your-sites=https://pplware.sapo.pt/gadgets/hardware/raspberry-pi-4-b/

**Comment by igobranco** [comment]
Fixed
Also fixed the same page on english.

Like:
https://sobre.arquivo.pt/en/collaborate/suggest/?your-sites=https://pplware.sapo.pt/gadgets/hardware/raspberry-pi-4-b/
