### ISSUE TITLE
pywb2 timemap problem

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#582]
preprod.arquivo.pt/wayback/timemap/*/www.fccn.pt
  doesn't work

preprod.arquivo.pt/wayback/timemap/link/www.fccn.pt
  doesn't return same information comparing to arquivo.pt that has pywb previous version

Any change to protocol needs to be documented on https://github.com/arquivo/pwa-technologies/wiki/Memento---Time-travel-API

**Comment by danielbicho** [comment]
documentation changed
