### ISSUE TITLE
Send event to google analytics with the number of the search result clicked

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#583]
Send event to google analytics with the number of the search result clicked.
E.g. when user clicks on the 2nd page of results, in the 2nd result, send an event to googleanalytics with the number 12.
Do this for the text and image search on desktop and mobile.

ga('send', 'event', [eventCategory], [eventAction], [eventLabel], [eventValue], [fieldsObject]);

Set eventValue to 1, to allow counts in google analytics.

**Comment by igobranco** [comment]
Solution is:
Add an onclick attribute to the anchors on search results of the page search and images that send that event to google analytics.
