### ISSUE TITLE
Add datepickers to the mobile homepage

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#585]
Similarly to search.jsp add the datepickers and the date slider to the homepage of the mobile version.

**Comment by Fernando-Melo** [comment]
@dcgomes check if it is really needed to add the datepickers to the homepage. We removed the autofocus. Check if it is ok in the p18 machine or if we still need to add those datepickers

**Comment by jnobre** [comment]
Commit: #600
