### ISSUE TITLE
Row too big on results table of url search

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#601]
Some items apear too large occupying too much space.
This occurs on small screen sizes, like iphone 4 or iphone 5 (tested on chrome desktop with that phones resolutions).

View next screenshot:

![image](https://user-images.githubusercontent.com/67018/67477582-4791cf00-f652-11e9-9d58-444d2db2c0dd.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
