### ISSUE TITLE
Hide background content on image details modal

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#603]
When the user opens the image details modal, if he scrolls to bottom, it's incorrectly showing the search screen.
It's should hide it when the modal is open. 
When the modal is closed the search screen (div etc.) should be shown again. 

![image](https://user-images.githubusercontent.com/67018/67502639-1f1fca00-f67e-11e9-8b0a-98ef6a654a42.png)

**Comment by dcgomes** [comment]
Present only the "image details modal" and remove the search UI below.
