### ISSUE TITLE
Field description link of technical details is broken

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#608]
Technical details (field description) goes to a broken link.
It think it should go to "https://github.com/arquivo/pwa-technologies/wiki/Arquivo.pt-API-v.0.2#response-fields"

![image](https://user-images.githubusercontent.com/67018/67945106-07909600-fbd6-11e9-8db8-fdd83d9d9158.png)

**Comment by jnobre** [comment]
https://github.com/arquivo/pywb-arquivo/commit/c9399e6f1a2825c320ec2e07f695ec4bd32f1f9e
