### ISSUE TITLE
Google is crawling supposedly disallowed pages

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#61]
Originally reported on Google Code with ID 62
```

According to Google Analytics information, the Google crawler is retrieving archived
pages from archive.pt that should be disallowed according to the robots.txt file.

The likely cause of the problem is some misconfiguration of the robots.txt file.
```

Reported by `devel.david@vcruz.net` on 2013-02-01 18:16:20

**Comment by danielbicho** [comment]
This problem has been solved. The rules changed to /wayback/wayback and a test was made to check if the googlebot is blocked.

![image](https://cloud.githubusercontent.com/assets/13105310/9221479/8c4d6c78-40e2-11e5-8634-2973df98e9ae.png)
