### ISSUE TITLE
(Regression) Replay Interface is showing again resources with 400s and 500s status codes

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#623]
On the replay interface, list versions is showing again the resources with **400s** and **500s** status codes.

Example: https://arquivo.pt/wayback/20131108044736/http://www.caleida.pt/saramago/

Change it from **filter=!status:4|5** to **filter=!~status:4|5**

Also a regression test needs to be created to avoid future regressions.

### Tasks:
- [x] Fix the problem
- [x] Create a regression test

**Comment by igobranco** [comment]
Fixed in production

**Comment by igobranco** [comment]
Added a regression test for list mode:
- https://github.com/arquivo/functional-tests/blob/master/src/test/java/pt/fccn/mobile/arquivo/tests/urlsearch/URLSearchListNotContainsSomeHttpCodesTest.java

And improved the normal url search test with more tests:
- https://github.com/arquivo/functional-tests/blob/master/src/test/java/pt/fccn/mobile/arquivo/tests/urlsearch/URLSearchListTest.java
