### ISSUE TITLE
Specific URL isn't detected as search by URL

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#627]
The following URL isn't detected as search by URL instead of text.

http://github.com/arquivo/pwa-technologies/wiki/OpenSearch-API-%E2%80%93-Full-text-Search-(deprecated)

**Comment by dcgomes** [comment]
Another example:
https://github.com/arquivo/pwa-technologies/wiki/ImageSearch-API-v1-(beta)

**Comment by igobranco** [comment]
Yes, i've confirmed that it's the '(' character isn't treated correctly.

Searching by [https://www.fccn.pt](https://arquivo.pt/search.jsp?l=pt&query=https%3A%2F%2Fwww.fccn.pt&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018) goes correctly to table version.
But searching by [https://www.fccn.pt/(hello)](https://arquivo.pt/search.jsp?l=pt&query=https%3A%2F%2Fwww.fccn.pt%2F%28hello%29&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018) goes **incorrectly** to full text.

**Comment by igobranco** [comment]
Fixed on https://github.com/arquivo/arquivo-webapp/commit/b036c28200738bfd39c188a40fc00c1e69744989
