### ISSUE TITLE
Validate if begin date is always earlier than end date on date range restriction

### ISSUE THREAD

**Issue by jnobre** [arquivo/pwa-technologies#630]
- Start date cannot be higher than end date.
- End date cannot be less than start date.

Example:

![issue-datepicker-dates](https://user-images.githubusercontent.com/5844312/68947491-7ca2c480-07ad-11ea-9e54-270ccc179baa.png)

**Comment by PedroG1515** [comment]
Regression:

![DatePicker](https://user-images.githubusercontent.com/25795364/70803736-a949fc00-1dac-11ea-8866-dc0964318e82.PNG)
