### ISSUE TITLE
The version table years must be fixed when scrolling down.

### ISSUE THREAD

**Issue by jnobre** [arquivo/pwa-technologies#640]
The version table years must be fixed when scrolling down.

![tabela-versoes](https://user-images.githubusercontent.com/5844312/68953686-50417500-07ba-11ea-86c7-fefdbe073aaf.png)

**Comment by dcgomes** [comment]
@hmendes consider this suggestion in prototyping.

**Comment by igobranco** [comment]
I've already tested this js plugin (http://mkoryak.github.io/floatThead/) but I couldn't make it work, because currently the url search results (list or table) is inside an iframe. And the plugin seams to not work inside an iframe.

**Comment by pcabritafccn** [comment]
This does not apply to the new HTML code version. Going to close it.

**Comment by dcgomes** [comment]
Maintaining the visibility of the years improves UX because it maintains the context of the year in the Table view.
In Dionisius milestone this behavior was not implemented.

**Comment by pcabritafccn** [comment]
Issue #640 is now done.
