### ISSUE TITLE
Replace suggest form with a google form

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#643]
The suggest forms to be used to suggest a site to be crawled are constantly with problems.
https://arquivo.pt/sugerir
https://arquivo.pt/suggest

It should consider replace it with a google form.

Test if a google forma could send email to the requester with content that he have put on the form and to a arquivo.pt email.

**Comment by dcgomes** [comment]
Current message:

![image](https://user-images.githubusercontent.com/13120352/89191250-903fc680-d59a-11ea-9ddb-66e0c617e5af.png)


Simplify confirmation message to become:

"Recebemos a sua sugestão!

Os endereços sugeridos ficarão acessíveis no Arquivo.pt após 1 ano da sua recolha, por respeito ao período de embargo.

Obrigado!"
