### ISSUE TITLE
Patching Mode should have a banner and a quit button

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#657]
Regardless it's just working in preproduction, at least for now, Patching mode should have an Arquivo.pt banner with some visual clues that we are patching the webpage, and a button to quit Patching mode.

It feels really disruptive when the user enters in Patching mode. It feels that the user gets completely out of Arquivo.pt and is not easy to get back to the Replay mode.

The back button of browsers is not enough to quit Patching mode back to Replay mode.

Most of time the workflow is the following:
1. Navigate to the archived webpage.
2. Press complete page button (entering patching mode).
3. Press webpage links while patching.

At this point (3.) the browser's back button is useless for quitting Patching mode.

**Comment by igobranco** [comment]
The same thing for the "Save page now" feature.
The behavior could be the same with the same look and feel.

**Comment by dcgomes** [comment]
Browsers already provides progress through the spinning icon.
The user can quit by closing the new tab opened for patching.
