### ISSUE TITLE
Reset dates link or button

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#66]
Originally reported on Google Code with ID 67

```
What steps will reproduce the problem?
1. Make a search on a given subject and define date restrictions. E.g. Surf, 1998;2000.
2. Then make a new search on a different subject. E.g. Cooking.
3. The date restriction may inadvertently prevail across searches on different subjects.

What is the expected output? What do you see instead?
A "reset dates" button/link close to the dates drop-boxes could raise the attention
of the users to the date restrictions. On the other hand, it makes it easier for the
users to start new fresh searches on broad time scopes (Cooking, NO_DATE_RESTRICTION)
after doing searchers on narrowed time scopes (surf, 1998;2000).
```

Reported by `danielcoelhogomes` on 2013-03-15 17:09:32

**Comment by dcgomes** [comment]
Verify if this issue persists during the usability tests of the Janus release.

**Comment by Fernando-Melo** [comment]
@dcgomes 
a) Do you want to implement a Reset Dates button?
b) Do you want to automatically reset dates to the defaults each time the textbox changes its content?

**Comment by dcgomes** [comment]
We never noticed this problem to happen during usability testing with real users.
Maybe it is a non-issue. Close until it becomes an actually observed issue.
