### ISSUE TITLE
Desktop Version presented on mobile device: rendering problem on right side of the page

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#664]
Although does not make much sense, or is not common to navigate to the Desktop Version on a mobile device, the option is there, and on a mobile device there is a rendering problem at the right side. The main problem is that the option button to navigate back to mobile disappear.

**Comment by danielbicho** [comment]
![image](https://user-images.githubusercontent.com/13105310/70060590-bb70b100-15da-11ea-9714-dcb3a468a9d8.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
