### ISSUE TITLE
mobile version number of search results is wrong

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#667]
Searching for 'amigos' on the fulltext search mobile version the number of results per page is not coherent. It should display 10 results per page.

First Page show 10 results
Second Page of results show 9 results
Third Page of results show again 10 results

This behavior can happen on the First Page of results also.

The results that are shown on the Desktop must be the same that are shown on Mobile.

**Comment by igobranco** [comment]
Fixed when I've developed the #703.
