### ISSUE TITLE
Highlight pages on home page should change

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#67]
Originally reported on Google Code with ID 68
```
What steps will reproduce the problem?

The highlight pages on the home page of archive.pt, that exemplify to the users the
type of archived pages that can be found, are always the same.

What is the expected output? What do you see instead?

The examples should change on page load.



```

Reported by `danielcoelhogomes` on 2013-08-09 16:52:13

**Comment by dcgomes** [comment]
This would require developing a back-office to manage these examples. This is not a priority.
A simpler approach was adopted to solve this problem, see issue #165.
