### ISSUE TITLE
Replay options disappear with lower resolutions (Desktop version)

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#670]
Right display with all options available with 50% zoom on a laptop:
![image](https://user-images.githubusercontent.com/13120352/70060964-5b2e3f00-15db-11ea-8707-84beeb72570d.png)

Wrong display with no options available with 67% zoom on a laptop:
![image](https://user-images.githubusercontent.com/13120352/70061237-d1cb3c80-15db-11ea-8e73-ed01816a33f6.png)

The function labels could disappear but all function icons must be always available to the users independently from the resolution of the device: 
Icone completar a páginaCompletar a página Guardar a página Detalhes ténicos Imprimir a página Versão móvel PT  |  EN

**Comment by pcabritafccn** [comment]
This issue is now fixed.
