### ISSUE TITLE
Wayback replay is showing not archived too many times

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#672]
When searching by 'londres type:pdf', some result items aren't showing on wayback.

https://m.preprod.arquivo.pt/search.jsp?query=londres+type%3Apdf&l=pt&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018

When we click on the first 3 search results, we detect that the replay is:

- NOT OK | https://m.preprod.arquivo.pt/wayback/20141122172327/http://www.meteo-londres.eu/previsions/pdf_cartes_6j?pos=1&l=pt&sid=71F7E252A2AC60705A8ACCB0BDB06DC2
- NOT OK | https://m.preprod.arquivo.pt/wayback/20141122122053/http://www.meteo-londres.eu/previsions/tableau_pdf2/?pos=2&l=pt&sid=71F7E252A2AC60705A8ACCB0BDB06DC2
- OK | https://m.preprod.arquivo.pt/wayback/20141124071253/http://www.cnriveira.eu/downloads/rufinolondres.pdf?pos=3&l=pt&sid=71F7E252A2AC60705A8ACCB0BDB06DC2

NOT OK, means the that we see the not archied error page.

On the first example, if we remove the query parameters, then we can download the pdf. 

It seams to be a mobile only problem.

**Comment by dcgomes** [comment]
All results "Not Archived":
https://m.preprod.arquivo.pt/search.jsp?query=carolina+deslandes&l=pt&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018

**Comment by danielbicho** [comment]
solved
