### ISSUE TITLE
Message "Not Archived" does not need to display "ARQUIVO.PT"

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#673]
![image](https://user-images.githubusercontent.com/13120352/70061824-e0feba00-15dc-11ea-901b-6b617bddd8ea.png)

"ARQUIVO.PT" is already on the top bar. The redundancy reduces emphasizes on the most important message that is "Not archived".

Remove "ARQUIVO.PT" and redesign page.

**Comment by pcabritafccn** [comment]
This is issue is now solved.
