### ISSUE TITLE
robots.txt file should have a page search lower ranking

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#674]
The special robots.txt file should have a page search lower ranking. 

The page search shouldn't show the robots.txt file on the first result page.

When searching by 'joke' :  https://m.preprod.arquivo.pt/search.jsp?query=joke&l=pt&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018

The first search results are:
| search result number | URLs |
| 1st | https://m.preprod.arquivo.pt/wayback/20080316003721/http://images.joke.co.uk/robots.txt?pos=1&l=pt&sid=71F7E252A2AC60705A8ACCB0BDB06DC2 |
| 4th  | https://m.preprod.arquivo.pt/wayback/20080316212308/http://www.joke.co.uk/robots.txt |

**Comment by danielbicho** [comment]
Don't use the preproduction system to present Ranking problems. 
The number of documents is scarse, so this type of results can indeed happen.
