### ISSUE TITLE
Too much 302 at the top of the list of results

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#676]
I searched, on advanced search:   lisboa site:dn.pt
I got this set of 302 results: https://arquivo.pt/search.jsp?l=en&query=lisboa+site%3Adn.pt&btnSubmit=Search&dateStart=01%2F01%2F1996&dateEnd=01%2F12%2F2018 

![302_results](https://user-images.githubusercontent.com/44206545/70063572-edd0dd00-15df-11ea-9211-b1dfd9fd4acc.jpg)

**Comment by danielbicho** [comment]
We need to reindex the collection to solve this problem. We don't index redirects anymore

**Comment by amourao** [comment]
This will be solved when we reindex the documents using Solr
