### ISSUE TITLE
The close action on both image detail modal should be more responsive to the touch

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#684]
The close action on both image detail modal should be more responsive to the touch.

When using on a mobile device, sometimes the user can not easily close the modal.

![image](https://user-images.githubusercontent.com/67018/70067882-e5c86b80-15e6-11ea-9582-1908332bf0c7.png)

![image](https://user-images.githubusercontent.com/67018/70067890-ea8d1f80-15e6-11ea-954e-8faa2dcdc2a7.png)

**Comment by pcabritafccn** [comment]
The issue #684 is now solved: the close button touch area was increased with CSS in order to react better to the user´s touch. This is now working and fully functional at m.p18.arquivo.pt.
