### ISSUE TITLE
"Did you mean" does not appears on search image

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#687]
Search page:
![image](https://user-images.githubusercontent.com/25795364/70069622-fdedba00-15e9-11ea-8bc5-198400f99bc7.png)

Search image:
![image](https://user-images.githubusercontent.com/25795364/70069684-13fb7a80-15ea-11ea-826b-e3943caa6810.png)

**Comment by igobranco** [comment]
I've added the query suggestion to image search screen.
Nevertheless the suggestion is displayed strangely on wider screens like desktop.

**Comment by igobranco** [comment]
#602 is duplication of this issue.
