### ISSUE TITLE
The changes to search criteria aren't used if we change the search type

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#689]
If we change the search criteria from 'foo' pages to 'bar' images, it's searching the 'foo' images instead of 'bar' images.

The date range isn't applied when change the search type, view next example.

1. If we search pages using a term.
![image](https://user-images.githubusercontent.com/67018/70070781-119a2000-15ec-11ea-890d-4b6601c15299.png)

2. Then if we change the date range.
![image](https://user-images.githubusercontent.com/67018/70070835-28d90d80-15ec-11ea-8ab0-1a14d486fa2a.png)

3. Click on Images button

4. The search image results isn't filtered by that selected date range.
![image](https://user-images.githubusercontent.com/67018/70070881-41492800-15ec-11ea-950d-d3e6f4e86fa4.png)

**Comment by igobranco** [comment]
it's related to #678

**Comment by danielbicho** [comment]
@igobranco I think this problem is solved, can you verify?
It keeps the parameters that were used.

But by your example it seems that you want to apply a **new searching criteria** when pressing image button. Not clear.

**Comment by igobranco** [comment]
> @igobranco I think this problem is solved, can you verify?
> It keeps the parameters that were used.
> 
> But by your example it seems that you want to apply a **new searching criteria** when pressing image button. Not clear.

@danielbicho the problem maintains. Yes what we want is like a new search. 
I tried the this same flow on google and it isn't doing what I've opened on this issue. So maybe this issue is irrelevant.
