### ISSUE TITLE
Difference between ranking results in search image

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#690]
1. First page:
![m preprod arquivo pt_images jsp_query=lisbo l=en dateStart=01%2F01%2F1996 dateEnd=03%2F12%2F2018(Galaxy S5)](https://user-images.githubusercontent.com/25795364/70070876-3e4e3780-15ec-11ea-847b-e2077d2f273e.png)

2. Go to the second page.
3. Comeback to the first page.
![m preprod arquivo pt_images jsp_query=lisbo dateStart=01_01_1996 dateEnd=03_12_2018 pag=prev start=0 l=en(Galaxy S5)](https://user-images.githubusercontent.com/25795364/70070801-18c12e00-15ec-11ea-8b0d-8180958c7740.png)

**Comment by igobranco** [comment]
Now it seems ok.
