### ISSUE TITLE
Patching WARCs are too small

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#693]
**What happened?**
On patching wayback, the pywb is generating warcs files that are small < 1M and too many.

**What should have happened?**
It should generate bigger warcs files, like 1 per day with max size of 100MB.

** Impact **
The arcproxy starts to be populated with (w)arcs that are too small.
Maybe it could create some impact on indexing processes.

If pywb couldn't be configured with warc writer requirements:
- Max 100 MB
- 1 file per day
Then we could do this on ansible when copying the warcs from patching source directory to destination document servers.

**Comment by PedroG1515** [comment]
With [warcio](https://github.com/webrecorder/warcio) each WARC was processed, taking into account the pairs (Request, Response), originating file with 100 MB.

**Comment by PedroG1515** [comment]
Updates:
- Possibility to input arguments (using [argparse](https://docs.python.org/3/library/argparse.html));
- Process input generically;
- Throw exceptions in extreme cases;
- More generic file processing;
