### ISSUE TITLE
Add intro video to home page on mobile

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#694]
**What is the URL that originated the issue?**
https://m.arquivo.pt/

**What happened?**
The intro video is not available on the mobile home page and it is important to contextualize new users about what is Arquivo.pt and what they can find there.

**What should have happened?**
There should be also a card with the intro vídeo on the home page. 
PT:
https://www.youtube.com/watch?time_continue=2&v=2HEudlXPV4o&feature=emb_logo

EN:
https://www.youtube.com/watch?time_continue=1&v=dqG0VILi3gs&feature=emb_logo

**Screenshots**

**Comment by pcabritafccn** [comment]
Issue #694 is now solved: the intro video presentation of Arquivo.pt is now enabled on the mobile homepage version and fully functional on both Portuguese and English website versions. The changes can be viewed at m.p18.arquivo.pt
