### ISSUE TITLE
Did you mean on image search is displayed disformatted

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#695]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/images.jsp?query=lisbo&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018&l=en

**What happened?**
After adding the query suggestion to the image search screen, #687, it's displayed strangely on desktop.

**What should have happened?**
Display the query suggestion like the page search screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/70626438-5f321080-1c1c-11ea-9ac4-d04c09ea58ce.png)

**Comment by pcabritafccn** [comment]
This issue is now fixed.
