### ISSUE TITLE
'Complete Page' through Patching feature on Production

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#699]
Currently the 'Complete Page' button on the Production Environment redirects users to TimeTravel Service. We want instead to use the pywb Patching feature to Complete the Pages, exactly as we have on the Preproduction Environment.

- [x] @PedroG1515 - Merge WARCs into bigger files so we don't end with so many smaller WARCs - run it after synchronize WARCs to document server - #693
- [x] @igobranco - Create a new ansible playbook that move patching pywb WARCs from Production brokers to document server (synchronize to a new timestamp folder on document server and delete on origin).  
- [x] @igobranco - Add a new first stage on jenkins job [(Production - Update Collections Replay)](http://jenkins.arquivo.pt/job/Production%20-%20Update%20Collections%20Replay/) to run previous ansible playbook
- [ ] @igobranco - (preprod patching) Remove current synchronization on sync_data playbook running on [Production - Sync data
](http://jenkins.arquivo.pt/job/Production%20-%20Sync%20data/) jenkins job of PATCHING2020 collection from preprod to branch A document server
- [x] @igobranco Integration of patched content on Arquivo.pt on a daily/weekly basis - right time could be what we want using cron based jenkins job.
- [x] @danielbicho - Logging of patching activities more clearly.  
- [x] @danielbicho - Configure Pywb with the Patching Endpoint

**Comment by igobranco** [comment]
@danielbicho the patching feature needs to be on production brokers and the current publico.pt patching moved to production environment.

**Comment by danielbicho** [comment]
In production, we only need to toggle on the feature.

Patching can be easily tracked through access logs. 

pywb/uwsgi/supervisord logging needs some organization, like splitting the pywb stdout/stderr from the request logging of uwsgi, but will move that to a new issue.

**Comment by igobranco** [comment]
Only remove the synchronization on preprod patching after the deployment of the WebApp milestone/ release. When that occurs we could close this issue.

**Comment by igobranco** [comment]
On 2020-04-21 it was decided to maintain patching on preprod environment.
