### ISSUE TITLE
Cropped cards on the side on mobile version

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#701]
**What is the URL that originated the issue?**
https://arquivo.pt/

**What happened?**
Preserved pages card have the text cropped.

**What should have happened?**
The text on each card should be viewed correctly. 

**Screenshots**
Received screenshot using Samsung A40:
![image](https://user-images.githubusercontent.com/67018/70900160-21543400-1ff0-11ea-87b0-94e6aab52b7f.png)

On chrome tools using specific resolution:
![image](https://user-images.githubusercontent.com/67018/70900186-2d3ff600-1ff0-11ea-8d09-e41bf15290ec.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
