### ISSUE TITLE
Save Page now: create similar service on Arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#702]
## Save Page now: create similar service Arquivo.pt. 

- [x] @igobranco Create new pywb instance that stores warcs to different folder.
URL path of the save page now: /save/record/<URL>
Store warcs to different folder of the patching.

- [x] @igobranco  Change "Suggest site to be archived" to "Save page now!".
Replace link “Suggest site to be archived” (e.g. https://arquivo.pt/search.jsp?query=http%3A%2F%2Fultimahora.publico.pt%2FshownewsFAKEURL&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018&l=en) 
with link to pywb record feature (e.g. https://preprod.arquivo.pt/noFrame/patching/record/https://makeawebsitehub.com/weird-websites/)

- [ ] @igobranco  Show option "Save page now!" only if the URL returns 200 (follow redirects)  on the live-web.
Add a link to save page now functionality on not archived page #924

- [x] @igobranco  Log these URLs to be included in future crawls.
Maybe create a new path arquivo.pt/save (PT: arquivo.pt/guardar ) to aggregate all the incoming requests about this feature. And then redirect or proxy to /noFrame/save/record. Eg: https://arquivo.pt/save/http://example.com/a-page
The https://arquivo.pt/save could be a link to the form to insert an URL to save now.

- [x] @PedroG1515 Add a form on sobre.arquivo.pt that asks the user to insert an URL on an input and to click on save button. Similar to http://web.archive.org/save.

- [ ] #1185

- [x] @igobranco Add recording banner and quit button #657.

**Comment by igobranco** [comment]
New instance of pywb for save page now.

**Comment by dcgomes** [comment]
"Suggest site to be archived" and "Save page now!" are different features. DO NOT  Change "Suggest site to be archived" to "Save page now!". One aims to preserve the whole website in near future, the other only one page right now.

**Comment by danielbicho** [comment]
the **managed collection** directory structure (save) needs to be created beforehand, or manually or with **wb-manager init**

**Comment by PedroG1515** [comment]
We also have this issue #1035

**Comment by PedroG1515** [comment]
The prototype is done!. 
Some points will be done in the next phase.
