### ISSUE TITLE
Links on web-archived pages to arquivo.pt/wayback should not be rewritten

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#703]
Consider a page archived from the live-web that had links to web-archived pages:
- https://memoriafcsh.wordpress.com/2017/08/01/centro-de-estudos-historicos-2000-2015/
"A primeira versão preservada com o endereço fcsh.unl.pt/ceh é de 2000 e não tem alterações até 2006."
links to:
- http://arquivo.pt/wayback/20000915125205/http://www.fcsh.unl.pt/ceh/

When the web-page becomes web-archived:
https://arquivo.pt/wayback/20180919142909/https://memoriafcsh.wordpress.com/2017/08/01/centro-de-estudos-historicos-2000-2015/
"A primeira versão preservada com o endereço fcsh.unl.pt/ceh é de 2000 e não tem alterações até 2006."
links to:
https://arquivo.pt/wayback/20180919142909mp_/http://arquivo.pt/wayback/20000915125205/http://www.fcsh.unl.pt/ceh/
which originates a "Not Archived" message because the Replay system rewrites the URL to and adds the prefix "https://arquivo.pt/wayback/20180919142909mp_/" to redirect the link to Arquivo.pt.

Wayback should detect when the URLs in the links targeted web-archived pages, don't add the prefix and keep the original URLs in web-archived pages when they link to "https://arquivo.pt/wayback/*". In this example, the URL should be kept as in the original live-web page:
https://arquivo.pt/wayback/20000915125205/http://www.fcsh.unl.pt/ceh/

**Comment by igobranco** [comment]
I think this could be done on Apache HTTPd site configuration.

**Comment by danielbicho** [comment]
The server redirect doesn't work, weird things start to happen:
![image](https://user-images.githubusercontent.com/13105310/77068180-1093cf80-69de-11ea-842a-acf723c2ab5e.png)

I don't understand the pywb rewritting rules. will postpone this

**Comment by igobranco** [comment]
Can you put the apache httpd configuration on here so we can analyze it.

**Comment by danielbicho** [comment]
RewriteRule ^/wayback/.*/.*arquivo.pt/wayback/(.*)$ %{REQUEST_SCHEME}://%{SERVER_NAME}/wayback/$1 [PT]

It works if you open a new tab, or on an unframed context though

**Comment by dcgomes** [comment]
Check if newer version of PyWB fixes this issue.

**Comment by dcgomes** [comment]
Exceptions to rewrite of URLs was asked to Ilya.

**Comment by dcgomes** [comment]
Re-evaluate after Eros deploy

**Comment by VascoRatoFCCN** [comment]
I'll investigate implementing a fix on the replay page using [pywb UI customization](https://pywb.readthedocs.io/en/latest/manual/ui-customization.html)

**Comment by arquivo-awp** [comment]
Test when we integrate new version of pywb. 
@VascoRatoFCCN report issue to pywb project and close.
