### ISSUE TITLE
Export SERP in CSV format

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#704]
Researchers commonly aggregate their analysis in Spreadsheets.

We should add a function on the SERP page to export search results in CSV format. 
This could be implemented through a JSONtoCVS converter in Javascript that processes the results from the Arquivo.pt API.

Check Danish web archive.

**Comment by danielbicho** [comment]
This seems to only need development on the frontend

**Comment by igobranco** [comment]
@danielbicho you are right.

It seems easy to implement something like that. 
1. Export json to csv: https://stackoverflow.com/a/31536517/2239848
2. Export variable to file: https://stackoverflow.com/a/56616752/2239848

**Comment by igobranco** [comment]
Change to respect the RFC 4180 https://tools.ietf.org/html/rfc4180
Add a first line with `sep=,` so MS Excel interpret the column delimiter has a comma.

**Comment by igobranco** [comment]
Starting to use the [SheetJS](https://github.com/SheetJS/sheetjs) library.
Now there are buttons to export to XLSX, CSV (comma) and TXT(tab delimiter) formats.
