### ISSUE TITLE
Encoding Error: URL not found on URL Search results

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#705]
In the bottom of the following URL (https://arquivo.pt/wayback/20141108234539/http://www.publico.pt/politica/noticia/xanana-informou-passos-coelho-sobre-suspeitas-de-corrupcao-na-justica-de-timor-1675573?page=-1) there are a set of recommended notices.  

One of the images are presented in the following resources:

https://m.arquivo.pt/wayback/20141108234539im_/https://imagens.publicocdn.com/imagens.aspx/1421766?tp=UH&db=IMAGENS&w=362&h=204&act=cropResize

CDX:
https://arquivo.pt/wayback/cdx?url=https%3A%2F%2Fimagens.publicocdn.com%2Fimagens.aspx%2F1422331%3Ftp%3DUH%26db%3DIMAGENS%26w%3D362%26h%3D204%26act%3DcropResize%0A

However if you try to search for this specific URL (https://arquivo.pt/search.jsp?l=pt&query=https%3A%2F%2Fimagens.publicocdn.com%2Fimagens.aspx%2F1421766%3Ftp%3DUH%26db%3DIMAGENS%26w%3D362%26h%3D204%26act%3DcropResize&btnSubmit=Pesquisar) there is no resources found.

**Screenshots**

![encond](https://user-images.githubusercontent.com/25795364/71173199-fec55380-2259-11ea-92ae-f6d3150639e1.PNG)

**Possible Problems**

- Version of Pywb 
Pywb 2.0.0:
![pywb2 0](https://user-images.githubusercontent.com/25795364/71173289-316f4c00-225a-11ea-9e0e-1c7ae106e56e.PNG)

Pywb 2.4:
![pywb2 4](https://user-images.githubusercontent.com/25795364/71173288-316f4c00-225a-11ea-8cb3-1263ebd3cc12.PNG)

- Enconding  of URLs

**Impact**

- PageSearch, ImageSearch.
- Integration of patching files.

**Comment by PedroG1515** [comment]
Other example:
1) Search for "twiter"

2) And if you click on 9 position 
(https://arquivo.pt/wayback/20100805053836/http://mautempo.webx.com.pt/index.php?option=com_content&view=article&id=82&Itemid=64) the resource is found.

3) But If you search for "http://mautempo.webx.com.pt/index.php?option=com_content&view=article&id=82&Itemid=64", returns resource not found (https://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fmautempo.webx.com.pt%2Findex.php%3Foption%3Dcom_content%26view%3Darticle%26id%3D82%26Itemid%3D64&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2018)

**Comment by danielbicho** [comment]
escapingHtml variable urlQuery was breaking the search for this type of URL.
Also <c:out> tag already escapes HTML, thus StringEscapeUtils.escapeHtml(urlQuery) is not necessary (urlQuery is always being printed within a <c:out> tag).

**Comment by danielbicho** [comment]
reopening, the same is happening on the mobile version
