### ISSUE TITLE
History of pages visited on mobile.

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#706]
When a user clicks on a result and then returns to the result list, there is no information on which result was previously clicked (Mobile).

**Screenshots**
Example from browser:
![Expo](https://user-images.githubusercontent.com/25795364/71181027-443e4c80-226b-11ea-8b3f-297a18129997.PNG)

Mobile:
![ExpoM](https://user-images.githubusercontent.com/25795364/71181776-bb281500-226c-11ea-8f8f-ea1a89b88989.PNG)

**Impact**

- User disinterest
- More clicks than necessary
- On a later search (e.g., the next day) the user does not know what result he clicked

**Comment by igobranco** [comment]
The reported problem is resolved by adding a style on css like the it's done on desktop version.
@pcabritafccn please review this issue.

![image](https://user-images.githubusercontent.com/67018/71576422-8fb4ee00-2ae8-11ea-8004-e483cafe4659.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
