### ISSUE TITLE
Ortographic error on desktop version preprod.arquivo.pt

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#707]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20141123221450/http://admiradn.maxtrader.eu/uk/1,2,1,29777,0,295,11,-1,0,0,0/Admira+DN+-+Digital+Signage+Networks.html

**What happened?**
"Detalhes ténicos"

**What should have happened?**
"Detalhes técnicos"

**Screenshots**

<img width="960" alt="print01" src="https://user-images.githubusercontent.com/44206545/71515605-fc877880-289b-11ea-96c6-396463fc13b7.png">

**Comment by danielbicho** [comment]
fixed
