### ISSUE TITLE
The cross for clicking is not visible on "Detalhes técnicos" in the desktop version

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#708]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20170101180227/http://www.dn.pt/

**What happened?**
The cross for clicking is not visible on "Detalhes técnicos" desktop version

**What should have happened?**
The cross should be visible
**Screenshots**
<img width="815" alt="print2" src="https://user-images.githubusercontent.com/44206545/71515991-512bf300-289e-11ea-8aee-1ee165938bc5.png">

**Comment by danielbicho** [comment]
@pcabritafccn make it white maybe?

**Comment by pcabritafccn** [comment]
This issue is now solved.
