### ISSUE TITLE
List of versions moved from place

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#709]
**What is the URL that originated the issue?**

https://arquivo.pt/wayback/20131106224348/http://www.fccn.pt/pt/

**What happened?**
List of versions moved from place

Portuguese version:
![1](https://user-images.githubusercontent.com/25795364/71578631-e45c6700-2af0-11ea-8460-21cc6dc772f1.PNG)

English version:
![2](https://user-images.githubusercontent.com/25795364/71578706-2685a880-2af1-11ea-9669-bac1bff24707.PNG)

**Impact**

It is not possible to do scroll left-right.

![3](https://user-images.githubusercontent.com/25795364/71578766-69e01700-2af1-11ea-8857-e03257008cc1.PNG)

**Comment by pcabritafccn** [comment]
This issue is now fixed.
