### ISSUE TITLE
"No results were found for the query"- Element out of place.

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#711]
PageSearch:

![bug5](https://user-images.githubusercontent.com/25795364/71730290-ad13f000-2e39-11ea-829e-a556e64b019e.PNG)

ImageSearch:
![bug7](https://user-images.githubusercontent.com/25795364/71730348-cddc4580-2e39-11ea-87ef-9ef92741dede.PNG)

**Comment by pcabritafccn** [comment]
This issue is now solved.
