### ISSUE TITLE
Desktop version: reduce top left menu area from 100% to 20% wide

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#712]
**What is the URL that originated the issue?**

arquivo.pt

**What happened?**

When opened, the desktop version top left menu area is 100% wide, the same as the mobile version, which should not be happening.

**What should have happened?**

Desktop version top left menu area width needs to be reduced to +- 20% in order to have a better, and functional user experience.

**Screenshots**

![image](https://user-images.githubusercontent.com/51712013/71831062-05e4c200-30a0-11ea-8467-291c5573f34f.png)

**Comment by igobranco** [comment]
Done

**Comment by igobranco** [comment]
Also: on escape key close menu, replay menu or other popup.
