### ISSUE TITLE
Redesign date picker for desktop version

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#714]
**What is the URL that originated the issue?**
arquivo.pt

**What happened?**

The date picker on desktop version as the look and feel of the mobile version.

**What should have happened?**

The date picker needs to be redesign in order to be suitable to a desktop version. 
Use Google date picker as an example?

**Screenshots**

![image](https://user-images.githubusercontent.com/51712013/71893630-1ea6b380-3144-11ea-93c4-c2bcacfc3737.png)

**Comment by igobranco** [comment]
Now on desktop is displayed the jQuery datepicker on a modal and on mobile the previous ionic datepicker.

**Comment by igobranco** [comment]
The datepicker needs the following to be reviewed: 
- [ ] When changing the year on the combo box also change the current year value.
- [ ] When changing the month on the combo box also change the current month value.
- [ ] When clicking outside of the modal shouldn't close the modal.
- [ ] Increase the **OK** button size.
- [ ] Date format dd/mm/yyyy below the input.
- [ ] Remove previous and next month arrows.
- [ ] Full name of months on both desktop and mobile date pickers.

**Comment by igobranco** [comment]
@dcgomes with the current implementation using uglipop javascript library to open modal, I can't do the desired change:
> When clicking outside of the modal shouldn't close the modal

I suggest to not change anything more related to this issue on current milestone/release.

**Comment by igobranco** [comment]
On yesterday conference call it was decided that:
- [ ] The Cancel button should be removed;
- [ ] Each change of the user should change the current state of selected date.
- [ ] The Ok button should only close the modal.

Capture of the modal:
![image](https://user-images.githubusercontent.com/67018/76958043-da3b4f00-690e-11ea-91e4-6c1e969bdfb3.png)
