### ISSUE TITLE
Adapting the actual Replay section "List versions" menu to the new desktop version and style it to match the new design

### ISSUE THREAD

**Issue by pcabritafccn** [arquivo/pwa-technologies#718]
**What is the URL that originated the issue?**
arquivo.pt

**What happened?**
There is no Replay section "List versions" menu suitable to the new Desktop design, only a mobile version of it.

**What should have happened?**
Adapting the actual Replay section "List versions" menu to the new desktop version and style it to match the new design. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51712013/71896827-a98bac00-314c-11ea-8ed6-f5bcb11dd725.png)

![image](https://user-images.githubusercontent.com/51712013/71896849-b90af500-314c-11ea-9c08-efec3e9d9e35.png)

**Comment by igobranco** [comment]
The list/table of versions will be moved to a new iframe, only the results and not including the date slider. So it could be put on url search on arquivo.pt/search.jsp (if the search is an url) and the left side on wayback (if width is like a desktop).

**Comment by igobranco** [comment]
https://github.com/arquivo/arquivo-webapp/commit/4681e33b43d9b1b1390e8489f0bc2e28f5aec63b

**Comment by pcabritafccn** [comment]
This issue is now solved.
