### ISSUE TITLE
A broken link in the breadcrumb menu

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#719]
**What is the URL that originated the issue?**
https://sobre.arquivo.pt/en/help/help-about-image-search/

**What happened?**
A broken link in the breadcrumb menu.

**What should have happened?**
Should link to https://sobre.arquivo.pt/en/help/

**Screenshots**
<img width="787" alt="print00001" src="https://user-images.githubusercontent.com/44206545/72001017-6872c500-323c-11ea-83a6-4ead45eb326e.png">

**Comment by danielbicho** [comment]
it is what is happening! closing it, feel free to reopen it with more information
