### ISSUE TITLE
Replay of webpages changed

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#720]
**What is the URL that originated the issue
https://arquivo.pt/

**What happened?**
A user got some pages in a given date. Later, he went there and they were looking diferent. The replay changed and got worst.

**What should have happened?**
Should replay as well as the previous time. 

**Screenshots and feedback from a user**

Os jornais, que são objeto do meu estudo e que se alteraram foram:
 - Público, dia 4 de Junho de 2002 - link: https://m.arquivo.pt/wayback/20020604075207/http://publico.pt/
                                                        - print de como estava anteriormente: 
![image](https://user-images.githubusercontent.com/44206545/72001708-e71c3200-323d-11ea-94e7-afc785cf73d0.png)
                                                          

- O Jogo, dia 7 de Junho de 2007 - link: https://m.arquivo.pt/wayback/20070607010920/http://www.ojogo.pt/
                                                        - print de como estava anteriormente: 
![image](https://user-images.githubusercontent.com/44206545/72001724-edaaa980-323d-11ea-849a-a64922c21449.png)
                                                              

- O Jogo, dia 21 de Outubro de 2008 - link: https://m.arquivo.pt/wayback/20081021233540/http://www.ojogo.pt/
                                                            - print de como estava anteriormente: 
![image](https://user-images.githubusercontent.com/44206545/72001732-f13e3080-323d-11ea-99b6-7f02e1e7131f.png)
                                                             

- O Jogo, dia 20 de Maio de 2009 - link: https://m.arquivo.pt/wayback/20090520150742/http://www.ojogo.pt/
                                                       - print de como estava anteriormente:
![image](https://user-images.githubusercontent.com/44206545/72001746-f7341180-323d-11ea-92aa-6998e66d3562.png)
                                                        

- O Jogo, dia 1 de Abril de 2010 - link: https://m.arquivo.pt/wayback/20100401115234/http://www.ojogo.pt/
                                                       - print de como estava anteriormente:
 ![image](https://user-images.githubusercontent.com/44206545/72001766-ff8c4c80-323d-11ea-8c46-802d97b46ba8.png)
                                         
            
- O Jogo, dia 22 de Novembro de 2011 - link: https://m.arquivo.pt/wayback/20111122160335/http://www.ojogo.pt/index.asp
                                                       - print de como estava anteriormente:
![image](https://user-images.githubusercontent.com/44206545/72001801-0d41d200-323e-11ea-8963-872d1857761d.png)
                                                        

- O Jogo, todos os dias de 2017 estão desformatados, no entanto estes já estavam assim desde a minha primeira consulta em Setembro.
              - link de um dos dias: https://m.arquivo.pt/wayback/20170222180220/http://www.ojogo.pt/

**Comment by danielbicho** [comment]
A issue related with this is already open at https://github.com/webrecorder/pywb/issues/527

We don't have plans to handle it for now.
