### ISSUE TITLE
Page content is blinking on replaying

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#726]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20180919170011/http://radiocomercial.iol.pt/

It is similar problem at 
https://m.arquivo.pt/wayback/20181219203931/http://www.radionova.fm/media/live/ 
https://arquivo.pt/wayback/20181231181503/http://radioportuense.com/ouvir-em-direto/
https://arquivo.pt/wayback/20181228180013/https://www.avozdetrasosmontes.pt/
https://arquivo.pt/wayback/20181230180011/http://radiolumena.com/
https://arquivo.pt/wayback/20181203201203/http://www.radionova.fm/

**What happened?**
Page content is blinking on replaying only on radiocomercial.iol.pt.
Later a message was displayed "too many requests"

**What should have happened?**
Stop blinking

<img width="615" alt="2020_01_14_17_55_52_Rádio_Comercial_A_Melhor_Música_Sempre_preservada_pelo_Arquivo pt" src="https://user-images.githubusercontent.com/44206545/72369133-6060cc80-36f7-11ea-9cd9-6bddfb8f028e.png">

**Comment by PedroG1515** [comment]
Diference between preprod and production:
https://preprod.arquivo.pt/wayback/20180413225725/http://pload.org/
https://arquivo.pt/wayback/20180413225725/http://pload.org/

**Comment by PedroG1515** [comment]
Different example:
https://arquivo.pt/wayback/20200714190313/https://www.portugal.gov.pt/pt/gc22

**Comment by PedroG1515** [comment]
Possible solution: 

- 404 Cache

Check the presentation:

- "Michele Weigle and Michael Nelson: OPTIMIZING ARCHIVAL REPLAY BY ELIMINATING UNNECESSARY TRAFFIC TO WEB ARCHIVES" - WAC2022

**Comment by PedroG1515** [comment]
New version pywb
