### ISSUE TITLE
Index Blacklist

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#73]
Originally reported on Google Code with ID 74
```
The blacklist is processed by apache. Hence, this is not a reasonable solution/feasible
and the blacklist produced by the file Index_Collection.sh has to be fixed to put the
index in the "dark".

```

Reported by `HugoHAViana` on 2014-09-11 09:25:58

**Comment by FCCNhviana** [comment]
This issue was resolved in the previous milestone. Now, we can remove an index from the search results list.
