### ISSUE TITLE
Divide images mongodb table into 2 tables

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#733]
1st phase on image search indexing: divide the mongodb information on 2 tables.

Pros:
1) Save 9/10x times disk space on 1st phase of image search indexing on mongoDB servers.
2) Improve performance on MongoDB because it will save write bandwidth to MongoDB servers.

There are many duplicated images on ARC/WARC files.

Instead of saving information to images table with:
-  page info + image info + image thumbnail on same table

Change to 2 tables, like:
- page info + image info
- image thumbnail
-- digest (md5) image
-- thumbnail base 64

**Comment by amourao** [comment]
Closed, as the full architecture is being revised to avoid using MongoDB.
