### ISSUE TITLE
results in advanced search does not correspond to the query

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#735]
**What is the URL that originated the issue?**
https://arquivo.pt/search.jsp?l=pt&query=site%3A*.BR&btnSubmit=Pesquisar

**What happened?**
First results in advanced search are not what I've put in the query
The same happens if I ask for .pt (exception for 1st 2nd and 3th) (https://arquivo.pt/search.jsp?l=pt&query=site%3A*.pt&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2019)

**What should have happened?**
Should give results of .BR domain, not  of .net

**Screenshots**

<img width="942" alt="issue_pesquisa_avancada" src="https://user-images.githubusercontent.com/44206545/72718042-10f22480-3b6d-11ea-8e19-92675b4f1922.png">

**Comment by danielbicho** [comment]
Currently we don't support leading wildcard queries or prefix queries. Even with the new system these type of queries can be super inefficient. But it may make sense enable them on fields where the vocabulary is not very big. Will re-tag to visit later.

**Comment by danielbicho** [comment]
Nutchwax doesn't support this, and it currently returns no results as it is expected. Was solved with the issue #936
