### ISSUE TITLE
Problem replaying page, which may be related to jquery

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#743]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20180412160900/http://sim.assec.pt/

**What happened?**
The URL is loading infinitely

**Screenshots**

![2](https://user-images.githubusercontent.com/25795364/72989765-d1cf0800-3de6-11ea-9bc0-f26a58b28595.PNG)

**Comment by danielbicho** [comment]
I don't t think we will solve this, will keep it open for reference, or if someone wants to try go into detail about how pywb rewritting works and try to solve it

**Comment by dcgomes** [comment]
Check if newer versions of PyWB fixes this issue.

**Comment by vitgou** [comment]
Commit pushed to pywb-arquivo development branch
