### ISSUE TITLE
Website aphes.pt stoped to be crawled for unknown reason

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#745]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20050129185537/http://aphes.pt/

**What happened?**
http://aphes.pt/ is still online in 2020 but only have versions in Arquivo.pt till 2013. 

**What should have happened?**
It's a .PT website, should be collected trough the normal crawl.

**Comment by danielbicho** [comment]
@ricardobasiliopt since 2013 they are blocking us at server level.
https://arquivo.pt/wayback/20190314163457/http://www.aphes.pt/

Try to crawl the page with brozzler. If its also not possible, there is nothing we can do.
You may want or try to talk with them.
