### ISSUE TITLE
Multiple replay entries for the same url:timestamp combination 

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#748]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20001005013330/http://companhia-jesus.pt/cgi-bin/amigos/editorwww/cria_barra.pl

(issue also happens for more URLs from the IA collection)

**What happened?**
Duplicate/Triplicate entries show up with the same exact url:timestamp combination.
The only difference is the (W)ARC file where the page is stored.

**What should have happened?**
There should only be only entry per url:timestamp.
The Internet Archive also has multiple duplicate entries for these pages, but their are hidden in the interface (notice the "4 snapshots" indication next to a single time entry on the screenshot below).
![Screenshot from 2020-01-27 15-07-26](https://user-images.githubusercontent.com/2866295/73185885-cc3f2e00-4116-11ea-814f-a2b6bdbc4d0d.png)
https://web.archive.org/web/20000901000000*/http://companhia-jesus.pt/cgi-bin/amigos/editorwww/cria_barra.pl

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/73185425-efb5a900-4115-11ea-9511-17962857c396.png)
![image](https://user-images.githubusercontent.com/2866295/73186349-7919ab00-4117-11ea-80e6-f372ac70d2f5.png)

**Comment by igobranco** [comment]
The problem is that we have same information on different ARC files.

On cdx api: 
https://arquivo.pt/wayback/cdx?output=json&url=http%3A%2F%2Fcompanhia-jesus.pt%2Fcgi-bin%2Famigos%2Feditorwww%2Fcria_barra.pl&fl=url%2Ctimestamp%2Cstatus&filter=!~status%3A4%7C5

It gives us different files for same timestamp and URL, like '20000305051425'.

```
{"urlkey": "pt,companhia-jesus)/cgi-bin/amigos/editorwww/cria_barra.pl", "timestamp": "20000305051425", "status": "200", "url": "http://companhia-jesus.pt/cgi-bin/amigos/editorwww/cria_barra.pl", "filename": "FCCN-PT-HISTORICAL-ia400111.20080826054548.arc.gz", "length": "0", "mime": "text/html", "offset": "58433221", "digest": "5OQKP77BXRPFEEYMSPJDNUD2FJZVSBOL", "source": "$root:sorted_replay_index.cdxj", "source-coll": "$root"}
{"urlkey": "pt,companhia-jesus)/cgi-bin/amigos/editorwww/cria_barra.pl", "timestamp": "20000305051425", "status": "200", "url": "http://companhia-jesus.pt/cgi-bin/amigos/editorwww/cria_barra.pl", "filename": "PT-HISTORICAL-2000-GROUP-AOQ-20100830000000-00000.arc.gz", "length": "0", "mime": "text/html", "offset": "14511213", "digest": "5OQKP77BXRPFEEYMSPJDNUD2FJZVSBOL", "source": "$root:sorted_replay_index.cdxj", "source-coll": "$root"}
{"urlkey": "pt,companhia-jesus)/cgi-bin/amigos/editorwww/cria_barra.pl", "timestamp": "20000305051425", "status": "200", "url": "http://companhia-jesus.pt/cgi-bin/amigos/editorwww/cria_barra.pl", "filename": "PT-HISTORICAL-EMBEDS-2000-GROUP-BAV-20100830000000-00000.arc.gz", "length": "0", "mime": "text/html", "offset": "6215069", "digest": "5OQKP77BXRPFEEYMSPJDNUD2FJZVSBOL", "source": "$root:sorted_replay_index.cdxj", "source-coll": "$root"}
```
