### ISSUE TITLE
Pages with incomplete timestamps (HH:MM instead of HH:MM:SS) are not being indexed

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#749]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20001005013330/http://companhia-jesus.pt/cgi-bin/amigos/editorwww/cria_barra.pl
https://arquivo.pt/wayback/20001102194805/http://www.star.pt/recurso/recurso.html?id=133

**What happened?**
There are versions of pages in the IA collection WARCS that are being ignored due to malformed timestamps (missing the seconds information).
Some are found in the image indexing process, as they are referencing an image with a correctly formed timestamp (check the list in the file below).
[missing.zip](https://github.com/arquivo/pwa-technologies/files/4117787/missing.zip)

There may be many more pages that do not reference images being ignored by the parser.

**What should have happened?**
These pages should be parsed and indexed, by assuming that the seconds values are zero.
This is already being done on the Internet Archive.

**Screenshots**
Missing on Arquivo.pt
![image](https://user-images.githubusercontent.com/2866295/73187680-ae26fd00-4119-11ea-9292-f3e33097c7e2.png)
Available on the Internet Archive, with 00 as the seconds value.
![Screenshot from 2020-01-27 15-24-05](https://user-images.githubusercontent.com/2866295/73187295-19bc9a80-4119-11ea-82e2-5ae108b805ab.png)

**Comment by igobranco** [comment]
For url: http://companhia-jesus.pt/cgi-bin/amigos/editorwww/cria_barra.pl

Using sgrep on IA collection, we have confirmed that we have 21 versions on IA cdxj index.
```bash
/opt/sgrep-1.0/sgrep "pt,companhia-jesus)/cgi-bin/amigos/editorwww/cria_barra.pl" /data/indexes_split_cdx/IA.cdxj | awk '{print $2}' | wc -l
21
```

The image search indexing have detected more versions, like: 200012070901.
