### ISSUE TITLE
Relative URLs are not being properly expanded when matching images to pages

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#751]
**What is the URL that originated the issue?**
Multiple, example:
http://acores.bloco.org/desemprego.htm with tag `<img src="estrela.jpg">` 

**What happened?**
Relative URLs for images were not being properly expanded.
On page http://acores.bloco.org/desemprego.htm,
`<img src="estrela.jpg">`
was being expanded to 
http://acores.bloco.org/desemprego.htm/estrela.jpg

**What should have happened?**
`<img src="estrela.jpg">`
should be expanded to
http://acores.bloco.org/estrela.jpg

**Comment by dcgomes** [comment]
Always put link to the archived version.

**Comment by amourao** [comment]
This is not for display, this happens on the second image indexing stage (matching found images to the <img> tags in the WARCS).
This is probably one of the reasons why we have so few images.

**Comment by amourao** [comment]
Related to #747, as I found it specially prevalent in these collections.

**Comment by amourao** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Updated Image indexing code to support remaining (transformed) 2018 collections (e.g. BlocoEsquerda)](https://trello.com/c/H4acp5dK/56-updated-image-indexing-code-to-support-remaining-transformed-2018-collections-eg-blocoesquerda)
