### ISSUE TITLE
timemap path

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#755]
Is this servlet configuration still needed ?
https://github.com/arquivo/pwa-technologies/blob/18d46ce2fdf75c0e06b94484c5dcfb181b327b3a/PwaArchive-access/projects/nutchwax/nutchwax-webapp/src/main/webapp/WEB-INF/web.xml#L25-L32

That maps a specific servlet for url: https://arquivo.pt/timemap

**Comment by danielbicho** [comment]
Remove it, that is something left behind. Never hear anything about it, never saw a reference for it on old documentation since I am ehre. The servlet doesn't even exist in the code base.
