### ISSUE TITLE
Unframed replay is showing the default pywb framed header

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#763]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/noFrame/replay/20131105215853/http://f5it.pt/index.php/pt/noticias/92-mani-industrias-plasticas-otimiza-processos-de-fabrico-e-gestao-de-armazem-com-sage-erp-x3

**What happened?**
The unframed replay is showing the default pywb framed header.

**What should have happened?**
Do not show the default pywb framed header.

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/73469169-d57e0400-437d-11ea-96c2-ecd2b35edadf.png)

**Comment by danielbicho** [comment]
Fixed with https://github.com/arquivo/pywb-arquivo/commit/852d5f66c704a1b06c2a61dcc79b9dd80f82f009
