### ISSUE TITLE
Add domain level spam filter to image search

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#771]
**What is the URL that originated the issue?**
Any image search.

**What happened?**
No domain level spam filter.

**What should have happened?**
Documents should have a spam field that is used by Solr by default 
The spam filter classifier should be a step like the Safe score classification to allow for updates in the Spam domains.
Documents from all collections will be resent to Solr, when there is an update in the domains that are classified as Spam.

**Screenshots**

**Comment by amourao** [comment]
Added spam and blocked fields to Solr documents.

**Comment by igobranco** [comment]
> Documents from all collections will be resent to Solr, when there is an update in the domains that are classified as Spam.

So we need a new script that updates the Spam field on the jsonl files? And after the its run, we post the information to solr again?

**Comment by amourao** [comment]
> > Documents from all collections will be resent to Solr, when there is an update in the domains that are classified as Spam.
> 
> So we need a new script that updates the Spam field on the jsonl files? And after the its run, we post the information to solr again?

Only for the new index, the procedure for the current issue is different.
I'm going to open a new issue to setup the creation of that script for the new data.
