### ISSUE TITLE
The form options should be open to display the parameters on the advance search

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#775]
The form options should be open to display the parameters on the advance search:

https://m.arquivo.pt/advanced.jsp?query=sapo+type%3Apdf&l=pt&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2019

The Format field is collapsed although it has a parameter type:pdf.

![image](https://user-images.githubusercontent.com/13105310/73950050-331cce00-48f3-11ea-935c-d3db52741d08.png)

![image](https://user-images.githubusercontent.com/13105310/73950008-1e403a80-48f3-11ea-928f-e697ffbfbcdb.png)

**Comment by igobranco** [comment]
I didn't understand @danielbicho .
What should happen? Open all collapsed blocks that have at least one advanced option?

**Comment by igobranco** [comment]
Won't do, this problem will be fixed by #787.
