### ISSUE TITLE
Cdxj files with incorrect lines

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#779]
**What is the File that originated the issue?**
/data/indexes_cdx/sorted_replay_index.cdxj

**What happened?**
Wrong Entries on CDXJ:

1. Wrong surt (I suspect it happened more often):

- 01_03_03).pdf 20170804071359 {"url": "youtube-dl:http://www.umic.pt/images/stories/osic/MetodoAvaliacao2003_(01_03_03).pdf", "mime": "application/vnd.youtube-dl_formats+json", "digest": "FODZ7MHEQTD4GJXBWK26MYSLTYKO7Q35", "length": "757", "offset": "22231994", "filename": "umic-20170804071315121-00003-lw8kxbh0.warc.gz"}
- If we try to use the package [surt](https://pypi.org/project/surt/) it is solved now.

2. Urlopen Error

- <urlopen error [Errno -3] Temporary failure in name resolution>

3. Arcname:

- Arcname:	http://p68.arquivo.pt:8080/browser/files/AWP18/AWP18-PT/AWP18-PT-20150825163859075/arcs/IAH-20150829104722-07226-p81.arquivo.pt.arc.gz

4. Diferent Errors

- Error -3 while decompressing: incorrect data check
- Error -3 while decompressing: invalid distance too far bac

- Invalid ARC record, first line: ['<!DOCTYPE', 'HTML', 'PUBLIC', '"-//W3C//DTD', 'HTML', '4.0', 'Transitioneig/EN">']

- Unknown archive format, first line: ['L0\xab\xf2\xfa\xbeM.O.k\rxC\xaf\xbf(\x1d\xddy\xb6`~\x9b\x9cs\xb7L\x8c\x1d\xf2s\xe8\x10}w\xb7I\xb4F[\xd3\xe0_D\xe0\x00\xdb\xad\x1cp7\x10\xdci\x13\x97W\xfc\x80\x0bV\xc6+\x13\x9f\x95\xc94\xf4\x83\x8a`7\xd4\xb1-\xe0\xf9E\xe9R\xd0\xf1\x94\xb6\xd3W\x16Z\xf18\xd4\x80;\xe6uW+\x13O\xb0\xa4\xf0\xa2\xf4+\x15\xc0\xe9\xbei2/\xa8\x1c\xb9&\xb7lw\xbc\xd0\x11\x87\xf9\xd7g\xb6\x0b\rs\xd7ef`s\xb7ML\x87\xfbL\xde']

5. no status code and no revist

- be,lesoir,mad)/event/304361-impair-et-pere-de-ray-cooney/lesoir.be 20141128073049 {"url": "http://mad.lesoir.be/event/304361-impair-et-pere-de-ray-cooney/lesoir.be", "mime": "text/html", "digest": "Z2NCAPBZPCZKLPSEFNLHVSQACE4SX2D6", "length": "16547", "offset": "25998446", "filename": "IAH-20141128072511-35045-p12.arquivo.pt.arc.gz"}	

- com,mediafire,download394)/cpy2mqgbjy1g/hhocv8ktoim/scp+indienation.com.br.rar 20090705072153 {"url": "http://download394.mediafire.com/cpy2mqgbjy1g/hhocv8ktoim/scp+indienation.com.br.rar", "mime": "no-type", "digest": "GESQJBHPNUG5MR3SXLLHECZDVXUV67VS", "length": "186", "offset": "70686638", "filename": "IAH-20090705070122-16414-awp01.fccn.pt.arc.gz"}

6. screenshot in which do not work the replay

- screenshot:http://www.eeagrants.gov.pt/component/mailto/?link=90e40280815a066df9dbcc6c74fed9682f4f4958&template=ju_cobles&tmpl=component 20180702233938 {"url": "screenshot:http://www.eeagrants.gov.pt/component/mailto/?link=90e40280815a066df9dbcc6c74fed9682f4f4958&template=ju_cobles&tmpl=component", "mime": "image/jpeg", "digest": "VYL6H7XNJADJVUPNLC6ZEYBVTLSYFP4V", "length": "16777", "offset": "75584490", "filename": "raq-eeagrants-20180702214729722-00038-sypmah5r.warc.gz"}

7. thumbnail in which do not work the replay

- thumbnail:http://www.eeagrants.gov.pt/component/mailto/?link=2e6289ec15f4abce6467bf4ed4b86423288bbe94&template=ju_cobles&tmpl=component 20180710002437 {"url": "thumbnail:http://www.eeagrants.gov.pt/component/mailto/?link=2e6289ec15f4abce6467bf4ed4b86423288bbe94&template=ju_cobles&tmpl=component", "mime": "image/jpeg", "digest": "B64OUNLPRMYUSDJ77WE33RFT7Q4UGQMG", "length": "3040", "offset": "91707867", "filename": "raq-eeagrants-20180709210958602-00089-sypmah5r.warc.gz"}

8. youtube-dl  in which do not work the replay

- youtube-dl:http://www.english.umic.pt/images/stories/publicacoes2/Reflections_on_European_Policy_Outlook_RFID.pdf 20170825200222 {"url": "youtube-dl:http://www.english.umic.pt/images/stories/publicacoes2/Reflections_on_European_Policy_Outlook_RFID.pdf", "mime": "application/vnd.youtube-dl_formats+json", "digest": "64KEYRKC5JYE3QYFLGRZV7T24UQBZD2W", "length": "780", "offset": "176700705", "filename": "raq-umic-20170825161841528-00001-5qvhks7f.warc.gz"}

10. dns in which do not work the replay

- dns:-demilovato.blogs.sapo.pt 20110702025120 {"url": "dns:-demilovato.blogs.sapo.pt", "mime": "text/dns", "status": "200", "digest": "TQ5OQPUO4ZXBJJANIJJTHZKGOOMASSIM", "length": "120", "offset": "79743775", "filename": "IAH-20110630152629-00025-p9.arquivo.pt.arc.gz"}

11. Example of lines with different template:

- 80,66,136,207)/1pixtrans.gif 20001013015342 {"status": "200", "url": "http://207.136.66.80/1pixtrans.gif", "filename": "PT-HISTORICAL-EMBEDS-2000-GROUP-AZN-20100830000000-00000.arc.gz", "length": "0", "mime": "im", "offset": "7152389", "digest": "265QYK5YHQAUSK6YUG5L23A4HGT54U3X"}

- 82,96,32,72)/robots.txt 20090520123755 {"url": "https://72.32.96.82/robots.txt", "mime": "text/html", "status": "404", "digest": "S4YEZ5NQPQLTIP5ZK6MFPKLFQWYPZPER", "length": "370", "offset": "39406476", "filename": "IAH-20090520123245-00044-awp02.fccn.pt.arc.gz"}	

**Number of lines**
_original entries:_
_possible entries to be removed:_ 85000000 (more or less)

**Comment by PedroG1515** [comment]
The lines:
"Arcname:"
"Error -3"
"<urlopen error"
"Invalid ARC record"
"Unknown archive format"

were removed

**Comment by dcgomes** [comment]
CDXj were cleaned as good as possible. Requires full CDX reindexing. Won't do for now.
This problem does not impact on the quality of the service. It just adds unnecessary space on the indexes.
