### ISSUE TITLE
GZipped HTML records are not being parsed to find images

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#784]
**What is the URL that originated the issue?**
WARCs with GZipped records

**What happened?**
GZipped HTML is not being decompressed and thus, not parsed to find <img> records

**What should have happened?**
Stream should be decompressed

**Screenshots**

**Comment by amourao** [comment]
Issue also happens with DEFLATE and Brotli compressed records

**Comment by amourao** [comment]
https://github.com/arquivo/image-search-indexing/commit/1b7d9014076e6d82d2c08e37957d041567b9ab4a GZip and Deflate should work now

https://github.com/arquivo/image-search-indexing/commit/4024b2f4ffd87f6943f01cdd0eb0c95c61e00fbc Tried to add Brotli support, but it is giving an error, at least when working with Chunked data

**Comment by nikito7** [comment]
Cloudflare tunnels use Brotli
