### ISSUE TITLE
CDXJ fl param isn't working

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#789]
**What is the URL that originated the issue?**
https://m.arquivo.pt/search.jsp?query=fccn.pt&l=en&dateStart=01%2F01%2F1996&dateEnd=17%2F02%2F2020

That calls the CDX API with:
https://m.arquivo.pt/wayback/cdx?output=json&url=http%3A%2F%2Ffccn.pt&fl=url%2Ctimestamp%2Cstatus&filter=!~status%3A4%7C5&from=19960101&to=20200217

**What happened?**
The **fl** param isn't working.

**What should have happened?**
Work or review the [Arquivo.pt CDXJ Server API](https://github.com/arquivo/pwa-technologies/wiki/URL-search:-CDX-server-API) on github that is like a copy of [pywb CDXJ Server API](https://pywb.readthedocs.io/en/latest/manual/cdxserver_api.html). 

**Impact**
Very lower. Currently the **fl** is used to reduce the network sent to the client browser.

**Comment by danielbicho** [comment]
@igobranco you did solve this right? the parameter is now **field** instead of **fl**. Confirm and close plz

**Comment by igobranco** [comment]
> @igobranco you did solve this right? the parameter is now **field** instead of **fl**. Confirm and close plz

Yes.
