### ISSUE TITLE
WildCard Problem- Wayback Machine Query

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#79]
Originally reported on Google Code with ID 80
```
The query produced Wayback machine through a wildcard, take with example the follow
http://arquivo.pt/wayback/wayback/*/sapo.pt is not correctly producing the css. 

```

Reported by `HugoHAViana` on 2014-10-22 15:21:44

**Comment by dcgomes** [comment]
Test if this issue will be fixed with the adoption of PyWB for the Janus release.

**Comment by Fernando-Melo** [comment]
It will stay the same as it was.

If we want to present a better page when using the wildcard, we have to make changes also in the Search.jsp page.

Currently when we search for a url in Arquivo, as in the following example:
http://arquivo.pt/search.jsp?l=en&query=wordpress.com&btnSubmit=Search+the+Archive

The Wildcard page: http://arquivo.pt/wayback/*/wordpress.com is embedded in our search.jsp page.

If we change the css for the wildcard (http://arquivo.pt/wayback/*/wordpress.com) we will be automatically changing the search page (http://arquivo.pt/search.jsp?l=en&query=wordpress.com&btnSubmit=Search+the+Archive)

Postpone this to a future release?

**Comment by Fernando-Melo** [comment]
Done in p27
