### ISSUE TITLE
Advanced search button dis formatted 

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#790]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/

**What happened?**
The advanced search button isn't positioned correctly. 

**What should have happened?**
The pages, images and advanced search buttons on same row. 

**Screenshots**
On chrome tools has an iPhone 4:
![image](https://user-images.githubusercontent.com/67018/74744411-1b7e0780-525a-11ea-9ab3-e9d588e100e3.png)

On my device, android chrome:
![image](https://user-images.githubusercontent.com/67018/74744704-99daa980-525a-11ea-8895-d0451742af43.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
