### ISSUE TITLE
Change between image search, page search and advanced search buttons

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#792]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/images.jsp?l=en

**What happened?**
It is not possible to change to page search or advanced search

**Screenshots**
![page](https://user-images.githubusercontent.com/25795364/74926735-45583b00-53ce-11ea-9d71-68283db18436.PNG)

**Comment by igobranco** [comment]
Fixed.
