### ISSUE TITLE
Some images/html files from the BlogsSapo2018 collection are not being served

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#797]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20180803201845/https://cdn.olhares.pt/client/files/foto/medium/335/3358705.jpg
https://arquivo.pt/wayback/https://www.readinga-z.com/images/tab-phonics-image.png

**What happened?**
Images and pages are not being displayed; PyWb returns 404 for the corresponding WARCs.
For example, returns 404:

http://p89.arquivo.pt:8080/arcproxy/arcproxy/WEB-20180803201448803-p84.arquivo.pt.warc.gz

while the original file still exists:

http://p65.arquivo.pt:8080/browser/files/BlogsSapo2018/20180803082913/warcs/WEB-20180803201448803-p84.arquivo.pt.warc.gz

**What should have happened?**
Resource should be loaded

**Screenshots**

**Comment by igobranco** [comment]
Fixed.

Reason:
The BlogsSapo2018 collection wasn't populated on arcproxy.
And the alarms were incorrect. I've also changed the URLs used on alarms.
