### ISSUE TITLE
Python 2.7 is deprecated and we are starting to have problems installing libs

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#800]
:stderr: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

We may need to start thinking about to change ansible playbooks to use python 3 interpreter as basis.

**Comment by danielbicho** [comment]
We are starting to dockerize our services and with CentOS 8 we will start to install python through the package manager (python 3.6), if we really need to that. closing

**Comment by igobranco** [comment]
We are using python 3.5 on everything (pywb and memorial), so this isn't currently a problem.
