### ISSUE TITLE
Change dedupField to URL when searching for site

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#805]
**What is the URL that originated the issue?**
https://arquivo.pt/search.jsp?l=pt&btnSubmitTop=Pesquisar+no+Arquivo&adv_and=&adv_phr=economia+colaborativa&adv_not=&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2019&sort=relevance&format=all&site=www.publico.pt&hitsPerPage=10&dedupField=site&hitsPerDup=1

**What happened?**
The user complain that there was too many duplicate results when searching for "economia colaborativa" on site www.publico.pt. The hitsPerDup is ignored on this case, which makes  senses.

**What should have happened?**
It should not display so many duplicate results. Better results will be retrieved if when an user searches within a specific site, the dedup field should be changed to deduplicate by url.

**Screenshots**
Results now
![image](https://user-images.githubusercontent.com/13105310/75366251-5dd8c180-58b6-11ea-9cc3-3aa0ffc1d55a.png)

Results after
![image](https://user-images.githubusercontent.com/13105310/75366354-86f95200-58b6-11ea-8242-ad4b7cacdaa1.png)

The backend supports this, but the same functionality doesn't exist on the TextSearchAPI. The idea is to by default:
| Search type | Expected Behavior |
| -- | -- | 
| Normal search | use the dedupField=site with dedupValue=2 |
| Search by site (eg site:www.public.pt) |  use dedupField=URL with dedupValue=2 |

- [x] TextSearch API needs to by default use the URL has the dedupField if siteSearch parameter is used with same default value of 2.
- [x] TextSearch API could expose the dedupField {"site","url","collection", ...}, by default "site" if "siteSearch" not defined/empty or "url".
- [x] TextSearch API could expose the dedupValue by default 2.

**Comment by amourao** [comment]
We will increase the items returned (maxItems) to 2000, so that more results appear when the user clicks in the "more results" link

**Comment by VascoRatoFCCN** [comment]
This has been addressed, see https://github.com/arquivo/pwa-technologies/issues/1115
