### ISSUE TITLE
Deduplication by URL/HOST should ignore the protocol and www prefix

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#807]
Fulltext search and ImageSearch should handle URLs as wayback.

Should all be considered the same resource.

https://publico.pt
https://www.publico.pt
http://www.publico.pt
http://publico.pt

**Screenshots**
![image](https://user-images.githubusercontent.com/13105310/75367839-ce80dd80-58b8-11ea-9e45-446bac424284.png)

**Comment by amourao** [comment]
Fixed in the Image Search API

**Comment by amourao** [comment]
Deployed to preprod
