### ISSUE TITLE
Wrong title in the results list

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#810]
**What is the URL that originated the issue?**
Diference between desktop and mobile:
1. https://preprod.arquivo.pt/search.jsp?l=pt&query=leiria&btnSubmit=Pesquisar
2. https://m.preprod.arquivo.pt/search.jsp?l=pt&query=leiria&btnSubmit=Pesquisar

**Screenshots**

![3](https://user-images.githubusercontent.com/25795364/75436004-c58d1c00-594b-11ea-9be1-5e73f8b39070.JPG)

**Comment by igobranco** [comment]
The problem is related to the search page API (text search API) and not the front end.

**Comment by igobranco** [comment]
![image](https://user-images.githubusercontent.com/67018/75451184-faa76780-5967-11ea-9703-7747450c0a5f.png)

**Comment by danielbicho** [comment]
fixed
