### ISSUE TITLE
Buttons "Table" and "List" disappeared on mobile

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#818]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=fccn.pt&l=en&dateStart=01%2F01%2F1996&dateEnd=03%2F03%2F2020

**What happened?**
Buttons "Table" and "List" disappeared on mobile

**Screenshots**
![1](https://user-images.githubusercontent.com/25795364/75782980-ab8e7780-5d57-11ea-9e2f-0facf2e0e228.JPG)

**Comment by pcabritafccn** [comment]
This is issue is now closed.
