### ISSUE TITLE
Workflow Image/Page Search between pages.

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#819]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/images.jsp?query=fccn&dateStart=01/01/1996&dateEnd=09/03/2020&pag=prev&start=0&l=pt

**What happened?**
1. Search fccn
2. Change to Images
3. Change datepicker
4. Change to next image page

**What should have happened?**
The datepicker did not maintain the state.  -->**This happen in the Image and Page Search**

**Screenshots**
1. First page
![3](https://user-images.githubusercontent.com/25795364/76206112-589f3f00-61f3-11ea-8863-286b236c39d1.JPG)

2. Second Page
![2](https://user-images.githubusercontent.com/25795364/76205683-a4051d80-61f2-11ea-8d2d-f706fc0ab35b.JPG)

**Comment by igobranco** [comment]
An option is to execute the search when the user changes a datepicker value, and also change the datepicker 'ok' button label to 'search'.

We need more internal discussion about this before doing changes.

**Desktop:**
![image](https://user-images.githubusercontent.com/67018/76426238-b0c87380-63a2-11ea-8896-3578cf7895d1.png)

**Mobile:** 
![image](https://user-images.githubusercontent.com/67018/76426314-cfc70580-63a2-11ea-9ea4-41dd40fefa43.png)

**Comment by igobranco** [comment]
Won't fix.
Nevertheless we have decided that the **OK** button on desktop datepicker should be greater.
