### ISSUE TITLE
Page Advanced Search Negation Option 

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#822]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=fccn+-Funda%C3%A7%C3%A3o&l=pt&dateStart=01%2F01%2F1996&dateEnd=11%2F03%2F2020

**Screenshots**
![8](https://user-images.githubusercontent.com/25795364/76400807-d476c400-6378-11ea-99bd-12ecdc8f0191.JPG)

**Comment by danielbicho** [comment]
On a previous commit I removed a code line that was forcing the request encoding to UTF8.
Then this problem arise. The tomcat configuration was forcing to interpret an URI with the same encoding as the Content. Removed that option from tomcat and everything is working.
