### ISSUE TITLE
Diference between previous and next buttons - Ipad view

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#823]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=fccn+type%3Apdf&dateStart=01/01/1996&dateEnd=11/03/2020&pag=next&start=10&hitsPerPage=10&hitsPerDup=2&dedupField=site&l=pt

**What happened?**
1. m.prepod.arquivo.pt on Ipad view (768x1024)
2.  Search fccn type:pdf
3. Go to the second page

**Screenshots**

![1](https://user-images.githubusercontent.com/25795364/76412824-3ab91200-638c-11ea-81b6-1ffc85cb543f.JPG)

**Comment by pcabritafccn** [comment]
This issue is now fixed.
