### ISSUE TITLE
The highlight of current version was removed

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#824]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/wayback/19980205082901/http://www.caleida.pt/saramago/

**What happened?**
The highlight of current version was removed.

**What should have happened?**
The current version should be highlighted on left side list of version.

Review the "viewing-version" css class. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/76443890-0741ac00-63bb-11ea-8eed-5aa90826807f.png)

**Comment by pcabritafccn** [comment]
This is now solved.

**Comment by igobranco** [comment]
Isn't working.

**Comment by pcabritafccn** [comment]
This issue is now solved.
