### ISSUE TITLE
Footer with background at blue instead of gray

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#827]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/

**What happened?**
The footer should be blue instead of gray.

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/76538572-6ebd3180-6477-11ea-8200-6d88fff6f004.png)

**Comment by pcabritafccn** [comment]
The footer works better with neutral colours. So it´s initial blue colour was removed and replaced by grey.
