### ISSUE TITLE
Increase the indentation of the second (related) search result

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#828]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=fccn&l=pt&dateStart=01%2F01%2F1996&dateEnd=12%2F03%2F2020

**What happened?**
The related search result is too close to the first one. It gives the impression that it's a bug instead of a feature. The google have a bigger indentation. 

**What should have happened?**
Increase the indentation of the second (related) search result, like it was a couple of weeks before. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/76538687-9b714900-6477-11ea-96b7-e60032e08be7.png)

**Comment by pcabritafccn** [comment]
This issue is now closed.
