### ISSUE TITLE
Mouse hover on calendar didn't change colors

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#830]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/

**What happened?**
When the user pass the mouse above the calendar displayed, ex. homepage, it didn't invert the colors like the other buttons.

**What should have happened?**
It should invert, change, the colors like the Page, Image and Advanced Search buttons. 
For the user the calendar should have the same presentation like any other type of action element. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/76629728-aa6b0080-6536-11ea-8dbb-95e50f70f802.png)

**Comment by pcabritafccn** [comment]
This is issue is now solved.
