### ISSUE TITLE
No results displayed on mobile version

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#833]
Search for semplanos.com in Desktop, presents 32 versions:
https://arquivo.pt/search.jsp?l=pt&query=semplanos.com&btnSubmit=Pesquisar

If we change to mobile, no results are presented:
https://m.arquivo.pt/search.jsp?l=pt&query=semplanos.com&btnSubmit=Pesquisar

Seems to be fixed on WebApp milestone but please double-check situation:
https://m.preprod.arquivo.pt/search.jsp?l=pt&query=semplanos.com&btnSubmit=Pesquisar

**Comment by igobranco** [comment]
Everything seams ok. The current differences between desktop production version and the preprod mobile version is the gigantic_index_1_v2.cdxj isn't available on preprod.
@PedroG1515 is there any reason for this file not available on preprod environment ?

**Comment by igobranco** [comment]
After a prieve talk with @PedroG1515  the gigantic_index_1_v2.cdxj index isn't available on purpose on preprod environment. 
I'm going to close this issue because it is fixed on current next release that is being closed.
