### ISSUE TITLE
Add menu and option text on wayback header on desktop view

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#835]
On header using wider screen:
1. add the "Menu" text of the left near the menu icon.
2. add the "Options" text on the right near the replay options icon.

**Comment by igobranco** [comment]
I've added the required text, but it needs a tweak of css.

![image](https://user-images.githubusercontent.com/67018/76992119-a2e69580-6942-11ea-84dc-798dee11b0e7.png)

**Comment by igobranco** [comment]
And on homepage:
![image](https://user-images.githubusercontent.com/67018/76993447-c27ebd80-6944-11ea-8229-072790ea80af.png)

**Comment by igobranco** [comment]
@pcabritafccn please tweak the header on homepage and wayback.

**Comment by pcabritafccn** [comment]
Working on it.

**Comment by pcabritafccn** [comment]
This issue is now solved.
