### ISSUE TITLE
Put EAWP23 in production

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#836]
The **EAWP23** special collection about the European elections of 2019 should be put in production.

Tasks (the 2nd and the 3rd needs to be done after the 1st):

- [x] Replay @igobranco 
- [x] Image search @amourao 
- [x] Page search @danielbicho 
- [x] short link to search collection https://arquivo.pt/ee2019 @igobranco

**Comment by amourao** [comment]
EAWP23 image search deployed to preprod.

**Comment by danielbicho** [comment]
FTS indexes ready

**Comment by igobranco** [comment]
Replay on preprod and production environments.

**Comment by igobranco** [comment]
Next week we need to deploy the image and FTS indexes in production.

**Comment by igobranco** [comment]
I've added the short link page for this collection on [viagens no tempo repository](https://github.com/arquivo/viagens-no-tempo/tree/master/ee2019)

**Comment by igobranco** [comment]
I've added the apache httpd configuration need to redirect arquivo.pt/ee2019 still need a production deployment...

**Comment by igobranco** [comment]
@danielbicho have warn that the EAWP23 collection have been indexed using a multi-version profile.
This profile have a bug that prevent us to search by collection.

This could be fixed using #845.

**Comment by igobranco** [comment]
@amourao can you put the images in production?

**Comment by amourao** [comment]
@igobranco started now

**Comment by amourao** [comment]
Image search deployed
