### ISSUE TITLE
Visualization and Encoding Problems

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#837]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/wayback/20080320054537/http://diznao.blogs.sapo.pt/

**What happened?**
There are some encoding problems. For instance, replay bar on março.

It happens on my computer, @amourao reported the same.
Also if I try to open it on a fresh browser, incognito mode or firefox the replay bar is not loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/13105310/76993630-0a054980-6945-11ea-802a-8ebcef75cc88.png)

![image](https://user-images.githubusercontent.com/13105310/76993992-a3346000-6945-11ea-9907-dcac41c9af8c.png)

**Comment by igobranco** [comment]
Also there is an error when opening https://m.preprod.arquivo.pt/wayback/20080320054537/http://diznao.blogs.sapo.pt/ directly on incognito mode.
