### ISSUE TITLE
Menu and options display on mobile with labels

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#838]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/wayback/20170223165940/https://jornadas.fccn.pt/

**Screenshots**
![1](https://user-images.githubusercontent.com/25795364/77051240-e680e400-69c2-11ea-8cfc-13736eb99733.JPG)

**Comment by igobranco** [comment]
Closing me and @pcabritafccn  are working on it on issue #835.
