### ISSUE TITLE
Strange element like a | char on page search results

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#839]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=fccn&l=pt&dateStart=01%2F01%2F1996&dateEnd=19%2F03%2F2020

**What happened?**
The | char is on a strange position, view the screenshot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/77058514-7592f980-69cd-11ea-8c11-44f392598fc3.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
