### ISSUE TITLE
(Try again to) Create Arquivo.pt English Wikipeda page

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#840]
**What is the URL that originated the issue?**
https://en.wikipedia.org/wiki/Portuguese_Web_Archive

**What happened?**
It does not exist

**What should have happened?**
It should exist.

**Screenshots**

**Comment by amourao** [comment]
https://en.wikipedia.org/wiki/Arquivo.pt is redirecting to the FCT page.

Examples of other archive wiki pages:
- https://en.wikipedia.org/wiki/Webarchiv
- https://en.wikipedia.org/wiki/PADICAT
- https://en.wikipedia.org/wiki/Pandora_archive
- https://en.wikipedia.org/wiki/Internet_Archive

**Comment by amourao** [comment]
Previously written PT and EN texts

[ArquivoPTWikipediaPT.txt](https://github.com/arquivo/pwa-technologies/files/5051361/ArquivoPTWikipediaPT.txt)
[ArquivoPTWikipediaEN.txt](https://github.com/arquivo/pwa-technologies/files/5051362/ArquivoPTWikipediaEN.txt)

**Comment by amourao** [comment]
Wikimedia Portugal will help revise PT page and recreate EN page with a more neutral tone in line with editorial guidelines.

**Comment by dcgomes** [comment]
Arquivo.pt vai melhorar a[ versão em português](https://pt.wikipedia.org/wiki/Arquivo.pt) e pedir feedback à Wikipedia
Usar [Testes](https://pt.wikipedia.org/w/index.php?title=Usu%C3%A1rio(a):ArquivoPTBot/Testes&action=edit&redlink=1&editintro=Predefini%C3%A7%C3%A3o%3AP%C3%A1gina+de+testes+de+utilizador&preload=Predefini%C3%A7%C3%A3o%3AP%C3%A1gina+de+testes+de+utilizador%2Fpreload) antes de submeter a nova versão do artigo
Intro mais focada no Arquivo.pt
Adicionar [História](https://sobre.arquivo.pt/pt/imprensa/historia/)
Evitar dar a ideia de auto-promoção, através da utilização de referências externas
Adicionar referências externas por exemplo para artigos científicos ou notícias nos sites das editoras ou jornais
Ter em consideração [Fontes confiáveis](https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:Fontes_confi%C3%A1veis)
Usar [Cite web template](https://en.wikipedia.org/wiki/Template:Cite_web#Using_%22archive-url%22_and_%22archive-date%22_(and_optionally_%22url-status%22)_for_webpages_that_have_been_archived)
Referir conteúdos arquivados sempre que possível
Usar [Save PageDown](https://arquivo.pt/savepagenow) para gravar páginas imediatamente
Ver [Arquivo.pt in a nutshell: overview of services and activities](https://github.com/arquivo/pwa-technologies/wiki/Arquivo.pt-in-a-nutshell:-overview-of-services-and-activities)
Quando se chegar a uma versão de qualidade razoável validada pela WikipediaPT então traduzir para inglês.https://en.wikipedia.org/wiki/Arquivo.pt_-_the_Portuguese_web-archive

**Comment by dcgomes** [comment]
Leave this task to the Wikipedia community of editors
