### ISSUE TITLE
Amplify Brozzler Cluster with Docker Swarm

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#842]
Each individual Brozzler Cluster is running currently with 40 brozzler-workers on a server machine.
We want to tune and increase the cluster capacity to be able to crawl more daily pages in 24 hours.

- [x] Configure a Docker Swarm to launch more brozzler-workers containers and warcprox containers
- [x] Scale RethinkDB

**Comment by vitgou** [comment]
Brozzler Cluster is relying on Docker Swarm. Currently, internally available.
