### ISSUE TITLE
When collapsing the replay list, a big blank space between the replay list and the footer is left open

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#844]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=sapo.pt

**What happened?**
Start to expand the replay list, specially dates with lots of versions, since they will need more view space. Then collapse some back, and you can see that the spacing between the replay list and the footer doesn't reset to its original spacing.

**Screenshots**
The Replay list is on top of the footer, but I have just seen this happening with the Chrome DevTools, is not the problem I am reporting:

![image](https://user-images.githubusercontent.com/13105310/77294117-8dbf8d00-6cdb-11ea-981e-bccbf9a14c5a.png)

After expanding and collapsing back:
![image](https://user-images.githubusercontent.com/13105310/77294140-9b751280-6cdb-11ea-887c-3ce0fcefed5d.png)

**Comment by dcgomes** [comment]
Check if problem prevails with the latest developments.

**Comment by dcgomes** [comment]
Won't fix. It is a detail without impact on the UX or functionality of the service.

**Comment by pcabritafccn** [comment]
Solved: not happening now.
