### ISSUE TITLE
Image preview shows footer

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#856]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/images.jsp?query=fccn&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-03-26&dateStart=01%2F01%2F1996&dateEnd=26%2F03%2F2020#card

**What happened?**
When opening a image to preview it. If we scroll, it shows the footer.

**What should have happened?**
Do not show the footer

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/77642721-05005580-6f56-11ea-9173-e6e6a606ab5f.png)

**Comment by dcgomes** [comment]
Why shouldn't the footer appear?

**Comment by igobranco** [comment]
> Why shouldn't the footer appear?

Well maybe we don't need to change it... My idea to hide the footer is related to the old #603 issue. But given this is the footer and not the search form, we could do nothing.

Closing this issue has won't do.
