### ISSUE TITLE
Table of version does not show anything on Chrome

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#857]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=dn.pt&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-03-26&dateStart=01%2F01%2F1996&dateEnd=26%2F03%2F2020

**What happened?**
Search by url and then change to table mode on chrome desktop and mobile. The Table of versions appears empty despite existing versions. On other browsers work ok. Only searching using "dn.pt"

**What should have happened?**
It should have presented the versions also on the Table of versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/77643442-46ddcb80-6f57-11ea-87cf-b095ce8922e2.png)

**Comment by PedroG1515** [comment]
It is happen again.

https://preprod.arquivo.pt/search.jsp?hitsPerPage=10&query=fccn.pt&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-04-02&dateStart=01%2F01%2F1996&dateEnd=02%2F04%2F2020

**Comment by igobranco** [comment]
Fixed.
