### ISSUE TITLE
Inconsistent placeholders on Advanced Image Search filters

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#859]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/advancedImages.jsp?query=&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-03-26&dateStart=01%2F01%2F1996&dateEnd=26%2F03%2F2020

**What happened?**
"Select One" instead of "Selecione"
"mostrar todas" should be "Mostrar todas"

**What should have happened?**
The three dropdowns should be consistent

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/77644373-cd46dd00-6f58-11ea-8145-9d6972084b53.png)

**Comment by amourao** [comment]
![image](https://user-images.githubusercontent.com/2866295/77644790-89a0a300-6f59-11ea-8631-a15c99d92cd8.png)

"show all" -> "Show all"

**Comment by igobranco** [comment]
1. The "Select One" was fixed yesterday because the page were having a javascript error.
2. Fixed the case of the "Show all" text.
