### ISSUE TITLE
Encoding problems on Image Replay Screen 

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#860]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/wayback/20040311070234/http://www.maisfutebol.iol.pt/

**Screenshots**

![1](https://user-images.githubusercontent.com/25795364/77644703-5827d780-6f59-11ea-8728-7b1fcfbee7d3.JPG)

**Comment by igobranco** [comment]
Already fixed.
