### ISSUE TITLE
Header isn't full width on big screens

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#861]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/?l=pt

**What happened?**
Header isn't full width on big screens.

**What should have happened?**
It should present the menu header on full width

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/77644605-2b73c000-6f59-11ea-94a8-636650b6dada.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
