### ISSUE TITLE
Resize image preview breaks

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#862]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/images.jsp?query=fccn&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-03-26&dateStart=01%2F01%2F1996&dateEnd=26%2F03%2F2020#card

**What happened?**
![image](https://user-images.githubusercontent.com/13120352/77644949-d08e9880-6f59-11ea-88de-3d83cb2650e4.png)

But when we resize the window the UI breaks:
![image](https://user-images.githubusercontent.com/13120352/77644992-e439ff00-6f59-11ea-819b-a8595d990ffd.png)

**What should have happened?**
Mantain aspect.

**Comment by pcabritafccn** [comment]
Closed: the new HTML behaviour don´t have this issue.
