### ISSUE TITLE
List of versions on replay does not show the last lable on windows

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#864]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/wayback/20040311070234/http://www.maisfutebol.iol.pt/

**Screenshots**

![2](https://user-images.githubusercontent.com/25795364/77645811-4ba47e80-6f5b-11ea-91ed-528b9b8b2e76.JPG)

**Comment by pcabritafccn** [comment]
This issue is now solved.
