### ISSUE TITLE
Maintain the same date format on all UIs

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#865]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/wayback/20000301082139/http://www.fccn.pt:80/

**What happened?**
![image](https://user-images.githubusercontent.com/13120352/77645411-97a2f380-6f5a-11ea-9254-e0b7722bf5ee.png)

On the left drill-down the date format should be the same as in all the other UIs.
3 Dezembro às 04:12

Also happens here:
![image](https://user-images.githubusercontent.com/13120352/77645705-1435d200-6f5b-11ea-8b5f-82aec13653a8.png)

**What should have happened?**
Use the same date format on all UIs: dd month, yyyy

**Comment by igobranco** [comment]
I think the format was:
```
PT: day month às hh:mm, year
EN: day month at hh:mm, year
```
Note, hide year if it already displayed.

**Comment by igobranco** [comment]
- [ ] Review the wayback header to include the hour/minute.
- [ ] Review replay options  to include the hour/minute.

**Comment by igobranco** [comment]
![image](https://user-images.githubusercontent.com/67018/77772372-eecec400-703f-11ea-9f46-f2f8d1171b66.png)

![image](https://user-images.githubusercontent.com/67018/77772385-f68e6880-703f-11ea-962b-b5530d27389c.png)

**Comment by igobranco** [comment]
Missing the cases of:
- [ ] Each image search result:
![image](https://user-images.githubusercontent.com/67018/77778919-ab795300-7049-11ea-8dac-32f06a2a7a60.png)

- [ ] Each image search result viewer, when the user opens each image:
![image](https://user-images.githubusercontent.com/67018/77779001-c64bc780-7049-11ea-84ae-a81641b4a171.png)
