### ISSUE TITLE
Reinclude link "List versions" on the drill-down 

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#866]
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/wayback/19990423194008/http://www.fccn.pt:80/

**What happened?**
Reinclude link "List versions" on the drill-down:
https://m.preprod.arquivo.pt/wayback/19990423194008/http://www.fccn.pt:80/

https://preprod.arquivo.pt/wayback/19990423194008/http://www.fccn.pt:80/

![image](https://user-images.githubusercontent.com/67018/77657904-d7bfa180-6f6d-11ea-962d-11a770f8a3ef.png)

**Comment by igobranco** [comment]
@pcabritafccn please style the new list of versions link.
