### ISSUE TITLE
Image Search filter query by collection is not working correctly

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#874]
**What is the URL that originated the issue?**
https://arquivo.pt/images.jsp?l=pt&query=collection:EAWP23%20verdes&dateStart=01/01/1996&dateEnd=31/12/2019

**What happened?**
Results for "verdes" show up for all collections

**What should have happened?**
Results for "verdes" should be filtered to collection EAWP23

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/77754230-ce444100-7022-11ea-8712-5dbd76b91779.png)

**Comment by igobranco** [comment]
This works on arquivo-webapp. 
It will work on production environment after the deploy of webapp release.
