### ISSUE TITLE
On IE11 the wayback menu and options buttons are displayed strangely 

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#878]
The menu and the options buttons are showing strangely. The menu button is displaying the hamburger and the options button the ... with both using a too large font. 
On webapp front-end it shows ok.

![image](https://user-images.githubusercontent.com/67018/78129599-c06e3180-740f-11ea-87e4-a4493fa2640e.png)

![image](https://user-images.githubusercontent.com/67018/78129881-307cb780-7410-11ea-8abf-111568fb65d9.png)

**Comment by pcabritafccn** [comment]
This is issue is solved.
