### ISSUE TITLE
Order of the image search results is wrong on the two column result layout

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#879]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/images.jsp?hitsPerPage=10&query=fccn&l=pt&ion-dt-0=1996-12-01&ion-dt-1=2020-01-02&dateStart=01%2F12%2F1996&dateEnd=02%2F01%2F2020#

**What happened?**
Results are displayed by vertically instead of horizontally

**What should have happened?**
Order should be changed to match desktop version and user expectation
See the screenshots to better understand what is happening
I've added the numbers in red to show the correct ranking

**Screenshots**

How it shows on desktop
![image](https://user-images.githubusercontent.com/2866295/78270412-b416d100-7502-11ea-9e45-bb766add2d8c.png)

How it shows on a two column layout (recent Chrome on Tablet, but also happens when resizing on desktop)
![image](https://user-images.githubusercontent.com/2866295/78270434-ba0cb200-7502-11ea-8cd5-861fd1d5b2e6.png)

**Comment by hmendes** [comment]
Related to #970

**Comment by pcabritafccn** [comment]
This will be checked,

**Comment by pcabritafccn** [comment]
Issue #879 is now solved. The order is now as row.

**Comment by pcabritafccn** [comment]
Issue #879 is now solved on Eros version. The order is now as row.
