### ISSUE TITLE
Image search stuck at loading (Android Browser version 6.0.1)

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#880]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/images.jsp?hitsPerPage=10&query=fccn&l=pt&ion-dt-0=1996-12-01&ion-dt-1=2020-01-02&dateStart=01%2F12%2F1996&dateEnd=02%2F01%2F2020#

**What happened?**
Stuck showing loading spinner

**What should have happened?**
Image search results show up
I'm trying to find a way of getting to the JS console to see what is happening and give more details

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/78271505-22a85e80-7504-11ea-8ff4-6f366fcde960.png)

**Comment by amourao** [comment]
Managed to get the following errors using "adb logcat"

```
Console: Uncaught SyntaxError: Unexpected token function https://preprod.arquivo.pt/js/images2.js?build=202004021407:170
Console: Uncaught ReferenceError: slideChanged is not defined https://preprod.arquivo.pt/images.jsp?hitsPerPage=10&query=batatas&l=pt&dateStart=01%2F12%2F1996&dateEnd=02%2F01%2F2020:654
Console: Uncaught (in promise) ReferenceError: doInitialSearch is not defined https://preprod.arquivo.pt/images.jsp?hitsPerPage=10&query=batatas&l=pt&dateStart=01%2F12%2F1996&dateEnd=02%2F01%2F2020:651
```

**Comment by igobranco** [comment]
We aren't supporting this kind of browser. 
I think the page search works because we didn't use too much of newest versions of ECMAScript, but unfortunately the image search use.
