### ISSUE TITLE
Add border to confirm to search in other archives

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#887]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20020407221349/fccn.pt/testtesttest

**What happened?**
When clicking on **Search in other archives** it opens a modal box that has an incorrect style. 

**What should have happened?**
Add s similar style with other modals on wayback / replay. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/78372122-c8b99e80-75c0-11ea-946b-74f4f6eda874.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
