### ISSUE TITLE
Search images with site shows other sites

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#892]
**What is the URL that originated the issue?**
https://arquivo.pt/images.jsp?hitsPerPage=10&query=portugal+site%3Aft.com&l=en&ion-dt-1=1996-01-01&ion-dt-0=2020-04-15&dateStart=01%2F01%2F1996&dateEnd=15%2F04%2F2020

**What happened?**
When searching images with a short site, like ft.com, it show images from other domains different of ft.com. 

**What should have happened?**
Only show images of ft.com or at least its sub-domains. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/79356053-62286f00-7f36-11ea-9c64-7c53d1aa3a42.png)

**Comment by amourao** [comment]
Site matches are being searched as `domain matches *ft.com`

This should be changed to `domain matches *.ft.com OR domain matches ft.com`

**Comment by amourao** [comment]
Fixed in https://github.com/arquivo/image-search-api/commit/317be43bfdfc4b9f49882ebf6e9ca816ebab4df3 
Deployed to preprod
