### ISSUE TITLE
Text search API error

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#895]
**What is the URL that originated the issue?**
https://arquivo.pt/textsearch?q=ronaldo&maxItems=2000

Works normal: https://arquivo.pt/textsearch?q=Coronav%C3%ADrus&maxItems=1263 
Error: https://arquivo.pt/textsearch?q=Coronav%C3%ADrus&maxItems=1264 

**What happened?**
Error when serving some queries on text search API.

**What should have happened?**
No errors. 

**Screenshots**

**Comment by igobranco** [comment]
Exception on log without stacktrace.

{code}
17-Apr-2020 15:43:35.456 SEVERE [ajp-nio-8009-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [NutchwaxTextSearch] in context with path [/nutchwax] threw exception
 java.lang.NullPointerException

{code}

**Comment by danielbicho** [comment]
Fixed. Problem with some segments files on EAWP12.
