### ISSUE TITLE
Text Search API JSON output format has wrong data types

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#896]
**What is the URL that originated the issue?**
https://arquivo.pt/textsearch?versionHistory=uc.pt

**What happened?**
All JSON fields are returned as string instaead of the correct type.

**What should have happened?**
**estimated_nr_results** should be **integer**
**contentLength** should be **integer**
**status** should be **integer**

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/79755700-70e59c00-8311-11ea-92cc-680ab8e5cf28.png)

**Comment by danielbicho** [comment]
This is fixed on #890

**Comment by danielbicho** [comment]
fixed on preprod
