### ISSUE TITLE
Inconsistent naming in Text Search API output JSON fields

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#897]
**What is the URL that originated the issue?**
https://arquivo.pt/textsearch?versionHistory=uc.pt

**What happened?**
Some fields are _camelCase_, while others are _snake_case_
e.g.
**estimated_nr_results** 
**contentLength** 

**What should have happened?**
Consistent naming

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/79755700-70e59c00-8311-11ea-92cc-680ab8e5cf28.png)

**Comment by arquivo-awp** [comment]
Won't fix. This minor improvement could break existing applications such as those developed for the Awards.
