### ISSUE TITLE
Can't get the number of pages where a certain search term existed

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#899]
**What is the URL that originated the issue?**
https://arquivo.pt/textsearch?q=ronaldo&maxItems=2000

**What happened?**
When trying to access https://arquivo.pt/textsearch?q=ronaldo&maxItems=2000 it returns that unexpected event occurred. 

**What should have happened?**
I think it is because there are not 2000 pages with the term ronaldo, but as the parameter is maxItems and no, exactItems I think it would make sense to return the pages that existed.

**Screenshots**

**Comment by danielbicho** [comment]
this was reported at #895 and is solved. try again
