### ISSUE TITLE
Behavior on mouse over and on click is not allways the same

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#901]
**What is the URL that originated the issue?**
https://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Flisboaenova.org%2F

**What happened?**
On mouse over the day-month-hour the color doesn't change

**What should have happened?**
The color should change to white on mouse over and to dark blue when selected. Also the year should return to initial blue

**Screenshots**
<img width="958" alt="print_x01" src="https://user-images.githubusercontent.com/44206545/79869107-d2bd0900-83d8-11ea-98a1-b83463c13cec.png">

**Comment by pcabritafccn** [comment]
This issue is not valid anymore as the team is working on a new wayback left menu (tale versions included) with a new html+ css structure on which will be applied the correct mouse behaviours.
