### ISSUE TITLE
Open in a new tab doesn't work in some links

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#902]
**What is the URL that originated the issue?**
https://arquivo.pt/

**What happened?**
When open in new tab the buttons/links "Página" and "Imagens" we get a error 500.

**What should have happened?**
Should open in a new tab, like the link/button "Pesquisa Avançada"

**Screenshots**
<img width="960" alt="print_x03" src="https://user-images.githubusercontent.com/44206545/79870906-9048fb80-83db-11ea-8343-a5a8a6ee9e65.png">
<img width="589" alt="print_x04" src="https://user-images.githubusercontent.com/44206545/79871052-bcfd1300-83db-11ea-8fde-48e44dce27c9.png">

**Comment by igobranco** [comment]
Already fixed on #893
