### ISSUE TITLE
Review buttons background colors

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#903]
Buttons background color strategy:
- Not selected: bg:blue/font:white
- Selected: bg:dark blue/font:white bold
- On-mouse-over: bg:white/font:blue bold

### Menu Pages button
https://preprod.arquivo.pt/?&l=en > Menu > Pages
![image](https://user-images.githubusercontent.com/67018/79861200-eb72f200-83cb-11ea-845a-a218d7539cd0.png)

Expected behavior:
- [x] Pages options colapsed: bg:blue/font:white
- [ ] Pages options expanded: bg:dark-blue/font:white bold
- [x] Pages options on mouse over: bg:white/font:blue bold

### Menu Images button
Same thing has previous menu pages button.

Expected behavior:
- [x] Images options colapsed: bg:blue/font:white
- [ ] Images options expanded: bg:dark-blue/font:white bold
- [x] Images on mouse over: bg:white/font:blue bold

### Date pickers
The start and end datepickers on homepage, search pages, search images, and both advanced search pages and images screens. 
Expected behavior:
- [ ] default background: blue/font:white
- [ ] on mouse over: bg:white/font:blue bold

![image](https://user-images.githubusercontent.com/67018/79861027-9c2cc180-83cb-11ea-8a8e-c95c648a376a.png)

### Year on the list of versions embedded on wayback
https://preprod.arquivo.pt/wayback/19961013145650/http://www.fccn.pt:80/

![image](https://user-images.githubusercontent.com/67018/79871077-c4bcb780-83db-11ea-8e7e-a18934d3e0a9.png)

Expected behavior:
- [ ] default background: blue/font:white
- [ ] selected: bg:dark blue/font:white bold 
- [ ] on mouse over: bg: white/font:blue bold

### Month on list of versions embedded on wayback
https://preprod.arquivo.pt/wayback/19961013145650/http://www.fccn.pt:80/

![image](https://user-images.githubusercontent.com/67018/79871107-cedeb600-83db-11ea-8099-da86c0b328f9.png)

Expected behavior:
- [ ] default background: blue/font:white
- [ ] selected: dark blue/font:white bold 
- [ ] on mouse over: white/font:blue bold 

### Timestamp on list of versions embedded on wayback
Also the same thing on table of versions. Because it's the same code, I'm not going to repeat. 

![image](https://user-images.githubusercontent.com/67018/79871444-41e82c80-83dc-11ea-896b-fe5c43b4df07.png)

Expected behavior:
- [x] default background: blue/font:white
- [x] selected: bg: dark blue/font:white bold
- [ ] on mouse over: white/font:blue bold

**Comment by hmendes** [comment]
Solved.
