### ISSUE TITLE
Display in some mobile devices doesn't fit

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#904]
**What is the URL that originated the issue?
https://sobre.arquivo.pt/

**What happened?**
Search box doesn't fit with the device, ex "Samsung RGX(GT-I9060)

**What should have happened?**
Should adapt the box size

**Screenshots**
![Screenshot_20200416-181247_Chrome](https://user-images.githubusercontent.com/44206545/79873795-7ad5d080-83df-11ea-81c6-6d4392919510.jpg)

**Comment by pcabritafccn** [comment]
Issue #904 is now closed.

![image](https://user-images.githubusercontent.com/51712013/130079893-2abbb2fe-3a61-4e07-a409-d7683b7e934f.png)
