### ISSUE TITLE
Color and behavior of date pickers buttons not the same as int the other pages

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#905]
**What is the URL that originated the issue?**
https://arquivo.pt/advanced.jsp?start

**What happened?**
On mouse over and on click in a given date the behavior and colors are diferent from other pages

On mouse over and on click in a given date the behavior and colors shoud be the same as in other pages.

**Screenshots**
<img width="563" alt="print_x06" src="https://user-images.githubusercontent.com/44206545/79875105-10259480-83e1-11ea-8903-91201bfb2ee0.png">

**Comment by igobranco** [comment]
I think this is a special case. Every number on background blue is kind of strange...
In my opinion the only change should be the selected date on dark blue/white font.

**Comment by dcgomes** [comment]
I did an heuristic usability analysis on the SERP UI. 
I identified several additional cognitive incoherence that originate obstacle particularly for the interaction withe datepickers.

I proposed a new UI design as attached. 

I will present and explain it to the team.

![UI-SERP-Responsive](https://user-images.githubusercontent.com/13120352/80092967-949c2280-855b-11ea-867d-4c662ee78175.jpg)

**Comment by pcabritafccn** [comment]
This issue is now solved.
