### ISSUE TITLE
Date overflows result boxes on Image SERP

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#909]
**What is the URL that originated the issue?**
https://arquivo.pt/images.jsp?hitsPerPage=10&query=universidade+de+coimbra&l=pt&dateStart=01%2F01%2F1996&dateEnd=23%2F04%2F2020

Some dates of the images are overflowing the boxes.

This works OK in a different screen even if we Zoom In or Out.

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/80130503-97653a80-8590-11ea-88d6-ce6c4ed94fb5.png)

![image](https://user-images.githubusercontent.com/13120352/80130601-c7acd900-8590-11ea-96c6-e3e3dc110133.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
