### ISSUE TITLE
Queries and accesses get slow

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#91]
Originally reported on Google Code with ID 92
```
Sometimes the search and access system degrades and gets slow.

It only recovers its normal performance if we restart the Query Broker.

Must find what causes this degradation?

Check monitpring of resources for the QB machines.
Configure alarm to warn if searches get slow.
```

Reported by `danielcoelhogomes` on 2014-11-10 18:02:33

**Comment by danielbicho** [comment]
Query response times monitoring has been added to Cacti, at host p19:
(p58) http://sirens.fccn.pt/cacti/graph.php?action=view&local_graph_id=24032&rra_id=all
(p62) http://sirens.fccn.pt/cacti/graph.php?action=view&local_graph_id=24031&rra_id=all

Slowness triggers also has been added.

The problem never happend again. 

Reopen if the problem starts again.
