### ISSUE TITLE
CDX indexes some collections are wrongly reporting content length 0

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#912]
**What is the URL that originated the issue?**
CDX indexes some collections are wrongly reporting content length 0

https://arquivo.pt/wayback/cdx?url=sapo.pt

**What happened?**
There are records with content length 0. It seems a specific collection problem?

**What should have happened?**
Display correctly the content length

![image](https://user-images.githubusercontent.com/13105310/80358807-e0f5a400-8874-11ea-9017-406773de775e.png)

Can you check the issue @PedroG1515 ?

**Comment by PedroG1515** [comment]
When we do a new indexing the problem is solved.

**Comment by PedroG1515** [comment]
Problem related with this issue:
https://github.com/webrecorder/cdxj-indexer/issues/8

**Comment by PedroG1515** [comment]
We can not re-index
