### ISSUE TITLE
Change links "Visit" and "Details" to buttons on image details

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#913]
**What is the URL that originated the issue?**
https://arquivo.pt/images.jsp?hitsPerPage=10&query=ronaldo&ion-dt-1=1996-01-01&ion-dt-0=2020-04-27&dateStart=01%2F01%2F1996&dateEnd=27%2F04%2F2020#card

**What should have happened?**
Change links "Visit" and "Details" to buttons on image details.

Not selected: bg:blue/font:white
Selected: bg:dark blue/font:white bold
On-mouse-over: bg:white/font:blue bold

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/80363416-18b41a00-887c-11ea-983f-b39bde53e2f5.png)

**Comment by pcabritafccn** [comment]
This issue is now solved.
