### ISSUE TITLE
Improve FAWP crawling

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#914]
On FAWP crawling:

1. replace the crontab with a stop/start from an ansible playbook.
The ansible playbook should be started using a cron jenkins job.
The ansible playbook should firstly stop the previous run and, start and launch a new crawling.

2. Seeds from google sheet
In the middle it should download the seeds from the FAWP google sheet that contains the seeds.

**Comment by PedroG1515** [comment]
The seeds are only checked the first month of each year.
