### ISSUE TITLE
Add soft-404 message linking to web-archived page

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#917]
Any broken link on sobre.arquivo.pt should present a soft-404 message with a link to that web-archived page on Arquivo.pt.

This was working like this before milestone Upgrade to Wordpress v.5 https://github.com/arquivo/pwa-technologies/milestone/10

If we try browse an nonexistent page such as https://sobre.arquivo.pt/en/ferfref we get an error page:

![image](https://user-images.githubusercontent.com/13120352/81422740-4dad5000-914b-11ea-8233-0cc72ec68f2d.png)

A related problem: the search box does not appear on Firefox:
![image](https://user-images.githubusercontent.com/13120352/81423158-fb206380-914b-11ea-83dc-54ba29321bdb.png)

A possible solution could:

"Page not found.

Browse a previous version of this page -> put link to Wayback URL on Arquivo.pt
Maybe try searching? -> put link on "searching" to the search page (https://sobre.arquivo.pt/en/search/) because the search box does not appear on Firefox"

OR 

Does the link to the web-archived page only appears when we have it archived?

**Comment by igobranco** [comment]
> Does the link to the web-archived page only appears when we have it archived?

This could be done like this example: https://github.com/arquivo/example-cdx-api

**Comment by dcgomes** [comment]
Message is always displyed in English.

Also I suggest a simpler message:

- EN: 
"Page not found.

Browse a <a href=$WAYBACK_URL> previous version of this page in $DATE</a>

Maybe try searching? 
<searchbox>

- PT 
"Página não encontrada.

Visite uma <a href=$WAYBACK_URL> versão anterior desta página em $DATE</a>

Ou experimente pesquisar: 
<searchbox>

**Comment by dcgomes** [comment]
This page is useful for testing: 
http://sobre.arquivo.pt/about-the-archive/publications-1/documents/peopleware-rarc-article-in-jpg/image_preview

Replace "." by ":" in "Ou experimente pesquisar."

**Comment by igobranco** [comment]
The problem is that on mobile the search is on top.

![image](https://user-images.githubusercontent.com/67018/83146640-8909c180-a0ee-11ea-8285-8c21a53d9f6a.png)
