### ISSUE TITLE
No version is selected in the version list

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#921]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20170227184149/https://sobre.arquivo.pt/about-the-archive/publications-1/documents/peopleware-rarc-article-in-jpg/image_preview

**What happened?**
1.  http://sobre.arquivo.pt/about-the-archive/publications-1/documents/peopleware-rarc-article-in-jpg/image_preview
2.  Then click on "Nevertheless you can still view a snapshot of this page from 2017-02-27 on Arquivo.pt"
3.  No version is selected in the version list.

**Screenshots**

![sss](https://user-images.githubusercontent.com/25795364/82190553-137d4480-98e9-11ea-8a86-f223467c4cab.JPG)

**Comment by igobranco** [comment]
Fixed.
