### ISSUE TITLE
Unable to submit a page through a suggestion link

### ISSUE THREAD

**Issue by Painatalman** [arquivo/pwa-technologies#922]
I'm **unable to suggest a page right after searching for it** in the archive, by clicking on the link that appeared to do so.

![incapaz-de-gravar-diretamente](https://user-images.githubusercontent.com/1950530/82138685-4278b500-981a-11ea-8712-153f6d860785.gif)

### When and where

In the main website's search result page, when there are no results available.

### Steps to reproduce

1 - Go to Arquivo.pt
2 - Search for a specific page by: 
  1 - adding an unarchived url in the form input
  2 - submitting the form (by pressing "enter" or clicking the button)
3 - Select the option labelled "Sugerir" that appears in the results section
4 - a banner with a sad face appears, as if something broke. Page doesn't progress from there

### What should happen

I don't know what the expected behaviour is in terms of UI, but **I should've been redirected to a form** to submit the searched URL (preferably without having to write the suggested page's URL).

### Observations

It seems that the **link** labelled "Sugira" (that appears after an unsuccessful search) **works properly**. When I copy it and paste it directly in the browser's URL bar, I am redirected to the page used to submit page suggestions:

![url-seems-to-work](https://user-images.githubusercontent.com/1950530/82138658-0f362600-981a-11ea-907b-0ac7653ecde9.gif)

> **Side note**: I'm assuming that the **field for page URLs should be filled up** already, but that's another issue to consider.

However, there's an **cross-origin issue** in the  *iframe* with the suggestion link:

 ![error-iframe](https://user-images.githubusercontent.com/1950530/82138411-25db7d80-9818-11ea-87c1-c62d041d126c.gif)

**Comment by igobranco** [comment]
@Painatalman thanks to the report of the problem. I've fixed it on dev. On next deploy to production it will be fixed on arquivo.pt.
