### ISSUE TITLE
Left Menu appears expanded and does not close in Chrome

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#923]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20141025164946/http://www.parlamento.pt/ActividadeParlamentar/Paginas/DetalheIniciativa.aspx?BID=34920

https://arquivo.pt/wayback/20190522131407/http://obscurena.org/monica-lopes/

https://arquivo.pt/wayback/20090930025342/http://www.aportugal.com/braganca/index.htm

**What happened?**
Even if we try to click in the cross to close the menu it does not close the Menu.

The problem was witnessed in Chrome but does don't affect for instance Firefox.

The problem seems to occur when users follow links from external sites to archived pages. These problem occurred very frequently when following links contained in works submitted to the Award.

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/82233332-c4a2cf80-9927-11ea-9931-6fd721431c53.png)

![image](https://user-images.githubusercontent.com/13120352/82233292-b5bc1d00-9927-11ea-9dbe-5edbbabc49af.png)

![image](https://user-images.githubusercontent.com/13120352/82234106-d6d13d80-9928-11ea-9648-1db6e32dec20.png)

**Comment by pcabritafccn** [comment]
This was tested again in different browsers including Chrome and no issue was detected.
