### ISSUE TITLE
Log the search results of each page/text search API call

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#928]
Related to #782.
On /textsearch API it is need a better log that writes:
1. the requested URL;
2. its n results.

Something like:
Page search with requested URL: <requested URL> and results: [<timestamp_1>/<url_1> <timestamp_2>/<url_2> <timestamp_3>/<url_3>]

**Comment by danielbicho** [comment]
Example of how it is currently:

`2020-06-18T08:38:47,528 INFO  PageSearchController - https://preprod.arquivo.pt/pagesearch/textsearch?q=carnaval&siteSearch=www.ojogo.pt&prettyPrint=true&maxItems=10 search_parameters:{"offset":0,"dedupValue":2,"dedupField":"url","q":"carnaval","maxItems":10,"siteSearch":["www.ojogo.pt"]} search_results: ["20190522141229/https://www.ojogo.pt/extra/lusa/interior/carnaval-diferente-com-festival-entrudancas-na-vila-alentejana-de-entradas-10620170.html","20190522141233/https://www.ojogo.pt/extra/lusa/interior/amp/carnaval-diferente-com-festival-entrudancas-na-vila-alentejana-de-entradas-10620170.html"]`

Please re-open the issue to add any suggestions or point out missing stuff
