### ISSUE TITLE
Add link to Arquivo.pt Awards on footer of www.arquivo.pt and sobre.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#937]
**What is the URL that originated the issue?**
www.arquivo.pt
sobre.arquivo.pt

**What should have happened?**
- Add link "Arquivo.pt Awards" to https://arquivo.pt/awards below "Colaborate" section on the footer. Change header "Colaborate" to "Collaborate"
- Add link "Prémios Arquivo.pt" to https://arquivo.pt/premios below "Colabore" section on the footer

**Comment by PedroG1515** [comment]
Fixed

**Comment by igobranco** [comment]
We still need to change on arquivo.pt webapp.

**Comment by igobranco** [comment]
Done.
