### ISSUE TITLE
Create graphical coeherence between www.arquivo.pt and sobre.arquivo.pt

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#938]
**What is the URL that originated the issue?**
Users should navigate between www.arquivo.pt and sobre.arquivo.pt pages without noticing that they are using different platforms. Thus, there must be a coherent graphical that was broken during the WebApp milestone.

**What should have happened?**
- Top bar and footer should have the same color to emphasize the begin and end of the UI. I suggest blue or black, both on www.arquivo.pt and sobre.arquivo.pt.

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/85848772-a25f6580-b7a1-11ea-872a-b0d2771cb40d.png)
![image](https://user-images.githubusercontent.com/13120352/85848793-b014eb00-b7a1-11ea-9e27-a4b636fb8b98.png)

**Comment by hmendes** [comment]
Solved.
