### ISSUE TITLE
Change tstamp field on the API to reflect that it is the crawling date

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#939]
There is some confusion with the **tstamp** field presented on API. It should be renamed to properly convey that is the date when the page was crawled instead of the publication date. 

https://arquivo.pt/textsearch?q=Lisboa&collection=AWP4

Or improve documentation?

**Comment by amourao** [comment]
This is a simple issue, but maybe we should delay it to the Caronte milestone to avoid changing the API too many times

**Comment by danielbicho** [comment]
also the API should be versioned next time it changes

**Comment by VascoRatoFCCN** [comment]
Edited the API field description as follows:
UTC timestamp of when the page was crawled - **NOT the timestamp of when it was published**
