### ISSUE TITLE
Review mouse style of open/close arrows

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#941]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/search?hitsPerPage=10&query=fccn.pt&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-06-29&dateStart=01%2F01%2F1996&dateEnd=29%2F06%2F2020

**What happened?**
The open / close vertical arrows should have the mouse style has an anchor, so the user thinks it should be clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/86000291-47c64380-ba05-11ea-9afd-dcecf0a674ed.png)

**Comment by hmendes** [comment]
This issue is now fixed.
