### ISSUE TITLE
Add an autocomplete to search bar

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#943]
Add an autocomplete to the search bar.
![image](https://user-images.githubusercontent.com/67018/86001417-c1aafc80-ba06-11ea-9079-cc7f2eea24d6.png)

So instead of creating a new spellchecker / query suggestion. One option is to use the google. 
We could use the autocomplete feature of the google like what is documented here: https://shreyaschand.com/blog/2013/01/03/google-autocomplete-api/

**Comment by dcgomes** [comment]
Won't apply autocomplete because browsers/devices already have built-in autocomplete functions for typing.
