### ISSUE TITLE
Use default scroller on Chrome

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#945]
**What is the URL that originated the issue?**
www.arquivo.pt on Desktop/Laptop screen.

On Chrome the scroll bar turns blue and it is too thin to be viewable or clickable.
On Firefox it appears OK.

The best is to use the default scroll bar to avoid interoperability issues.

**Screenshots**
Chrome: 
![image](https://user-images.githubusercontent.com/13120352/86015296-4a329880-ba19-11ea-9c48-fce03b8386e1.png)
Firefox
![image](https://user-images.githubusercontent.com/13120352/86015316-51f23d00-ba19-11ea-92c9-dc34b6a81e96.png)

**Comment by igobranco** [comment]
).Removed the custom style on scroll bar on webapp (homepage, page and image search). But maintain the style on the wayback list of versions. 

Removed the style:
![image](https://user-images.githubusercontent.com/67018/86517537-a6365c00-be21-11ea-82c2-aadcb979f28e.png)

Maintain the style:
![image](https://user-images.githubusercontent.com/67018/86517540-af272d80-be21-11ea-945e-62af6711a6ec.png)
