### ISSUE TITLE
Strong tag is not properly opened on input box label

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#947]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/image/advanced/search?hitsPerPage=10&query=fccn&ion-dt-0=1996-01-01&ion-dt-1=2020-06-29&dateStart=01%2F01%2F1996&dateEnd=29%2F06%2F2020&l=en

**What happened?**
Strong tag is not properly opened in the English version of the page:
`strong>Related to this expression or sentence:`

**What should have happened?**
Strong tag should properly opened

**Screenshots**

**Comment by igobranco** [comment]
Fixed.
