### ISSUE TITLE
Visually distinguish selected version from other opened versions on drill down

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#949]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20090625085758/http://www.interney.net/testes/teste001.php

**What happened?**
After the user opened a few versions of a page through the drill down menu on replay, it becomes visually impossible to identify which one of the versions corresponds to the page that it is currently opened.

**What should have happened?**
Opened and selected versions should present different color schemes on the Replay bar.

**Screenshots**
In this example, it becomes very difficult to identify which one of the versions is the one being replayed?
![image](https://user-images.githubusercontent.com/13120352/86023077-1c525180-ba23-11ea-9392-443ce50d5006.png)

**Comment by dcgomes** [comment]
The selected date only turns bold after second click on it.

![image](https://user-images.githubusercontent.com/13120352/86025164-cf23af00-ba25-11ea-906a-c6669fcfe9e4.png)

**Comment by igobranco** [comment]
> The selected date only turns bold after second click on it.
> 
> ![image](https://user-images.githubusercontent.com/13120352/86025164-cf23af00-ba25-11ea-906a-c6669fcfe9e4.png)

I think the problem isn't the second click like you have described, but the change of the selected version is too slow. When you change a version timestamp for a page, depending of the page, sometimes takes a couple of seconds to change the current timestamp on list of versions.

**Comment by igobranco** [comment]
I've added a small change that improves the UI. The clicked version is firstly marked has selected and then the archived version if changed. It feels better to the user because he views the change of the selected version immediately.

**Comment by dcgomes** [comment]
Suggest to use only two colors:
- blue: default
- dark blue: for selected items

For instance, in this example, only the Year, Month and Day of the version being replayed would be in dark blue background and bold font. That would be "2017", 
"Dezembro" and "7 Dezembro às 20:03" in dark blue background and bold font. 

Every other version would be in blue background and normal font.

![image](https://user-images.githubusercontent.com/13120352/86144821-107f9180-baee-11ea-87e0-978e3c29d801.png)

Make mockups before changing code.

**Comment by dcgomes** [comment]
The List view in Mobile gets even more confusing. It uses 3 different backgrounds for selected versions: white, blue and dark blue.

![Screenshot_20200630-152619](https://user-images.githubusercontent.com/13120352/86146189-cdbeb900-baef-11ea-8052-49bbe06cc543.png)


White background should not be used in mobile viewport.
The expanded options should be in dark blue with bold font. All the others should not change color.

In the example above, dark blue with bold font should have been applied to all the expanded options:
- 2014, Setembro
- 2016, Fevereiro, Junho, Novembro
- 2017, Fevereiro, Agosto, Dezembro


When the options are colapsed they should return to blue with normal font.

**Comment by dcgomes** [comment]
![image](https://user-images.githubusercontent.com/13120352/96602104-92d4d100-12ea-11eb-893d-7d66666d825c.png)

On the left drill-down, all remains at the same color except the chosen date (same as 2015).
In the example above only "4 Agosto às 23:14" would be in dark blue.

**Comment by hmendes** [comment]
Solved.

**Comment by dcgomes** [comment]
Only the selected version should be in dark blue.

https://preprod.arquivo.pt/wayback/20180419170248/https://www.globo.com/

![image](https://user-images.githubusercontent.com/13120352/96877498-a2325680-1471-11eb-9ac5-a8cfb11a1d96.png)

For example, on the screenshpt above only "19 Abril às 17:02" should be in dark blue

**Comment by hmendes** [comment]
Solved.
