### ISSUE TITLE
Mouse over the Table button doesn't show as clickable

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#950]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/search?hitsPerPage=10&query=fccn.pt&ion-dt-0=1996-01-01&ion-dt-1=2020-06-29&dateStart=01%2F01%2F1996&dateEnd=29%2F06%2F2020&l=en

**What happened?**
The Table button when searching by URL isn't being shown as clickable. 

**What should have happened?**
The mouse cursor should change to "hand mode" instead of the cursor, so it is consistent with other buttons on the web application. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/86023593-c9c56500-ba23-11ea-9286-28fdc8337670.png)

![image](https://user-images.githubusercontent.com/67018/86023668-dcd83500-ba23-11ea-9fc3-03147ab88aa5.png)

**Comment by hmendes** [comment]
Fixed.
