### ISSUE TITLE
Date input on advanced search pages is not aligned to the bottom of the screen on mobile

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#951]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/advanced/search?l=pt&adv_and=FCCN&adv_phr=&adv_not=&ion-dt-0=2001-01-01&ion-dt-1=2020-06-29&dateStart=01%2F01%2F2001&dateEnd=29%2F06%2F2020&type=all&size=all&safeSearch=on&site=
https://preprod.arquivo.pt/image/advanced/search?l=pt&adv_and=FCCN&adv_phr=&adv_not=&ion-dt-0=2001-01-01&ion-dt-1=2020-06-29&dateStart=01%2F01%2F2001&dateEnd=29%2F06%2F2020&format=all&site=&hitsPerPage=10

**What happened?**
On my Android smartphone, the Date picker does not stick to the bottom of the page when I scroll down.
This happens both on advanced page and advanced image search.
This happens for both Firefox and Chrome.

**What should have happened?**
Date input should stick to the bottom of the page

**Screenshots**
Click on date before scroll (works ok)
![image](https://user-images.githubusercontent.com/2866295/86023983-51ab6f00-ba24-11ea-9059-a146cf81830a.png)

Click on date after scrolling down a bit (not stuck to the bottom)
![image](https://user-images.githubusercontent.com/2866295/86023364-7fdc7f00-ba23-11ea-8d95-b999d77fffac.png)

**Comment by amourao** [comment]
The problem also happens on the main search pages 

https://preprod.arquivo.pt/image/search?hitsPerPage=10&query=Batatas+fritas&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-06-29&dateStart=01%2F01%2F1996&dateEnd=29%2F06%2F2020#

**Comment by hmendes** [comment]
Solved.
