### ISSUE TITLE
Review and redesign Table view

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#952]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/search?typeShow=table&query=interney.net/testes/teste001.php

**What happened?**
- The design should be coherent with the remaining UIs. For instance, the squares of the dates could have round corners. On mouse hover they should turn to white background.

- The bold on the years may be could be remove to make the layout more elegant and light.

- The buttons  "Tabela" and "Lista" may should be out of the Table header (dark blue background) to respect the same behavior of the remaining buttons. It becomes confusing to identify in which view the user is. Here the user is on the Tabela view but the design highlights "Lista":
![image](https://user-images.githubusercontent.com/13120352/86024254-abac3480-ba24-11ea-9341-e632b31a8171.png)
Here the user is on the "Lista" view but the design highlights "Tabela":
![image](https://user-images.githubusercontent.com/13120352/86024310-bcf54100-ba24-11ea-9fd9-100cc4d2e275.png)

The problem is that as the selected button loses its button affordance due to the blue background, the user does not recognize that is the currently selected option.

- The lines on the Table view may could be removed for the sake of simplicity. Review the design of the Table view.

**Screenshots**
![image](https://user-images.githubusercontent.com/13120352/86023685-e1045280-ba23-11ea-82ad-bb969177ed7b.png)

**Comment by hmendes** [comment]
Solved.

**Comment by dcgomes** [comment]
The described problems prevail at preprod.arquivo.pt. Solve or reassign to Caronte milestone.

**Comment by hmendes** [comment]
Solved.
