### ISSUE TITLE
Menu Freezes on UI

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#954]
**What is the URL that originated the issue?**
This bug is hard to reproduce but it occurs frequently by navigating through the UIs, the left Menu after being opened freezes and the user cannot close it even after clocking on the cross.

![image](https://user-images.githubusercontent.com/13120352/86025612-52dd9b80-ba26-11ea-93a9-0736ae231ffd.png)

**Comment by dcgomes** [comment]
Using resolution 2560 x 1440 px, Windows 10, 125% resize fonts (Windows recommended default), Chrome

**Comment by dcgomes** [comment]
Does not happen on preprod.arquivo.pt. Might be fixed.

**Comment by dcgomes** [comment]
Still happens after I cleared all browsing cache and cookies.

![image](https://user-images.githubusercontent.com/13120352/96859289-393ee480-1459-11eb-97b6-bc5bae118127.png)

It is annoying because the close cross of the menu does not work and the menu steals a part of the screen.

### Settings:

- Chrome Version 86.0.4240.75 (Official Build) (64-bit) on Windows 10
- Zoom: 100%
- Display settings of external screen:
![image](https://user-images.githubusercontent.com/13120352/96859535-8753e800-1459-11eb-83cc-248ad1265530.png)
- Display settings of laptop screen:
![image](https://user-images.githubusercontent.com/13120352/96859752-c7b36600-1459-11eb-8d64-ddf45794a95d.png)

**Comment by dcgomes** [comment]
On Firefox, sometimes the Menu automatically appears really quickly and then it closes also automatically.

**Comment by pcabritafccn** [comment]
This issue does not apply to the new HTML code. Going to close it.
