### ISSUE TITLE
Maintain consistent button on mouse hover behavior on "Pesquisar noutros arquivos"

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#956]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20060219152250mp_/http://centrodeemergencia.blogs.com/portugal/2004/07/linhas_de_apoio.html

On mouse hover on button "Pesquisar noutros arquivos" should turn it to white backgroud.

![image](https://user-images.githubusercontent.com/13120352/86026614-908ef400-ba27-11ea-9ca8-69dbd8f66804.png)

**Comment by hmendes** [comment]
This issue is now fixed.
