### ISSUE TITLE
Change alternatives when no result is found

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#957]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/image/search?hitsPerPage=10&query=batrtata&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2001-12-12&dateStart=01%2F01%2F1996&dateEnd=12%2F12%2F2001
![image](https://user-images.githubusercontent.com/13120352/86027139-3cd0da80-ba28-11ea-8dfa-aecb744d170f.png)

Present the query alternative as defined in:
https://xd.adobe.com/view/e0d94404-5737-435a-8f05-639888512a26-b58a/screen/34c38da8-b01b-47d2-9518-118e37edb113/Search-page-results-for-not-found-term-1

![image](https://user-images.githubusercontent.com/13120352/86027241-60942080-ba28-11ea-9979-1e42208cd62f.png)

Sugerimos que:
- Aumente o intervalo de tempo
- Pesquise outras palavras
- Experimente a Pesquisa Avançada"

**Comment by igobranco** [comment]
It's also needed a change to the order of the HTML tags.

**Comment by igobranco** [comment]
I didn't respect the order, because the spellchecker is very rapid. And it would move the green spellchecker further down when the search have finished.

![image](https://user-images.githubusercontent.com/67018/87699077-3d89a080-c78c-11ea-87b8-3e4ecaaa6489.png)
