### ISSUE TITLE
Cannot copy text from UIs

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#959]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/search?hitsPerPage=10&query=batata&l=pt&ion-dt-1=1998-01-01&ion-dt-0=2001-12-12&dateStart=01%2F01%2F1998&dateEnd=12%2F12%2F2001&spellchecked=true

![image](https://user-images.githubusercontent.com/13120352/86028598-faa89880-ba29-11ea-95e0-ace191728cdc.png)

**What happened?**
Users cannot copy text (Control+ C) from the UIs. For instance, cannot copy titles of pages or URLs. Researchers like to copy texts for their own notes.

Why is this happening?

**Comment by hmendes** [comment]
Related to #968

**Comment by pcabritafccn** [comment]
This issue does not apply to the new HTML code. Going to close it.

**Comment by VascoRatoFCCN** [comment]
Do we want to support this? There are plenty of workarounds for this problem, some are provided by us: the user can use the export option or use the APIs to access this text.

**Comment by dcgomes** [comment]
Yes, because we cannot control what users do and copy/paste of text from web pages is a function that all web users consider as common and expect to be supported.

API and Technical details are advanced functions that most of our users do not use.

Please fix on milestone Helios.
