### ISSUE TITLE
Change label "Exportar para XLSX"

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#960]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/search?hitsPerPage=10&query=batata&l=pt&ion-dt-1=1998-01-01&ion-dt-0=2001-12-12&dateStart=01%2F01%2F1998&dateEnd=12%2F12%2F2001&spellchecked=true

![image](https://user-images.githubusercontent.com/13120352/86028750-304d8180-ba2a-11ea-8fc1-a5f0b23098c3.png)

The labels should be:

- Exportar resultados (XLSX)
- Exportar resultados (CSV)
- Exportar resultados (TXT)

The current label "Exportar para XLSX" does not communicate WHAT will be exported.

**Comment by igobranco** [comment]
Changed.
