### ISSUE TITLE
"Páginas" button with charset problem

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#961]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/

![image](https://user-images.githubusercontent.com/13120352/86029454-182a3200-ba2b-11ea-8ff2-8132c5da9f39.png)

"Páginas" button displays a charset problem

**Comment by amourao** [comment]
That issue also happens to me intermittently then browsing Search and Wayback pages (Firefox 77 Ubuntu 18.04).
For example, in the names of the months.
I could never find a way of properly reproducing it.

**Comment by igobranco** [comment]
It's need to convert the ConstantsPT.js file 
á --> &aacute;
