### ISSUE TITLE
Use always fonts in black for fields of Details 

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#962]
**What is the URL that originated the issue?**

"Detalhes" of Page UI using fonts in black:
https://preprod.arquivo.pt/wayback/20180712130748/http://lixo-lixo.blogspot.com/#
![image](https://user-images.githubusercontent.com/13120352/86029650-56bfec80-ba2b-11ea-991c-d3e535f528ea.png)

"Detalhes" of Image UI using fonts in grey:
https://preprod.arquivo.pt/image/search?hitsPerPage=10&query=lixo&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-06-29&dateStart=01%2F01%2F1996&dateEnd=29%2F06%2F2020#card

![image](https://user-images.githubusercontent.com/13120352/86029756-7b1bc900-ba2b-11ea-8cb8-bf936f6e5852.png)

Both should use black.

**Comment by dcgomes** [comment]
Make graphical layout of Technical Details coherent between Pages and Images:
![image](https://user-images.githubusercontent.com/13120352/93906024-94af7280-fcf3-11ea-8b5a-58f700a709e7.png)

![image](https://user-images.githubusercontent.com/13120352/93906039-9aa55380-fcf3-11ea-88f0-6753cd29a175.png)

**Comment by hmendes** [comment]
Fixed issue.
