### ISSUE TITLE
Background of Image card misaligns on browser windows with low height 

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#963]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/image/search?l=pt&query=fccn&dateStart=01%2F01%2F1996&dateEnd=29%2F06%2F2020#card
Click on any image and resize browser to reduce height.

**What happened?**
Window card gets misaligned and a light blue background shows up

**What should have happened?**
Window card should stay properly aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/2866295/86030047-df3e8d00-ba2b-11ea-8339-e7df3124f4d5.png)

**Comment by hmendes** [comment]
Solved.
