### ISSUE TITLE
Color on mouse over "Pesquisar"

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#964]
**What is the URL that originated the issue?**
https://arquivo.pt

**What happened?**
On mouse over button "Pesquisar" mantains blue color

**What should have happened?**
Should be white on mouse over
<img width="960" alt="2020_06_30_11_08_54_" src="https://user-images.githubusercontent.com/44206545/86114243-30995b80-bac2-11ea-9eec-558ebefaf082.png">

**Screenshots**
<img width="960" alt="2020_06_30_11_08_54_" src="https://user-images.githubusercontent.com/44206545/86114305-41e26800-bac2-11ea-9b7e-08f7a0500935.png">

**Comment by igobranco** [comment]
Fixed.
