### ISSUE TITLE
Charset in the table of date

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#966]
**What is the URL that originated the issue?**
https://arquivo.pt

**What happened?**
Wrong charset "Atã@" and also the diferent font of the "years"

**What should have happened?**
Right charset and also same font in the list of "years"

<img width="960" alt="2020_06_30_10_59_08_" src="https://user-images.githubusercontent.com/44206545/86115041-48bdaa80-bac3-11ea-9c63-151bc8f47842.png">

**Comment by PedroG1515** [comment]
These are intermittent bugs:

Other example:

![safasdfc](https://user-images.githubusercontent.com/25795364/86118260-62adbc00-bac8-11ea-809e-45a36b797dd6.JPG)

**Comment by PedroG1515** [comment]
![dsad](https://user-images.githubusercontent.com/25795364/86118418-a99bb180-bac8-11ea-8fac-86ceb83eee4f.JPG)

**Comment by PedroG1515** [comment]
![dewfdwe](https://user-images.githubusercontent.com/25795364/86118838-55dd9800-bac9-11ea-9ebe-ab77e33a56a1.JPG)
