### ISSUE TITLE
Refactor CSS/HTML code to facilitate maintenance 

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#968]
**What is the URL that originated the issue?**
www.arquivo.pt

The HTML/Code should be reviewed to facilitate maintenance and reduce operational costs.

The amount of CSS classes should be minimized.

For instance, ideally there should be one single CSS class to all buttons so that their behavior could be changed on a single file. This would also facilitate maintaining coherence along the UIs and avoid usability problems.

**Comment by pcabritafccn** [comment]
Part of this is working in progress and the majority of it it´s done: html. In a second phase the css will be restructured with variables to keep it easy to change any html elements easily and also for maintenance purposes, and to obtain a quicker and smoother framework.

**Comment by dcgomes** [comment]
Issue should be closed after testing and scheduled to deploy in production.

**Comment by dcgomes** [comment]
Code was totally refactored for Eros
