### ISSUE TITLE
Search tip appears behind search button in mobile viewport

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#969]
**What is the URL that originated the issue?**
www.arquivo.pt

![image](https://user-images.githubusercontent.com/13120352/86147548-71f52f80-baf1-11ea-9a70-84f969d5d66b.png)

"Pesquisar ou escrever URL" appears behind the "Pesquisar" button.

Two suggestions to fix this issue:
- Change message to "Pesquisa ou URL"
OR
- Change button to magnifier icon on mobile viewport.

**Comment by hmendes** [comment]
Subsituir a label por "Palavra ou URL"

**Comment by hmendes** [comment]
This issue is now solved.
