### ISSUE TITLE
Upload code of sobre.arquivo.pt to Google Code (Plone)

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#98]
Originally reported on Google Code with ID 99
```
Must upload code of sobre.arquivo.pt to Google Code (Plone) and generate adequate documentation
to quickly install a replica of the documentation that complements the Archive.pt service.
```

Reported by `danielcoelhogomes` on 2014-12-02 16:34:23

**Comment by dcgomes** [comment]
Close? Or we need to re-upload after the Fénix release?

**Comment by FCCNhviana** [comment]
It was already done. Documentation is available at :https://github.com/arquivo/pwa-technologies/wiki/Install#install-plone.
