### ISSUE TITLE
linkToService, next_page and previous_page on page search API with incorrect values

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#983]
**What is the URL that originated the issue?**
https://arquivo.pt/textsearch?q=ronaldo&offset=50
https://arquivo.pt/textsearch?q=ronaldo

**What happened?**
The linkToService, next_page and previous_page attributes of the text search API response, returns the servers name instead of the service endpoint. 

```
"linkToService": "http://p89.arquivo.pt",
"next_page": "http://p89.arquivo.pt/textsearch?q=ronaldo&offset=100",
"previous_page": "http://p89.arquivo.pt/textsearch?q=ronaldo&offset=0",
```

Replace http://p89.arquivo.pt to https://arquivo.pt

**Comment by danielbicho** [comment]
Misconfiguration in the ansible application.properties file. Already fixed in production
