### ISSUE TITLE
Replace legacy arcproxy process by file-based "pyWB archives_paths"

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#985]
Replace the pywb configuration of the arcproxy with a new index.
It is possible to replace the reference in the pywb to 2 URLs of the arcproxy's with 2 files (each one for each branch). 
So pywb stops getting ARC/WARC files from arcproxy and starts getting them directly from the document servers.

Configuration changes to config.yaml of the pywb processes.
From:
```yaml
          - http://p89.arquivo.pt:8080/arcproxy/arcproxy/
          - http://p85.arquivo.pt:8080/arcproxy/arcproxy/
```
To:
```yaml
          - /data/warcIndex/branchA.tsv
          - /data/warcIndex/branchB.tsv
```

**Comment by danielbicho** [comment]
There are lots of advantage of having a proxy to get the WARCs.
What does each of those tsv files have?

**Comment by igobranco** [comment]
The tsv akka tabbed csv should contains.

Sorted lines, where each line should be: 
```
<(w)arc filename>\t<url of the (w)arc>
```

**Comment by danielbicho** [comment]
My problem with this solution is that we lose access flexibility and also lose the decoupling from the underlying storage layer.
Also the search will be inferior, O(log n) instead of O(1). These are my initial thoughts about this.

**Comment by igobranco** [comment]
@danielbicho Sorry but I don't see any advantage to use an additional component. 
The performance should be similar.
Fewer components means the architecture is more simpler.

**Comment by igobranco** [comment]
How can you justify a O(1) ? The arcproxy also needs to search internally on its Berkeley DB.

**Comment by danielbicho** [comment]
The BDB uses a hashmap

**Comment by vitgou** [comment]
Example of the current tsv file

0000.weblog.com.pt.warc.gz      http://p64.arquivo.pt:8080/browser/files/Weblog/warcs/0000.weblog.com.pt.warc.gz
007.weblog.com.pt.warc.gz       http://p64.arquivo.pt:8080/browser/files/Weblog/warcs/007.weblog.com.pt.warc.gz
01-08-2012-05h08m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/01-08-2012-05h08m.warc.gz
01-09-2012-01h54m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/01-09-2012-01h54m.warc.gz
01-10-2012-03h25m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/01-10-2012-03h25m.warc.gz
01-11-2012-06h08m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/01-11-2012-06h08m.warc.gz
02-07-2012-03H14m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/02-07-2012-03H14m.warc.gz
02-09-2012-02h52m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/02-09-2012-02h52m.warc.gz
02-10-2012-02h54m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/02-10-2012-02h54m.warc.gz
02-12-2012-02h04m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/02-12-2012-02h04m.warc.gz
03-07-2012-02h50m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/03-07-2012-02h50m.warc.gz
03-08-2012.warc.gz      http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/03-08-2012.warc.gz
03-09-2012-07h04m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/03-09-2012-07h04m.warc.gz
03-10-2012-04h53m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/03-10-2012-04h53m.warc.gz
03-12-2012-04h13m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/03-12-2012-04h13m.warc.gz
04-07-2012-06h12m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/04-07-2012-06h12m.warc.gz
04-07-2012-23h21m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/04-07-2012-23h21m.warc.gz
04-09-2012-04h00m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/04-09-2012-04h00m.warc.gz
04-10-2012-01h48m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/04-10-2012-01h48m.warc.gz
04-12-2012-03h00m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/04-12-2012-03h00m.warc.gz
05-07-2012-02h03m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/05-07-2012-02h03m.warc.gz
05-07-2012-03h35m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/05-07-2012-03h35m.warc.gz
05-10-2012-04h26m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/05-10-2012-04h26m.warc.gz
05-12-2012-02h05m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/05-12-2012-02h05m.warc.gz
06-07-2012-05h05m.warc.gz       http://p64.arquivo.pt:8080/browser/files/DinisAlves2018/warcs/06-07-2012-05h05m.warc.gz

**Comment by vitgou** [comment]
Currently in preprod. Ready for production.

**Comment by dcgomes** [comment]
We cannot yet assure the quality of the generation of the TSV files.
Delay deploy of this feature.

**Comment by vitgou** [comment]
After careful assessment it was decided not to implement this feature.
