### ISSUE TITLE
Site search: add subdomain expansion to by default to image and page search

### ISSUE THREAD

**Issue by danielbicho** [arquivo/pwa-technologies#987]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/image/search?query=sapo+site%3Aua.pt&dateStart=01/01/1996&dateEnd=22/07/2020&pag=next&start=25&l=pt

**What happened?**
Is displaying images from other subdomains *.ua.pt

**What should have happened?**
The query should diplay only images from ua.pt and not subdomains

**Comment by amourao** [comment]
This behaviour (*.ua.pt || ua.pt), is consistent with Google's:

https://www.google.pt/search?source=hp&ei=3_g6XYwv7oOMuw-yqrLwCw&q=tempo%20site%3Asapo.pt

But we should validate it against user expectations.

**Comment by amourao** [comment]
After discussion, automatic wildcard expansion will be removed from the API and added by default to image search queries using  JS. 

For example, siteSearch=ul will be expanded to siteSearch=*.ul.pt|ul,pt

Related #1014
