### ISSUE TITLE
Button to change language should be white when click (Mobile)

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#988]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/?&l=pt

**What happened?**
1.  Click "Menu"
2. Click "English". 

**What should have happened?**

When we click on "English", the button should be white like the button "sobre".

**Screenshots**
<img width="239" alt="loool" src="https://user-images.githubusercontent.com/25795364/88271664-66032480-cccf-11ea-98bf-ea5f15716a3a.png">

**Comment by hmendes** [comment]
Solved.
