### ISSUE TITLE
Links below the award banner (homepage) with the wrong color

### ISSUE THREAD

**Issue by hmendes** [arquivo/pwa-technologies#992]
**What is the URL that originated the issue?**
https://arquivo.pt

**What happened?**
All links should be consistent
![image](https://user-images.githubusercontent.com/165853/88379937-a0d28e80-cd9b-11ea-8f20-e18489d712c3.png)

For instance, "O que é o Arquivo.pt" and "Testemunhos de utilizadores" must be blue.
![image](https://user-images.githubusercontent.com/165853/88380137-e4c59380-cd9b-11ea-964f-fa805f3c2523.png)

Also, "Testemunhos de utilizadores" link to a wrong page: https://sobre.arquivo.pt/pt/colabore/premio-arquivo-pt-2020/

**Comment by dcgomes** [comment]
Headings "O que é o Arquivo.pt?" and "Testemunhos de utilizadores" are linking to https://sobre.arquivo.pt/pt/colabore/premio-arquivo-pt-2020/

Remove these links.

Same problem on English version: https://preprod.arquivo.pt/?l=en

**Comment by pcabritafccn** [comment]
This issue is now closed.
