### ISSUE TITLE
Number of versions per year disappeared (List versions)

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#993]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/page/search?hitsPerPage=10&query=fccn.pt&l=pt&ion-dt-1=1996-01-01&ion-dt-0=2020-07-24&dateStart=01%2F01%2F1996&dateEnd=24%2F07%2F2020

**Screenshots**

**NOW**

![sss](https://user-images.githubusercontent.com/25795364/88381084-9d400700-cd9d-11ea-8a21-23e7f737a768.jpg)

**BEFORE**
![sfsf](https://user-images.githubusercontent.com/25795364/88381193-daa49480-cd9d-11ea-8e88-1e929060a28d.JPG)

**Comment by dcgomes** [comment]
On the List view the number of versions should be presented.
