### ISSUE TITLE
Link "Saiba mais" (award banner in the homepage) must be consistent (blue)

### ISSUE THREAD

**Issue by hmendes** [arquivo/pwa-technologies#994]
**What is the URL that originated the issue?**
https://arquivo.pt/
https://arquivo.pt/img/homepage-premio-card-pt-desktop.jpg

**What happened?**
Button "Saiba mais" with the wrong style.

**What should have happened?**
Button must be blue or removed from the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/165853/88381465-64ecf880-cd9e-11ea-85c1-8377f6376a31.png)

**Comment by igobranco** [comment]
The image already have been replaced, during development of #975. But nevertheless the "Saiba mais" button problem still exists. 

http://preprod.arquivo.pt/img/homepage-premio-card-pt-desktop.jpg

![image](https://user-images.githubusercontent.com/67018/88381774-f0ff2000-cd9e-11ea-94eb-54ad8140f759.png)

**Comment by amourao** [comment]
Image replaced as a part of https://github.com/arquivo/arquivo-webapp/commit/ac405696797490b1dcf5c78520c8573bddac070f
