### ISSUE TITLE
The Menu button do not have size

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#995]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/

**What happened?**
In order to run the functional tests, the button "Menu" on the home page needs to have size. 
If not, the saucelabs will return the following error:

SauceOnDemandSessionID=53b50b2a0db14454adf2a1a7af2ddf90 job-name=pt.fccn.mobile.arquivo.tests.menu.MenuAboutHomepageTest.menuAboutHomepagePTTest[0]
Job link: https://saucelabs.com/jobs/7c20a1a1c86b4d2587d8b490992f58eb?auth=618f154f2f921ee757e7156e998aeaa6
org.openqa.selenium.ElementNotInteractableException: element not interactable: element has zero size

Screenshot of the sauce labs:
![image](https://user-images.githubusercontent.com/67018/88399528-eb193700-cdbe-11ea-8ffc-e5bb1f733b3e.png)

**Comment by igobranco** [comment]
@PedroG1515 I've attach the sauce labs screenshot because it's gone in a couple of days.
