### ISSUE TITLE
Going to "About" button on Arquivo.pt we go to another interface and can't go back

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#997]
**What is the URL that originated the issue?**
arquivo.pt

**What happened?**
On clicking on "About" button on Arquivo.pt we go to another interface and can't go back

**What should have happened?**
Should open as target _blank

**Screenshots**
<img width="959" alt="2020_07_28_10_06_17_Arquivo pt_pesquisa_sobre_o_passado" src="https://user-images.githubusercontent.com/44206545/88644202-9a555700-d0ba-11ea-984e-268986cfb14f.png">

**Comment by hmendes** [comment]
This issue is now solved.
