### ISSUE TITLE
There is no button "list" when we are seeing the list

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#998]
**What is the URL that originated the issue?**
https://arquivo.pt/page/search?hitsPerPage=10&query=dn.pt&l=pt&ion-dt-0=1996-01-01&ion-dt-1=2020-07-28&dateStart=01%2F01%2F1996&dateEnd=28%2F07%2F2020

**What happened?**
When I see as a list, the button "list" is invisible and the button "table" is visible.
When I see as table the button "table is invisible and the button "list" is visible.

**What should have happened?**
Two buttons would be better

**Screenshots**
<img width="958" alt="2020_07_28_10_14_53_" src="https://user-images.githubusercontent.com/44206545/88644915-70506480-d0bb-11ea-8744-250c5a37e749.png">

**Comment by dcgomes** [comment]
Put all buttons in the same color light blue.

**Comment by hmendes** [comment]
Solved.
